-- ============================================================
-- VINEXPRESS - THIẾT LẬP DATABASE ĐẦY ĐỦ (SUPABASE / POSTGRESQL)
-- Chạy một lần trong Supabase Dashboard > SQL Editor.
-- Tài khoản đăng nhập do Supabase Auth (auth.users) quản lý.
-- ============================================================

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS unaccent;

CREATE TABLE IF NOT EXISTS public.khach_hang (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_user_id UUID UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
    ho_ten TEXT NOT NULL,
    so_dien_thoai VARCHAR(20),
    email TEXT UNIQUE,
    mat_khau TEXT NOT NULL DEFAULT 'SUPABASE_AUTH',
    dia_chi TEXT,
    avt TEXT,
    trang_thai VARCHAR(20) NOT NULL DEFAULT 'HOAT_DONG',
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_khach_hang_trang_thai
        CHECK (trang_thai IN ('HOAT_DONG', 'KHOA'))
);

CREATE TABLE IF NOT EXISTS public.khu_vuc (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten_khu_vuc TEXT NOT NULL,
    tinh_thanh TEXT NOT NULL,
    phuong_xa TEXT NOT NULL,
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_khu_vuc_hanh_chinh UNIQUE (ten_khu_vuc, tinh_thanh, phuong_xa)
);

CREATE TABLE IF NOT EXISTS public.kho_hang (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_kho VARCHAR(30) NOT NULL UNIQUE,
    ten_kho TEXT NOT NULL,
    dia_chi TEXT NOT NULL,
    khu_vuc_id BIGINT NOT NULL REFERENCES public.khu_vuc(id),
    so_dien_thoai VARCHAR(20),
    trang_thai VARCHAR(20) NOT NULL DEFAULT 'HOAT_DONG',
    cap_kho SMALLINT NOT NULL DEFAULT 1,
    kho_trung_tam_id BIGINT REFERENCES public.kho_hang(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_kho_hang_trang_thai CHECK (trang_thai IN ('HOAT_DONG', 'TAM_NGUNG')),
    CONSTRAINT chk_kho_hang_cap_kho CHECK (
        (cap_kho = 1 AND kho_trung_tam_id IS NULL)
        OR (cap_kho = 2 AND kho_trung_tam_id IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS public.don_hang (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_van_don VARCHAR(30) NOT NULL UNIQUE,
    ma_qr UUID NOT NULL DEFAULT gen_random_uuid(),
    khach_hang_id BIGINT NOT NULL REFERENCES public.khach_hang(id),
    nguoi_gui_ten TEXT NOT NULL,
    nguoi_gui_dia_chi TEXT NOT NULL,
    nguoi_gui_sdt VARCHAR(20) NOT NULL,
    nguoi_nhan_ten TEXT NOT NULL,
    nguoi_nhan_dia_chi TEXT NOT NULL,
    nguoi_nhan_sdt VARCHAR(20) NOT NULL,
    can_nang NUMERIC(12,2) NOT NULL,
    gia_tri_hang NUMERIC(14,2) NOT NULL DEFAULT 0,
    phi_van_chuyen NUMERIC(14,2) NOT NULL DEFAULT 0,
    cod NUMERIC(14,2) NOT NULL DEFAULT 0,
    kho_gui_id BIGINT REFERENCES public.kho_hang(id),
    kho_dich_id BIGINT REFERENCES public.kho_hang(id),
    kho_trung_tam_gui_id BIGINT REFERENCES public.kho_hang(id),
    kho_trung_tam_dich_id BIGINT REFERENCES public.kho_hang(id),
    khoang_cach_km NUMERIC(12,2),
    phuong_tien VARCHAR(30),
    trang_thai VARCHAR(30) NOT NULL DEFAULT 'CHO_LAY_HANG',
    ghi_chu TEXT,
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_don_hang_phuong_tien
        CHECK (phuong_tien IS NULL OR phuong_tien IN ('XE_MAY', 'XE_TAI')),
    CONSTRAINT chk_don_hang_kho CHECK (
        (phuong_tien = 'XE_MAY' AND khoang_cach_km <= 50
            AND kho_gui_id IS NULL AND kho_dich_id IS NULL)
        OR (phuong_tien = 'XE_TAI' AND khoang_cach_km > 50
            AND kho_gui_id IS NOT NULL AND kho_dich_id IS NOT NULL
            AND kho_gui_id <> kho_dich_id
            AND kho_trung_tam_gui_id IS NOT NULL
            AND kho_trung_tam_dich_id IS NOT NULL)
        OR (phuong_tien IS NULL AND khoang_cach_km IS NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_khu_vuc_dia_ban
    ON public.khu_vuc (tinh_thanh, phuong_xa);
CREATE INDEX IF NOT EXISTS idx_kho_hang_khu_vuc ON public.kho_hang (khu_vuc_id);
CREATE INDEX IF NOT EXISTS idx_don_hang_khach_hang ON public.don_hang (khach_hang_id);

-- Kho cấp 2 chỉ được nối với kho cấp 1 trong cùng tỉnh/thành.
CREATE OR REPLACE FUNCTION public.kiem_tra_cay_kho()
RETURNS TRIGGER LANGUAGE plpgsql SET search_path = public AS $$
DECLARE
    v_cap_trung_tam SMALLINT;
    v_tinh_kho TEXT;
    v_tinh_trung_tam TEXT;
BEGIN
    IF NEW.cap_kho = 1 THEN
        NEW.kho_trung_tam_id := NULL;
        RETURN NEW;
    END IF;
    SELECT kh.cap_kho, kv.tinh_thanh
    INTO v_cap_trung_tam, v_tinh_trung_tam
    FROM public.kho_hang kh JOIN public.khu_vuc kv ON kv.id = kh.khu_vuc_id
    WHERE kh.id = NEW.kho_trung_tam_id;
    SELECT tinh_thanh INTO v_tinh_kho FROM public.khu_vuc WHERE id = NEW.khu_vuc_id;
    IF NEW.cap_kho <> 2 OR v_cap_trung_tam <> 1
       OR v_tinh_kho IS DISTINCT FROM v_tinh_trung_tam THEN
        RAISE EXCEPTION 'Kho cấp 2 phải liên kết với một kho cấp 1 cùng tỉnh/thành';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_kiem_tra_cay_kho ON public.kho_hang;
CREATE TRIGGER trg_kiem_tra_cay_kho
BEFORE INSERT OR UPDATE OF cap_kho, kho_trung_tam_id, khu_vuc_id ON public.kho_hang
FOR EACH ROW EXECUTE FUNCTION public.kiem_tra_cay_kho();

-- Dữ liệu địa bàn mới của API v2 (tỉnh/thành -> phường/xã/đặc khu).
INSERT INTO public.khu_vuc (ten_khu_vuc, tinh_thanh, phuong_xa) VALUES
    ('Trung tâm TP.HCM', 'Thành phố Hồ Chí Minh', 'Phường Sài Gòn'),
    ('Phía Đông TP.HCM', 'Thành phố Hồ Chí Minh', 'Phường An Phú'),
    ('Trung tâm Hà Nội', 'Thành phố Hà Nội', 'Phường Hoàn Kiếm'),
    ('Phía Tây Hà Nội', 'Thành phố Hà Nội', 'Phường Từ Liêm'),
    ('Trung tâm Đà Nẵng', 'Thành phố Đà Nẵng', 'Phường Hải Châu'),
    ('Trung tâm Cần Thơ', 'Thành phố Cần Thơ', 'Phường Ninh Kiều')
ON CONFLICT (ten_khu_vuc, tinh_thanh, phuong_xa) DO NOTHING;

INSERT INTO public.kho_hang
    (ma_kho, ten_kho, dia_chi, khu_vuc_id, so_dien_thoai, trang_thai, cap_kho)
SELECT v.ma_kho, v.ten_kho, v.dia_chi, kv.id, v.so_dien_thoai, 'HOAT_DONG', v.cap_kho
FROM (VALUES
    ('HCM-Q1', 'Kho trung tâm Sài Gòn', '12 Nguyễn Huệ, Phường Sài Gòn, Thành phố Hồ Chí Minh', 'Thành phố Hồ Chí Minh', 'Phường Sài Gòn', '02838220001', 1),
    ('HCM-AP', 'Kho trung chuyển An Phú', '86 Mai Chí Thọ, Phường An Phú, Thành phố Hồ Chí Minh', 'Thành phố Hồ Chí Minh', 'Phường An Phú', '02837240002', 1),
    ('HN-HK', 'Kho trung tâm Hoàn Kiếm', '25 Tràng Tiền, Phường Hoàn Kiếm, Thành phố Hà Nội', 'Thành phố Hà Nội', 'Phường Hoàn Kiếm', '02439260003', 1),
    ('HN-TL', 'Kho trung chuyển Từ Liêm', '18 Hàm Nghi, Phường Từ Liêm, Thành phố Hà Nội', 'Thành phố Hà Nội', 'Phường Từ Liêm', '02437680004', 1),
    ('DNG-HC', 'Kho trung tâm Hải Châu', '40 Bạch Đằng, Phường Hải Châu, Thành phố Đà Nẵng', 'Thành phố Đà Nẵng', 'Phường Hải Châu', '02363560005', 1),
    ('CT-NK', 'Kho trung tâm Ninh Kiều', '15 Hai Bà Trưng, Phường Ninh Kiều, Thành phố Cần Thơ', 'Thành phố Cần Thơ', 'Phường Ninh Kiều', '02923760006', 1)
) AS v(ma_kho, ten_kho, dia_chi, tinh_thanh, phuong_xa, so_dien_thoai, cap_kho)
JOIN public.khu_vuc kv ON kv.tinh_thanh = v.tinh_thanh AND kv.phuong_xa = v.phuong_xa
ON CONFLICT (ma_kho) DO UPDATE SET
    ten_kho = EXCLUDED.ten_kho, dia_chi = EXCLUDED.dia_chi,
    khu_vuc_id = EXCLUDED.khu_vuc_id, so_dien_thoai = EXCLUDED.so_dien_thoai,
    trang_thai = EXCLUDED.trang_thai, cap_kho = EXCLUDED.cap_kho;

UPDATE public.kho_hang ve_tinh
SET cap_kho = 2,
    kho_trung_tam_id = trung_tam.id
FROM public.kho_hang trung_tam
WHERE (ve_tinh.ma_kho, trung_tam.ma_kho) IN (('HCM-AP', 'HCM-Q1'), ('HN-TL', 'HN-HK'));

CREATE OR REPLACE FUNCTION public.tim_kho_theo_dia_chi(p_dia_chi TEXT, p_kho_bo_qua BIGINT DEFAULT NULL)
RETURNS BIGINT LANGUAGE plpgsql SECURITY DEFINER STABLE SET search_path = public AS $$
DECLARE v_dia_chi TEXT; v_kho_id BIGINT;
BEGIN
    v_dia_chi := public.unaccent(LOWER(COALESCE(p_dia_chi, '')));
    SELECT kh.id INTO v_kho_id
    FROM public.kho_hang kh JOIN public.khu_vuc kv ON kv.id = kh.khu_vuc_id
    WHERE kh.trang_thai = 'HOAT_DONG'
      AND v_dia_chi LIKE '%' || public.unaccent(LOWER(BTRIM(kv.tinh_thanh))) || '%'
      AND v_dia_chi LIKE '%' || public.unaccent(LOWER(BTRIM(kv.phuong_xa))) || '%'
      AND (p_kho_bo_qua IS NULL OR kh.id <> p_kho_bo_qua)
    ORDER BY kh.id LIMIT 1;
    IF v_kho_id IS NULL THEN
        RAISE EXCEPTION 'Tỉnh/thành hoặc phường/xã trong địa chỉ này chưa có kho hoạt động: %', p_dia_chi;
    END IF;
    RETURN v_kho_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.tim_kho_trung_tam(p_kho_id BIGINT)
RETURNS BIGINT LANGUAGE sql SECURITY DEFINER STABLE SET search_path = public AS $$
    SELECT CASE WHEN cap_kho = 1 THEN id WHEN cap_kho = 2 THEN kho_trung_tam_id END
    FROM public.kho_hang WHERE id = p_kho_id AND trang_thai = 'HOAT_DONG';
$$;

CREATE OR REPLACE FUNCTION public.tao_don_hang_khach_hang(
    p_nguoi_gui_ten TEXT, p_nguoi_gui_dia_chi TEXT, p_nguoi_gui_sdt TEXT,
    p_nguoi_nhan_ten TEXT, p_nguoi_nhan_dia_chi TEXT, p_nguoi_nhan_sdt TEXT,
    p_can_nang NUMERIC, p_gia_tri_hang NUMERIC, p_phi_van_chuyen NUMERIC,
    p_cod NUMERIC, p_khoang_cach_km NUMERIC, p_ghi_chu TEXT DEFAULT NULL
) RETURNS TABLE (id BIGINT, ma_van_don VARCHAR, ma_qr UUID, trang_thai VARCHAR,
    khoang_cach_km NUMERIC, phuong_tien VARCHAR, ngay_tao TIMESTAMPTZ)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
    v_khach_hang_id BIGINT; v_kho_gui_id BIGINT; v_kho_dich_id BIGINT;
    v_kho_trung_tam_gui_id BIGINT; v_kho_trung_tam_dich_id BIGINT;
    v_phuong_tien VARCHAR(30);
BEGIN
    IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Bạn chưa đăng nhập'; END IF;
    SELECT id INTO v_khach_hang_id FROM public.khach_hang
    WHERE auth_user_id = auth.uid() AND trang_thai = 'HOAT_DONG';
    IF v_khach_hang_id IS NULL THEN RAISE EXCEPTION 'Không tìm thấy tài khoản khách hàng đang hoạt động'; END IF;
    IF p_can_nang <= 0 OR p_khoang_cach_km IS NULL OR p_khoang_cach_km < 0 THEN
        RAISE EXCEPTION 'Thông tin khối lượng hoặc khoảng cách không hợp lệ';
    END IF;
    IF p_khoang_cach_km <= 50 THEN
        v_phuong_tien := 'XE_MAY';
    ELSE
        v_phuong_tien := 'XE_TAI';
        v_kho_gui_id := public.tim_kho_theo_dia_chi(p_nguoi_gui_dia_chi);
        v_kho_dich_id := public.tim_kho_theo_dia_chi(p_nguoi_nhan_dia_chi, v_kho_gui_id);
        v_kho_trung_tam_gui_id := public.tim_kho_trung_tam(v_kho_gui_id);
        v_kho_trung_tam_dich_id := public.tim_kho_trung_tam(v_kho_dich_id);
        IF v_kho_trung_tam_gui_id IS NULL OR v_kho_trung_tam_dich_id IS NULL THEN
            RAISE EXCEPTION 'Kho địa phương chưa được gán kho trung tâm';
        END IF;
    END IF;
    RETURN QUERY INSERT INTO public.don_hang (
        ma_van_don, khach_hang_id, nguoi_gui_ten, nguoi_gui_dia_chi, nguoi_gui_sdt,
        nguoi_nhan_ten, nguoi_nhan_dia_chi, nguoi_nhan_sdt, can_nang, gia_tri_hang,
        phi_van_chuyen, cod, kho_gui_id, kho_dich_id, kho_trung_tam_gui_id,
        kho_trung_tam_dich_id, khoang_cach_km, phuong_tien, trang_thai, ghi_chu
    ) VALUES (
        'VEX' || UPPER(SUBSTRING(REPLACE(gen_random_uuid()::TEXT, '-', '') FROM 1 FOR 12)),
        v_khach_hang_id, BTRIM(p_nguoi_gui_ten), BTRIM(p_nguoi_gui_dia_chi), BTRIM(p_nguoi_gui_sdt),
        BTRIM(p_nguoi_nhan_ten), BTRIM(p_nguoi_nhan_dia_chi), BTRIM(p_nguoi_nhan_sdt),
        p_can_nang, GREATEST(p_gia_tri_hang, 0), GREATEST(p_phi_van_chuyen, 0), GREATEST(p_cod, 0),
        v_kho_gui_id, v_kho_dich_id, v_kho_trung_tam_gui_id, v_kho_trung_tam_dich_id,
        ROUND(p_khoang_cach_km, 2), v_phuong_tien, 'CHO_LAY_HANG', NULLIF(BTRIM(p_ghi_chu), '')
    ) RETURNING don_hang.id, don_hang.ma_van_don, don_hang.ma_qr, don_hang.trang_thai,
        don_hang.khoang_cach_km, don_hang.phuong_tien, don_hang.ngay_tao;
END;
$$;

CREATE OR REPLACE FUNCTION public.tao_ho_so_khach_hang()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
    INSERT INTO public.khach_hang (auth_user_id, ho_ten, so_dien_thoai, email, mat_khau, dia_chi, trang_thai)
    VALUES (NEW.id, COALESCE(NULLIF(BTRIM(NEW.raw_user_meta_data->>'ho_ten'), ''), 'Khách hàng'),
        NEW.raw_user_meta_data->>'so_dien_thoai', NEW.email, 'SUPABASE_AUTH',
        NULLIF(BTRIM(NEW.raw_user_meta_data->>'dia_chi'), ''), 'HOAT_DONG');
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_tao_ho_so_khach_hang ON auth.users;
CREATE TRIGGER trg_tao_ho_so_khach_hang AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.tao_ho_so_khach_hang();

ALTER TABLE public.khach_hang ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Khach hang xem ho so cua minh" ON public.khach_hang;
CREATE POLICY "Khach hang xem ho so cua minh" ON public.khach_hang
FOR SELECT TO authenticated USING (auth.uid() = auth_user_id);
DROP POLICY IF EXISTS "Khach hang cap nhat ho so cua minh" ON public.khach_hang;
CREATE POLICY "Khach hang cap nhat ho so cua minh" ON public.khach_hang
FOR UPDATE TO authenticated USING (auth.uid() = auth_user_id) WITH CHECK (auth.uid() = auth_user_id);
GRANT SELECT, UPDATE ON public.khach_hang TO authenticated;
REVOKE ALL ON FUNCTION public.tim_kho_theo_dia_chi(TEXT, BIGINT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tim_kho_trung_tam(BIGINT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tao_don_hang_khach_hang(
    TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, NUMERIC, NUMERIC, NUMERIC, NUMERIC, NUMERIC, TEXT
) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.tao_don_hang_khach_hang(
    TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, NUMERIC, NUMERIC, NUMERIC, NUMERIC, NUMERIC, TEXT
) TO authenticated;

COMMIT;

-- ============================================================
-- CÂU TRUY VẤN KIỂM TRA / VẬN HÀNH
-- ============================================================

-- 1. Danh sách kho và kho trung tâm của nó.
SELECT kh.ma_kho, kh.ten_kho, kh.cap_kho, kv.tinh_thanh, kv.phuong_xa,
       trung_tam.ma_kho AS ma_kho_trung_tam
FROM public.kho_hang kh
JOIN public.khu_vuc kv ON kv.id = kh.khu_vuc_id
LEFT JOIN public.kho_hang trung_tam ON trung_tam.id = kh.kho_trung_tam_id
ORDER BY kv.tinh_thanh, kh.cap_kho, kh.ma_kho;

-- 2. Tuyến vận chuyển của các đơn xe tải.
SELECT dh.ma_van_don,
       kho_gui.ma_kho AS kho_nhan_gui,
       trung_tam_gui.ma_kho AS trung_tam_gui,
       trung_tam_dich.ma_kho AS trung_tam_dich,
       kho_dich.ma_kho AS kho_giao_nhan,
       dh.trang_thai
FROM public.don_hang dh
LEFT JOIN public.kho_hang kho_gui ON kho_gui.id = dh.kho_gui_id
LEFT JOIN public.kho_hang trung_tam_gui ON trung_tam_gui.id = dh.kho_trung_tam_gui_id
LEFT JOIN public.kho_hang trung_tam_dich ON trung_tam_dich.id = dh.kho_trung_tam_dich_id
LEFT JOIN public.kho_hang kho_dich ON kho_dich.id = dh.kho_dich_id
WHERE dh.phuong_tien = 'XE_TAI'
ORDER BY dh.ngay_tao DESC;
