-- ============================================================
-- HỆ THỐNG QUẢN LÝ VẬN CHUYỂN - SUPABASE POSTGRESQL
-- LƯU Ý: Script này xóa dữ liệu bảng cũ và tạo lại từ đầu.
-- Không sử dụng GO vì Supabase dùng PostgreSQL.
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================
-- 1. XÓA HÀM VÀ BẢNG CŨ
-- ============================================================

DROP FUNCTION IF EXISTS quet_qr_don_hang(
    TEXT,
    BIGINT,
    BIGINT,
    TEXT,
    TEXT,
    TEXT,
    DOUBLE PRECISION,
    DOUBLE PRECISION
);

DROP FUNCTION IF EXISTS cap_nhat_thoi_gian();

DROP TABLE IF EXISTS danh_gia CASCADE;
DROP TABLE IF EXISTS nhat_ky_don_hang CASCADE;
DROP TABLE IF EXISTS niem_phong_xe CASCADE;
DROP TABLE IF EXISTS chuyen_xe_chang CASCADE;
DROP TABLE IF EXISTS chi_tiet_chuyen_xe CASCADE;
DROP TABLE IF EXISTS chuyen_xe CASCADE;
DROP TABLE IF EXISTS xe CASCADE;
DROP TABLE IF EXISTS don_hang CASCADE;
DROP TABLE IF EXISTS nhan_vien CASCADE;
DROP TABLE IF EXISTS kho_hang CASCADE;
DROP TABLE IF EXISTS khu_vuc CASCADE;
DROP TABLE IF EXISTS khach_hang CASCADE;

-- ============================================================
-- 2. BẢNG KHÁCH HÀNG
-- ============================================================

CREATE TABLE khach_hang (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    ho_ten VARCHAR(255) NOT NULL,
    so_dien_thoai VARCHAR(20) NOT NULL,
    email VARCHAR(255),
    mat_khau TEXT NOT NULL,

    dia_chi TEXT,
    avt TEXT,

    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    trang_thai VARCHAR(30) NOT NULL DEFAULT 'HOAT_DONG',

    CONSTRAINT uq_khach_hang_sdt UNIQUE (so_dien_thoai),
    CONSTRAINT uq_khach_hang_email UNIQUE (email),

    CONSTRAINT chk_khach_hang_trang_thai CHECK (
        trang_thai IN (
            'HOAT_DONG',
            'TAM_KHOA',
            'DA_KHOA'
        )
    )
);

-- ============================================================
-- 3. BẢNG KHU VỰC
-- ============================================================

CREATE TABLE khu_vuc (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    ten_khu_vuc VARCHAR(255) NOT NULL,
    tinh_thanh VARCHAR(255) NOT NULL,
    quan_huyen VARCHAR(255),
    phuong_xa VARCHAR(255),

    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_khu_vuc UNIQUE (
        ten_khu_vuc,
        tinh_thanh,
        quan_huyen,
        phuong_xa
    )
);

-- ============================================================
-- 4. BẢNG KHO HÀNG
-- ============================================================

CREATE TABLE kho_hang (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    ma_kho VARCHAR(50) NOT NULL,
    ten_kho VARCHAR(255) NOT NULL,
    dia_chi TEXT NOT NULL,

    khu_vuc_id BIGINT NOT NULL,

    so_dien_thoai VARCHAR(20),

    trang_thai VARCHAR(30) NOT NULL DEFAULT 'HOAT_DONG',

    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_kho_hang_ma_kho UNIQUE (ma_kho),

    CONSTRAINT fk_kho_hang_khu_vuc
        FOREIGN KEY (khu_vuc_id)
        REFERENCES khu_vuc(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_kho_hang_trang_thai CHECK (
        trang_thai IN (
            'HOAT_DONG',
            'TAM_NGUNG',
            'DA_DONG_CUA'
        )
    )
);

-- ============================================================
-- 5. BẢNG NHÂN VIÊN
-- ============================================================

CREATE TABLE nhan_vien (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    kho_hang_id BIGINT,

    ho_ten VARCHAR(255) NOT NULL,
    so_dien_thoai VARCHAR(20) NOT NULL,
    email VARCHAR(255),

    mat_khau TEXT NOT NULL,
    dia_chi TEXT,

    so_cccd VARCHAR(20),

    anh_cccd_truoc TEXT,
    anh_cccd_sau TEXT,
    anh_khuon_mat TEXT,

    vai_tro VARCHAR(30) NOT NULL,

    trang_thai_duyet VARCHAR(30) NOT NULL DEFAULT 'CHO_DUYET',
    trang_thai VARCHAR(30) NOT NULL DEFAULT 'HOAT_DONG',

    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_nhan_vien_sdt UNIQUE (so_dien_thoai),
    CONSTRAINT uq_nhan_vien_email UNIQUE (email),
    CONSTRAINT uq_nhan_vien_cccd UNIQUE (so_cccd),

    CONSTRAINT fk_nhan_vien_kho_hang
        FOREIGN KEY (kho_hang_id)
        REFERENCES kho_hang(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_nhan_vien_vai_tro CHECK (
        vai_tro IN (
            'ADMIN',
            'QUAN_LY_KHO',
            'NHAN_VIEN_KHO',
            'VAN_CHUYEN',
            'SHIPPER'
        )
    ),

    CONSTRAINT chk_nhan_vien_trang_thai_duyet CHECK (
        trang_thai_duyet IN (
            'CHO_DUYET',
            'DA_DUYET',
            'TU_CHOI'
        )
    ),

    CONSTRAINT chk_nhan_vien_trang_thai CHECK (
        trang_thai IN (
            'HOAT_DONG',
            'TAM_KHOA',
            'DA_NGHI'
        )
    )
);

-- ============================================================
-- 6. BẢNG ĐƠN HÀNG
-- ============================================================

CREATE TABLE don_hang (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    ma_van_don VARCHAR(50) NOT NULL,

    -- Có thể dùng UUID này để tạo nội dung mã QR.
    ma_qr UUID NOT NULL DEFAULT GEN_RANDOM_UUID(),

    khach_hang_id BIGINT NOT NULL,

    nguoi_gui_ten VARCHAR(255) NOT NULL,
    nguoi_gui_dia_chi TEXT NOT NULL,
    nguoi_gui_sdt VARCHAR(20) NOT NULL,

    nguoi_nhan_ten VARCHAR(255) NOT NULL,
    nguoi_nhan_dia_chi TEXT NOT NULL,
    nguoi_nhan_sdt VARCHAR(20) NOT NULL,

    can_nang NUMERIC(12,3) NOT NULL DEFAULT 0,
    gia_tri_hang NUMERIC(18,2) NOT NULL DEFAULT 0,
    phi_van_chuyen NUMERIC(18,2) NOT NULL DEFAULT 0,
    cod NUMERIC(18,2) NOT NULL DEFAULT 0,

    kho_gui_id BIGINT NOT NULL,
    kho_dich_id BIGINT NOT NULL,

    -- Kho hiện tại của đơn hàng.
    kho_hien_tai_id BIGINT,

    -- Nhân viên đang giữ hoặc đang xử lý đơn hàng.
    nhan_vien_hien_tai_id BIGINT,

    trang_thai VARCHAR(50) NOT NULL DEFAULT 'CHO_LAY_HANG',

    ghi_chu TEXT,

    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ngay_lay_hang TIMESTAMPTZ,
    ngay_giao_hang TIMESTAMPTZ,

    CONSTRAINT uq_don_hang_ma_van_don UNIQUE (ma_van_don),
    CONSTRAINT uq_don_hang_ma_qr UNIQUE (ma_qr),

    CONSTRAINT fk_don_hang_khach_hang
        FOREIGN KEY (khach_hang_id)
        REFERENCES khach_hang(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_don_hang_kho_gui
        FOREIGN KEY (kho_gui_id)
        REFERENCES kho_hang(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_don_hang_kho_dich
        FOREIGN KEY (kho_dich_id)
        REFERENCES kho_hang(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_don_hang_kho_hien_tai
        FOREIGN KEY (kho_hien_tai_id)
        REFERENCES kho_hang(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_don_hang_nhan_vien_hien_tai
        FOREIGN KEY (nhan_vien_hien_tai_id)
        REFERENCES nhan_vien(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_don_hang_can_nang CHECK (can_nang >= 0),
    CONSTRAINT chk_don_hang_gia_tri CHECK (gia_tri_hang >= 0),
    CONSTRAINT chk_don_hang_phi CHECK (phi_van_chuyen >= 0),
    CONSTRAINT chk_don_hang_cod CHECK (cod >= 0),

    CONSTRAINT chk_don_hang_kho CHECK (
        kho_gui_id <> kho_dich_id
    ),

    CONSTRAINT chk_don_hang_trang_thai CHECK (
        trang_thai IN (
            'CHO_LAY_HANG',
            'DA_LAY_HANG',
            'DANG_VAN_CHUYEN',
            'DEN_KHO_TRUNG_CHUYEN',
            'DEN_KHO_DICH',
            'GIAO_CHO_SHIPPER',
            'DANG_GIAO_HANG',
            'DA_GIAO_HANG',
            'GIAO_HANG_THAT_BAI',
            'HOAN_HANG',
            'DA_HUY'
        )
    )
);

-- ============================================================
-- 7. BẢNG XE
-- ============================================================

CREATE TABLE xe (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    tai_xe_id BIGINT,

    trang_thai VARCHAR(30) NOT NULL DEFAULT 'SAN_SANG',
    tai_trong NUMERIC(12,2) NOT NULL DEFAULT 0,
    bien_so_xe VARCHAR(30) NOT NULL,

    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_xe_bien_so UNIQUE (bien_so_xe),

    CONSTRAINT fk_xe_tai_xe
        FOREIGN KEY (tai_xe_id)
        REFERENCES nhan_vien(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_xe_tai_trong CHECK (tai_trong >= 0),

    CONSTRAINT chk_xe_trang_thai CHECK (
        trang_thai IN (
            'SAN_SANG',
            'DANG_CHAY',
            'BAO_TRI',
            'NGUNG_HOAT_DONG'
        )
    )
);

-- ============================================================
-- 8. BẢNG CHUYẾN XE
-- ============================================================

CREATE TABLE chuyen_xe (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    xe_id BIGINT NOT NULL,

    ma_chuyen VARCHAR(50) NOT NULL,
    trang_thai VARCHAR(30) NOT NULL DEFAULT 'CHO_KHOI_HANH',

    ngay_khoi_hanh TIMESTAMPTZ,
    ngay_du_kien TIMESTAMPTZ,
    ngay_den_thuc_te TIMESTAMPTZ,

    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_chuyen_xe_ma_chuyen UNIQUE (ma_chuyen),

    CONSTRAINT fk_chuyen_xe_xe
        FOREIGN KEY (xe_id)
        REFERENCES xe(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_chuyen_xe_trang_thai CHECK (
        trang_thai IN (
            'CHO_KHOI_HANH',
            'DANG_XEP_HANG',
            'DANG_DI',
            'DA_DEN',
            'DA_HOAN_THANH',
            'DA_HUY'
        )
    )
);

-- ============================================================
-- 9. CHI TIẾT CHUYẾN XE
-- ============================================================

CREATE TABLE chi_tiet_chuyen_xe (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    chuyen_xe_id BIGINT NOT NULL,
    don_hang_id BIGINT NOT NULL,

    ngay_xep_hang TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ngay_do_hang TIMESTAMPTZ,

    trang_thai VARCHAR(30) NOT NULL DEFAULT 'DA_XEP_HANG',

    CONSTRAINT uq_chi_tiet_chuyen_xe UNIQUE (
        chuyen_xe_id,
        don_hang_id
    ),

    CONSTRAINT fk_chi_tiet_chuyen_xe_chuyen
        FOREIGN KEY (chuyen_xe_id)
        REFERENCES chuyen_xe(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_chi_tiet_chuyen_xe_don_hang
        FOREIGN KEY (don_hang_id)
        REFERENCES don_hang(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT chk_chi_tiet_chuyen_xe_trang_thai CHECK (
        trang_thai IN (
            'DA_XEP_HANG',
            'DANG_VAN_CHUYEN',
            'DA_DO_HANG'
        )
    )
);

-- ============================================================
-- 10. CÁC CHẶNG CỦA CHUYẾN XE
-- ============================================================

CREATE TABLE chuyen_xe_chang (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    chuyen_xe_id BIGINT NOT NULL,

    thu_tu_chuyen INTEGER NOT NULL,

    kho_di_id BIGINT NOT NULL,
    kho_den_id BIGINT NOT NULL,

    nguoi_phan_cong_id BIGINT,

    ngay_khoi_hanh TIMESTAMPTZ,
    ngay_den_du_kien TIMESTAMPTZ,
    ngay_den_thuc_te TIMESTAMPTZ,

    trang_thai VARCHAR(30) NOT NULL DEFAULT 'CHO_KHOI_HANH',

    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_chuyen_xe_chang_thu_tu UNIQUE (
        chuyen_xe_id,
        thu_tu_chuyen
    ),

    CONSTRAINT fk_chuyen_xe_chang_chuyen
        FOREIGN KEY (chuyen_xe_id)
        REFERENCES chuyen_xe(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_chuyen_xe_chang_kho_di
        FOREIGN KEY (kho_di_id)
        REFERENCES kho_hang(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_chuyen_xe_chang_kho_den
        FOREIGN KEY (kho_den_id)
        REFERENCES kho_hang(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_chuyen_xe_chang_nguoi_phan_cong
        FOREIGN KEY (nguoi_phan_cong_id)
        REFERENCES nhan_vien(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_chuyen_xe_chang_thu_tu CHECK (
        thu_tu_chuyen > 0
    ),

    CONSTRAINT chk_chuyen_xe_chang_kho CHECK (
        kho_di_id <> kho_den_id
    ),

    CONSTRAINT chk_chuyen_xe_chang_trang_thai CHECK (
        trang_thai IN (
            'CHO_KHOI_HANH',
            'DANG_DI',
            'DA_DEN',
            'DA_HUY'
        )
    )
);

-- ============================================================
-- 11. BẢNG NIÊM PHONG XE
-- ============================================================

CREATE TABLE niem_phong_xe (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    chuyen_xe_id BIGINT NOT NULL,

    ma_niem_phong VARCHAR(50) NOT NULL,

    kho_niem_phong_id BIGINT NOT NULL,
    nguoi_niem_phong_id BIGINT NOT NULL,
    thoi_gian_niem_phong TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    kho_mo_niem_phong_id BIGINT,
    nguoi_mo_id BIGINT,
    thoi_gian_mo TIMESTAMPTZ,

    trang_thai VARCHAR(30) NOT NULL DEFAULT 'DA_NIEM_PHONG',

    CONSTRAINT uq_niem_phong_ma UNIQUE (ma_niem_phong),

    CONSTRAINT fk_niem_phong_chuyen_xe
        FOREIGN KEY (chuyen_xe_id)
        REFERENCES chuyen_xe(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_niem_phong_kho_niem_phong
        FOREIGN KEY (kho_niem_phong_id)
        REFERENCES kho_hang(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_niem_phong_nguoi_niem_phong
        FOREIGN KEY (nguoi_niem_phong_id)
        REFERENCES nhan_vien(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_niem_phong_kho_mo
        FOREIGN KEY (kho_mo_niem_phong_id)
        REFERENCES kho_hang(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_niem_phong_nguoi_mo
        FOREIGN KEY (nguoi_mo_id)
        REFERENCES nhan_vien(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_niem_phong_trang_thai CHECK (
        trang_thai IN (
            'DA_NIEM_PHONG',
            'DA_MO',
            'HU_HONG',
            'MAT_NIEM_PHONG'
        )
    )
);

-- ============================================================
-- 12. NHẬT KÝ ĐƠN HÀNG
-- ============================================================

CREATE TABLE nhat_ky_don_hang (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nhan_vien_id BIGINT,
    don_hang_id BIGINT NOT NULL,
    khach_hang_id BIGINT,

    hanh_dong VARCHAR(100) NOT NULL,

    trang_thai_cu VARCHAR(50),
    trang_thai_moi VARCHAR(50),

    -- Lưu URL ảnh từ Supabase Storage.
    minh_chung TEXT,

    kho_id BIGINT,

    ghi_chu TEXT,

    vi_do DOUBLE PRECISION,
    kinh_do DOUBLE PRECISION,

    thoi_gian TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_nhat_ky_nhan_vien
        FOREIGN KEY (nhan_vien_id)
        REFERENCES nhan_vien(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_nhat_ky_don_hang
        FOREIGN KEY (don_hang_id)
        REFERENCES don_hang(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_nhat_ky_khach_hang
        FOREIGN KEY (khach_hang_id)
        REFERENCES khach_hang(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_nhat_ky_kho
        FOREIGN KEY (kho_id)
        REFERENCES kho_hang(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_nhat_ky_vi_do CHECK (
        vi_do IS NULL OR vi_do BETWEEN -90 AND 90
    ),

    CONSTRAINT chk_nhat_ky_kinh_do CHECK (
        kinh_do IS NULL OR kinh_do BETWEEN -180 AND 180
    )
);

-- ============================================================
-- 13. BẢNG ĐÁNH GIÁ
-- ============================================================

CREATE TABLE danh_gia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    khach_hang_id BIGINT NOT NULL,
    don_hang_id BIGINT NOT NULL,
    nhan_vien_id BIGINT,

    diem_danh_gia INTEGER NOT NULL,
    binh_luan TEXT,

    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_danh_gia_don_hang UNIQUE (
        khach_hang_id,
        don_hang_id
    ),

    CONSTRAINT fk_danh_gia_khach_hang
        FOREIGN KEY (khach_hang_id)
        REFERENCES khach_hang(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_danh_gia_don_hang
        FOREIGN KEY (don_hang_id)
        REFERENCES don_hang(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_danh_gia_nhan_vien
        FOREIGN KEY (nhan_vien_id)
        REFERENCES nhan_vien(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_danh_gia_diem CHECK (
        diem_danh_gia BETWEEN 1 AND 5
    )
);

-- ============================================================
-- 14. INDEX TĂNG TỐC TRUY VẤN
-- ============================================================

CREATE INDEX idx_kho_hang_khu_vuc
    ON kho_hang(khu_vuc_id);

CREATE INDEX idx_nhan_vien_kho_hang
    ON nhan_vien(kho_hang_id);

CREATE INDEX idx_nhan_vien_vai_tro
    ON nhan_vien(vai_tro);

CREATE INDEX idx_don_hang_khach_hang
    ON don_hang(khach_hang_id);

CREATE INDEX idx_don_hang_kho_gui
    ON don_hang(kho_gui_id);

CREATE INDEX idx_don_hang_kho_dich
    ON don_hang(kho_dich_id);

CREATE INDEX idx_don_hang_kho_hien_tai
    ON don_hang(kho_hien_tai_id);

CREATE INDEX idx_don_hang_trang_thai
    ON don_hang(trang_thai);

CREATE INDEX idx_chuyen_xe_xe
    ON chuyen_xe(xe_id);

CREATE INDEX idx_chi_tiet_chuyen_xe_don_hang
    ON chi_tiet_chuyen_xe(don_hang_id);

CREATE INDEX idx_chuyen_xe_chang_chuyen
    ON chuyen_xe_chang(chuyen_xe_id);

CREATE INDEX idx_nhat_ky_don_hang
    ON nhat_ky_don_hang(don_hang_id);

CREATE INDEX idx_nhat_ky_nhan_vien
    ON nhat_ky_don_hang(nhan_vien_id);

CREATE INDEX idx_nhat_ky_thoi_gian
    ON nhat_ky_don_hang(thoi_gian DESC);

-- ============================================================
-- 15. TRIGGER TỰ CẬP NHẬT NGÀY SỬA
-- ============================================================

CREATE OR REPLACE FUNCTION cap_nhat_thoi_gian()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.ngay_cap_nhat := NOW();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_khach_hang_cap_nhat
BEFORE UPDATE ON khach_hang
FOR EACH ROW
EXECUTE FUNCTION cap_nhat_thoi_gian();

CREATE TRIGGER trg_kho_hang_cap_nhat
BEFORE UPDATE ON kho_hang
FOR EACH ROW
EXECUTE FUNCTION cap_nhat_thoi_gian();

CREATE TRIGGER trg_nhan_vien_cap_nhat
BEFORE UPDATE ON nhan_vien
FOR EACH ROW
EXECUTE FUNCTION cap_nhat_thoi_gian();

CREATE TRIGGER trg_don_hang_cap_nhat
BEFORE UPDATE ON don_hang
FOR EACH ROW
EXECUTE FUNCTION cap_nhat_thoi_gian();

CREATE TRIGGER trg_xe_cap_nhat
BEFORE UPDATE ON xe
FOR EACH ROW
EXECUTE FUNCTION cap_nhat_thoi_gian();

CREATE TRIGGER trg_chuyen_xe_cap_nhat
BEFORE UPDATE ON chuyen_xe
FOR EACH ROW
EXECUTE FUNCTION cap_nhat_thoi_gian();

CREATE TRIGGER trg_chuyen_xe_chang_cap_nhat
BEFORE UPDATE ON chuyen_xe_chang
FOR EACH ROW
EXECUTE FUNCTION cap_nhat_thoi_gian();

CREATE TRIGGER trg_danh_gia_cap_nhat
BEFORE UPDATE ON danh_gia
FOR EACH ROW
EXECUTE FUNCTION cap_nhat_thoi_gian();

-- ============================================================
-- 16. HÀM QUÉT QR ĐƠN HÀNG
--
-- p_su_kien:
--   TU_DONG
--   LAY_HANG
--   DEN_KHO
--   GIAO_CHO_SHIPPER
--   BAT_DAU_GIAO_HANG
--   GIAO_HANG_THANH_CONG
--   GIAO_HANG_THAT_BAI
-- ============================================================

CREATE OR REPLACE FUNCTION quet_qr_don_hang(
    p_ma_van_don TEXT,
    p_nhan_vien_id BIGINT,
    p_kho_id BIGINT DEFAULT NULL,
    p_su_kien TEXT DEFAULT 'TU_DONG',
    p_minh_chung TEXT DEFAULT NULL,
    p_ghi_chu TEXT DEFAULT NULL,
    p_vi_do DOUBLE PRECISION DEFAULT NULL,
    p_kinh_do DOUBLE PRECISION DEFAULT NULL
)
RETURNS TABLE (
    thanh_cong BOOLEAN,
    don_hang_id BIGINT,
    ma_van_don TEXT,
    trang_thai_cu TEXT,
    trang_thai_moi TEXT,
    hanh_dong TEXT,
    ten_kho TEXT,
    thoi_gian TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_don_hang don_hang%ROWTYPE;
    v_nhan_vien nhan_vien%ROWTYPE;
    v_kho kho_hang%ROWTYPE;

    v_su_kien TEXT;
    v_trang_thai_cu TEXT;
    v_trang_thai_moi TEXT;
    v_hanh_dong TEXT;
    v_ten_kho TEXT;
BEGIN
    -- --------------------------------------------------------
    -- Kiểm tra mã vận đơn
    -- --------------------------------------------------------
    IF p_ma_van_don IS NULL OR BTRIM(p_ma_van_don) = '' THEN
        RAISE EXCEPTION 'Mã vận đơn không được để trống';
    END IF;

    -- Khóa đơn hàng trong lúc xử lý để tránh quét đồng thời.
    SELECT *
    INTO v_don_hang
    FROM don_hang
    WHERE UPPER(ma_van_don) = UPPER(BTRIM(p_ma_van_don))
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Không tìm thấy đơn hàng có mã vận đơn: %',
            p_ma_van_don;
    END IF;

    -- --------------------------------------------------------
    -- Kiểm tra nhân viên
    -- --------------------------------------------------------
    SELECT *
    INTO v_nhan_vien
    FROM nhan_vien
    WHERE id = p_nhan_vien_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Không tìm thấy nhân viên ID: %',
            p_nhan_vien_id;
    END IF;

    IF v_nhan_vien.trang_thai <> 'HOAT_DONG' THEN
        RAISE EXCEPTION 'Tài khoản nhân viên không hoạt động';
    END IF;

    IF v_nhan_vien.trang_thai_duyet <> 'DA_DUYET' THEN
        RAISE EXCEPTION 'Tài khoản nhân viên chưa được duyệt';
    END IF;

    -- --------------------------------------------------------
    -- Xác định kho quét
    -- Nếu không truyền kho thì lấy kho của nhân viên.
    -- --------------------------------------------------------
    IF p_kho_id IS NULL THEN
        p_kho_id := v_nhan_vien.kho_hang_id;
    END IF;

    IF p_kho_id IS NOT NULL THEN
        SELECT *
        INTO v_kho
        FROM kho_hang
        WHERE id = p_kho_id;

        IF NOT FOUND THEN
            RAISE EXCEPTION 'Không tìm thấy kho hàng ID: %',
                p_kho_id;
        END IF;

        v_ten_kho := v_kho.ten_kho;
    ELSE
        v_ten_kho := NULL;
    END IF;

    -- Nhân viên kho chỉ được thao tác tại kho của mình.
    IF v_nhan_vien.vai_tro IN ('QUAN_LY_KHO', 'NHAN_VIEN_KHO')
       AND v_nhan_vien.kho_hang_id IS NOT NULL
       AND p_kho_id IS DISTINCT FROM v_nhan_vien.kho_hang_id THEN
        RAISE EXCEPTION
            'Nhân viên kho chỉ được quét đơn tại kho được phân công';
    END IF;

    v_su_kien := UPPER(COALESCE(NULLIF(BTRIM(p_su_kien), ''), 'TU_DONG'));
    v_trang_thai_cu := v_don_hang.trang_thai;

    -- --------------------------------------------------------
    -- Tự xác định sự kiện theo vai trò và trạng thái
    -- --------------------------------------------------------
    IF v_su_kien = 'TU_DONG' THEN

        -- Nhân viên vận chuyển lấy hàng từ khách hàng.
        IF v_nhan_vien.vai_tro = 'VAN_CHUYEN'
           AND v_don_hang.trang_thai = 'CHO_LAY_HANG' THEN

            v_su_kien := 'LAY_HANG';

        -- Quản lý kho hoặc nhân viên kho tiếp nhận hàng.
        ELSIF v_nhan_vien.vai_tro IN ('QUAN_LY_KHO', 'NHAN_VIEN_KHO')
              AND v_don_hang.trang_thai IN (
                  'DA_LAY_HANG',
                  'DANG_VAN_CHUYEN',
                  'GIAO_CHO_SHIPPER',
                  'DANG_GIAO_HANG'
              ) THEN

            v_su_kien := 'DEN_KHO';

        -- Nhân viên vận chuyển hoặc shipper nhận hàng từ kho.
        ELSIF v_nhan_vien.vai_tro IN ('VAN_CHUYEN', 'SHIPPER')
              AND v_don_hang.trang_thai IN (
                  'DEN_KHO_TRUNG_CHUYEN',
                  'DEN_KHO_DICH'
              ) THEN

            v_su_kien := 'GIAO_CHO_SHIPPER';

        ELSE
            RAISE EXCEPTION
                'Không xác định được hành động tự động. Vai trò: %, trạng thái đơn: %',
                v_nhan_vien.vai_tro,
                v_don_hang.trang_thai;
        END IF;
    END IF;

    -- --------------------------------------------------------
    -- SỰ KIỆN 1: NHÂN VIÊN VẬN CHUYỂN LẤY HÀNG
    -- --------------------------------------------------------
    IF v_su_kien = 'LAY_HANG' THEN

        IF v_nhan_vien.vai_tro <> 'VAN_CHUYEN' THEN
            RAISE EXCEPTION
                'Chỉ nhân viên vận chuyển được xác nhận lấy hàng';
        END IF;

        IF v_don_hang.trang_thai <> 'CHO_LAY_HANG' THEN
            RAISE EXCEPTION
                'Đơn hàng phải ở trạng thái CHO_LAY_HANG. Trạng thái hiện tại: %',
                v_don_hang.trang_thai;
        END IF;

        v_trang_thai_moi := 'DA_LAY_HANG';
        v_hanh_dong := 'Đã lấy hàng từ khách hàng';

        UPDATE don_hang
        SET
            trang_thai = v_trang_thai_moi,
            nhan_vien_hien_tai_id = p_nhan_vien_id,
            kho_hien_tai_id = NULL,
            ngay_lay_hang = NOW()
        WHERE id = v_don_hang.id;

    -- --------------------------------------------------------
    -- SỰ KIỆN 2: QUẢN LÝ KHO TIẾP NHẬN HÀNG
    -- --------------------------------------------------------
    ELSIF v_su_kien = 'DEN_KHO' THEN

        IF v_nhan_vien.vai_tro NOT IN (
            'QUAN_LY_KHO',
            'NHAN_VIEN_KHO'
        ) THEN
            RAISE EXCEPTION
                'Chỉ quản lý kho hoặc nhân viên kho được tiếp nhận hàng';
        END IF;

        IF p_kho_id IS NULL THEN
            RAISE EXCEPTION
                'Phải truyền kho_id hoặc gán kho_hang_id cho nhân viên';
        END IF;

        IF v_don_hang.trang_thai IN (
            'DA_GIAO_HANG',
            'DA_HUY',
            'HOAN_HANG'
        ) THEN
            RAISE EXCEPTION
                'Không thể tiếp nhận đơn ở trạng thái: %',
                v_don_hang.trang_thai;
        END IF;

        IF v_don_hang.kho_hien_tai_id = p_kho_id
           AND v_don_hang.trang_thai IN (
               'DEN_KHO_TRUNG_CHUYEN',
               'DEN_KHO_DICH'
           ) THEN
            RAISE EXCEPTION
                'Đơn hàng đã được quét tại kho này';
        END IF;

        IF p_kho_id = v_don_hang.kho_dich_id THEN
            v_trang_thai_moi := 'DEN_KHO_DICH';
            v_hanh_dong := 'Đã đến kho đích ' || v_kho.ten_kho;
        ELSE
            v_trang_thai_moi := 'DEN_KHO_TRUNG_CHUYEN';
            v_hanh_dong := 'Đã đến kho ' || v_kho.ten_kho;
        END IF;

        UPDATE don_hang
        SET
            trang_thai = v_trang_thai_moi,
            kho_hien_tai_id = p_kho_id,
            nhan_vien_hien_tai_id = p_nhan_vien_id
        WHERE id = v_don_hang.id;

    -- --------------------------------------------------------
    -- SỰ KIỆN 3: GIAO ĐƠN CHO NHÂN VIÊN VẬN CHUYỂN/SHIPPER
    -- --------------------------------------------------------
    ELSIF v_su_kien = 'GIAO_CHO_SHIPPER' THEN

        IF v_nhan_vien.vai_tro NOT IN (
            'VAN_CHUYEN',
            'SHIPPER'
        ) THEN
            RAISE EXCEPTION
                'Chỉ nhân viên vận chuyển hoặc shipper được nhận hàng từ kho';
        END IF;

        IF v_don_hang.trang_thai NOT IN (
            'DEN_KHO_TRUNG_CHUYEN',
            'DEN_KHO_DICH'
        ) THEN
            RAISE EXCEPTION
                'Đơn hàng chưa được kho tiếp nhận. Trạng thái hiện tại: %',
                v_don_hang.trang_thai;
        END IF;

        v_trang_thai_moi := 'GIAO_CHO_SHIPPER';

        IF v_nhan_vien.vai_tro = 'SHIPPER' THEN
            v_hanh_dong :=
                'Kho đã giao hàng cho shipper ' || v_nhan_vien.ho_ten;
        ELSE
            v_hanh_dong :=
                'Kho đã giao hàng cho nhân viên vận chuyển '
                || v_nhan_vien.ho_ten;
        END IF;

        UPDATE don_hang
        SET
            trang_thai = v_trang_thai_moi,
            nhan_vien_hien_tai_id = p_nhan_vien_id
        WHERE id = v_don_hang.id;

    -- --------------------------------------------------------
    -- SỰ KIỆN 4: SHIPPER BẮT ĐẦU GIAO HÀNG
    -- --------------------------------------------------------
    ELSIF v_su_kien = 'BAT_DAU_GIAO_HANG' THEN

        IF v_nhan_vien.vai_tro NOT IN (
            'VAN_CHUYEN',
            'SHIPPER'
        ) THEN
            RAISE EXCEPTION
                'Chỉ nhân viên vận chuyển hoặc shipper được giao hàng';
        END IF;

        IF v_don_hang.trang_thai <> 'GIAO_CHO_SHIPPER' THEN
            RAISE EXCEPTION
                'Đơn hàng phải ở trạng thái GIAO_CHO_SHIPPER';
        END IF;

        v_trang_thai_moi := 'DANG_GIAO_HANG';
        v_hanh_dong :=
            'Nhân viên ' || v_nhan_vien.ho_ten || ' bắt đầu giao hàng';

        UPDATE don_hang
        SET
            trang_thai = v_trang_thai_moi,
            nhan_vien_hien_tai_id = p_nhan_vien_id
        WHERE id = v_don_hang.id;

    -- --------------------------------------------------------
    -- SỰ KIỆN 5: GIAO HÀNG THÀNH CÔNG
    -- Phải có ảnh minh chứng.
    -- --------------------------------------------------------
    ELSIF v_su_kien = 'GIAO_HANG_THANH_CONG' THEN

        IF v_nhan_vien.vai_tro NOT IN (
            'VAN_CHUYEN',
            'SHIPPER'
        ) THEN
            RAISE EXCEPTION
                'Chỉ nhân viên vận chuyển hoặc shipper được xác nhận giao hàng';
        END IF;

        IF v_don_hang.trang_thai NOT IN (
            'GIAO_CHO_SHIPPER',
            'DANG_GIAO_HANG'
        ) THEN
            RAISE EXCEPTION
                'Đơn hàng chưa được giao cho shipper';
        END IF;

        IF p_minh_chung IS NULL OR BTRIM(p_minh_chung) = '' THEN
            RAISE EXCEPTION
                'Phải có ảnh hoặc đường dẫn minh chứng giao hàng';
        END IF;

        v_trang_thai_moi := 'DA_GIAO_HANG';
        v_hanh_dong := 'Đã giao hàng thành công cho khách hàng';

        UPDATE don_hang
        SET
            trang_thai = v_trang_thai_moi,
            nhan_vien_hien_tai_id = p_nhan_vien_id,
            kho_hien_tai_id = NULL,
            ngay_giao_hang = NOW()
        WHERE id = v_don_hang.id;

    -- --------------------------------------------------------
    -- SỰ KIỆN 6: GIAO HÀNG THẤT BẠI
    -- --------------------------------------------------------
    ELSIF v_su_kien = 'GIAO_HANG_THAT_BAI' THEN

        IF v_nhan_vien.vai_tro NOT IN (
            'VAN_CHUYEN',
            'SHIPPER'
        ) THEN
            RAISE EXCEPTION
                'Chỉ nhân viên vận chuyển hoặc shipper được cập nhật giao thất bại';
        END IF;

        IF v_don_hang.trang_thai NOT IN (
            'GIAO_CHO_SHIPPER',
            'DANG_GIAO_HANG'
        ) THEN
            RAISE EXCEPTION
                'Đơn hàng chưa ở quá trình giao hàng';
        END IF;

        IF p_ghi_chu IS NULL OR BTRIM(p_ghi_chu) = '' THEN
            RAISE EXCEPTION
                'Phải nhập lý do giao hàng thất bại';
        END IF;

        v_trang_thai_moi := 'GIAO_HANG_THAT_BAI';
        v_hanh_dong := 'Giao hàng thất bại';

        UPDATE don_hang
        SET
            trang_thai = v_trang_thai_moi,
            nhan_vien_hien_tai_id = p_nhan_vien_id
        WHERE id = v_don_hang.id;

    ELSE
        RAISE EXCEPTION 'Sự kiện không hợp lệ: %', v_su_kien;
    END IF;

    -- --------------------------------------------------------
    -- GHI NHẬT KÝ SAU KHI CẬP NHẬT THÀNH CÔNG
    -- --------------------------------------------------------
    INSERT INTO nhat_ky_don_hang (
        nhan_vien_id,
        don_hang_id,
        khach_hang_id,
        hanh_dong,
        trang_thai_cu,
        trang_thai_moi,
        minh_chung,
        kho_id,
        ghi_chu,
        vi_do,
        kinh_do,
        thoi_gian
    )
    VALUES (
        p_nhan_vien_id,
        v_don_hang.id,
        v_don_hang.khach_hang_id,
        v_hanh_dong,
        v_trang_thai_cu,
        v_trang_thai_moi,
        p_minh_chung,
        p_kho_id,
        p_ghi_chu,
        p_vi_do,
        p_kinh_do,
        NOW()
    );

    RETURN QUERY
    SELECT
        TRUE,
        v_don_hang.id,
        v_don_hang.ma_van_don::TEXT,
        v_trang_thai_cu,
        v_trang_thai_moi,
        v_hanh_dong,
        v_ten_kho,
        NOW();
END;
$$;

-- Cho phép Supabase gọi hàm qua RPC.
GRANT EXECUTE ON FUNCTION quet_qr_don_hang(
    TEXT,
    BIGINT,
    BIGINT,
    TEXT,
    TEXT,
    TEXT,
    DOUBLE PRECISION,
    DOUBLE PRECISION
) TO authenticated;

-- ============================================================
-- 17. VIEW XEM HÀNH TRÌNH ĐƠN HÀNG
-- ============================================================

CREATE OR REPLACE VIEW lich_su_hanh_trinh_don_hang AS
SELECT
    nk.id AS nhat_ky_id,
    dh.id AS don_hang_id,
    dh.ma_van_don,
    dh.ma_qr,

    nk.trang_thai_cu,
    nk.trang_thai_moi,
    nk.hanh_dong,
    nk.minh_chung,
    nk.ghi_chu,

    nk.vi_do,
    nk.kinh_do,
    nk.thoi_gian,

    nv.id AS nhan_vien_id,
    nv.ho_ten AS ten_nhan_vien,
    nv.vai_tro,

    kh.id AS kho_id,
    kh.ma_kho,
    kh.ten_kho

FROM nhat_ky_don_hang nk

JOIN don_hang dh
    ON dh.id = nk.don_hang_id

LEFT JOIN nhan_vien nv
    ON nv.id = nk.nhan_vien_id

LEFT JOIN kho_hang kh
    ON kh.id = nk.kho_id;

-- ============================================================
-- 18. VIEW XEM THÔNG TIN ĐƠN HÀNG ĐẦY ĐỦ
-- ============================================================

CREATE OR REPLACE VIEW thong_tin_don_hang AS
SELECT
    dh.id,
    dh.ma_van_don,
    dh.ma_qr,
    dh.trang_thai,

    dh.nguoi_gui_ten,
    dh.nguoi_gui_sdt,
    dh.nguoi_gui_dia_chi,

    dh.nguoi_nhan_ten,
    dh.nguoi_nhan_sdt,
    dh.nguoi_nhan_dia_chi,

    dh.can_nang,
    dh.gia_tri_hang,
    dh.phi_van_chuyen,
    dh.cod,

    dh.khach_hang_id,
    kh.ho_ten AS ten_khach_hang,

    dh.kho_gui_id,
    kg.ma_kho AS ma_kho_gui,
    kg.ten_kho AS ten_kho_gui,

    dh.kho_dich_id,
    kd.ma_kho AS ma_kho_dich,
    kd.ten_kho AS ten_kho_dich,

    dh.kho_hien_tai_id,
    kht.ma_kho AS ma_kho_hien_tai,
    kht.ten_kho AS ten_kho_hien_tai,

    dh.nhan_vien_hien_tai_id,
    nv.ho_ten AS nhan_vien_hien_tai,
    nv.vai_tro AS vai_tro_nhan_vien,

    dh.ngay_tao,
    dh.ngay_lay_hang,
    dh.ngay_giao_hang,
    dh.ngay_cap_nhat,
    dh.ghi_chu

FROM don_hang dh

JOIN khach_hang kh
    ON kh.id = dh.khach_hang_id

JOIN kho_hang kg
    ON kg.id = dh.kho_gui_id

JOIN kho_hang kd
    ON kd.id = dh.kho_dich_id

LEFT JOIN kho_hang kht
    ON kht.id = dh.kho_hien_tai_id

LEFT JOIN nhan_vien nv
    ON nv.id = dh.nhan_vien_hien_tai_id;

-- ============================================================
-- 19. MỞ RỘNG 2025: HÀNH CHÍNH MỚI VÀ PHÂN CẤP KHO
-- ============================================================
CREATE EXTENSION IF NOT EXISTS unaccent;

ALTER TABLE khach_hang ADD COLUMN IF NOT EXISTS auth_user_id UUID;
ALTER TABLE khach_hang ADD CONSTRAINT fk_khach_hang_auth_user
    FOREIGN KEY (auth_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
CREATE UNIQUE INDEX uq_khach_hang_auth_user ON khach_hang(auth_user_id)
    WHERE auth_user_id IS NOT NULL;

ALTER TABLE kho_hang
    ADD COLUMN IF NOT EXISTS cap_kho SMALLINT NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS kho_trung_tam_id BIGINT REFERENCES kho_hang(id);
ALTER TABLE kho_hang ADD CONSTRAINT chk_kho_hang_cap_kho CHECK (
    (cap_kho = 1 AND kho_trung_tam_id IS NULL) OR
    (cap_kho = 2 AND kho_trung_tam_id IS NOT NULL)
);

ALTER TABLE don_hang
    ADD COLUMN IF NOT EXISTS khoang_cach_km NUMERIC(12,2),
    ADD COLUMN IF NOT EXISTS phuong_tien VARCHAR(30),
    ADD COLUMN IF NOT EXISTS kho_trung_tam_gui_id BIGINT REFERENCES kho_hang(id),
    ADD COLUMN IF NOT EXISTS kho_trung_tam_dich_id BIGINT REFERENCES kho_hang(id);
ALTER TABLE don_hang ALTER COLUMN kho_gui_id DROP NOT NULL;
ALTER TABLE don_hang ALTER COLUMN kho_dich_id DROP NOT NULL;
ALTER TABLE don_hang DROP CONSTRAINT chk_don_hang_kho;
ALTER TABLE don_hang ADD CONSTRAINT chk_don_hang_kho CHECK (
    (phuong_tien = 'XE_MAY' AND khoang_cach_km <= 50
        AND kho_gui_id IS NULL AND kho_dich_id IS NULL)
    OR (phuong_tien = 'XE_TAI' AND khoang_cach_km > 50
        AND kho_gui_id IS NOT NULL AND kho_dich_id IS NOT NULL
        AND kho_trung_tam_gui_id IS NOT NULL AND kho_trung_tam_dich_id IS NOT NULL)
    OR (phuong_tien IS NULL AND khoang_cach_km IS NULL)
);

CREATE OR REPLACE FUNCTION kiem_tra_cay_kho() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
DECLARE v_cap SMALLINT; v_tinh TEXT; v_tinh_trung_tam TEXT;
BEGIN
  IF NEW.cap_kho = 1 THEN NEW.kho_trung_tam_id := NULL; RETURN NEW; END IF;
  SELECT kh.cap_kho, kv.tinh_thanh INTO v_cap, v_tinh_trung_tam
  FROM kho_hang kh JOIN khu_vuc kv ON kv.id=kh.khu_vuc_id WHERE kh.id=NEW.kho_trung_tam_id;
  SELECT tinh_thanh INTO v_tinh FROM khu_vuc WHERE id=NEW.khu_vuc_id;
  IF NEW.cap_kho <> 2 OR v_cap <> 1 OR v_tinh IS DISTINCT FROM v_tinh_trung_tam THEN
    RAISE EXCEPTION 'Kho cấp 2 phải thuộc kho cấp 1 cùng tỉnh/thành';
  END IF;
  RETURN NEW;
END; $$;
CREATE TRIGGER trg_kiem_tra_cay_kho BEFORE INSERT OR UPDATE OF cap_kho,kho_trung_tam_id,khu_vuc_id
ON kho_hang FOR EACH ROW EXECUTE FUNCTION kiem_tra_cay_kho();

-- Dữ liệu kho mẫu theo 34 tỉnh/thành mới, không dùng quận/huyện.
INSERT INTO khu_vuc(ten_khu_vuc,tinh_thanh,quan_huyen,phuong_xa) VALUES
 ('Trung tâm TP.HCM','Thành phố Hồ Chí Minh',NULL,'Phường Sài Gòn'),
 ('Phía Đông TP.HCM','Thành phố Hồ Chí Minh',NULL,'Phường An Phú'),
 ('Trung tâm Hà Nội','Thành phố Hà Nội',NULL,'Phường Hoàn Kiếm'),
 ('Phía Tây Hà Nội','Thành phố Hà Nội',NULL,'Phường Từ Liêm'),
 ('Trung tâm Đà Nẵng','Thành phố Đà Nẵng',NULL,'Phường Hải Châu'),
 ('Trung tâm Cần Thơ','Thành phố Cần Thơ',NULL,'Phường Ninh Kiều');

-- Thêm kho cấp 1 trước; sau đó gán kho cấp 2 về kho trung tâm cùng thành phố.
INSERT INTO kho_hang(ma_kho,ten_kho,dia_chi,khu_vuc_id,so_dien_thoai,cap_kho)
SELECT v.ma,v.ten,v.dc,kv.id,v.sdt,1 FROM (VALUES
 ('HCM-Q1','Kho trung tâm Sài Gòn','12 Nguyễn Huệ, Phường Sài Gòn, Thành phố Hồ Chí Minh','Thành phố Hồ Chí Minh','Phường Sài Gòn','02838220001'),
 ('HCM-AP','Kho An Phú','86 Mai Chí Thọ, Phường An Phú, Thành phố Hồ Chí Minh','Thành phố Hồ Chí Minh','Phường An Phú','02837240002'),
 ('HN-HK','Kho trung tâm Hoàn Kiếm','25 Tràng Tiền, Phường Hoàn Kiếm, Thành phố Hà Nội','Thành phố Hà Nội','Phường Hoàn Kiếm','02439260003'),
 ('HN-TL','Kho Từ Liêm','18 Hàm Nghi, Phường Từ Liêm, Thành phố Hà Nội','Thành phố Hà Nội','Phường Từ Liêm','02437680004')
)v(ma,ten,dc,tinh,phuong,sdt) JOIN khu_vuc kv ON kv.tinh_thanh=v.tinh AND kv.phuong_xa=v.phuong;
UPDATE kho_hang vt SET cap_kho=2,kho_trung_tam_id=tt.id FROM kho_hang tt
WHERE (vt.ma_kho,tt.ma_kho) IN (('HCM-AP','HCM-Q1'),('HN-TL','HN-HK'));

-- Chỉ cho phép chặng liên tỉnh giữa hai kho cấp 1.
CREATE OR REPLACE FUNCTION kiem_tra_chang_lien_tinh() RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE cap_di SMALLINT; cap_den SMALLINT; tinh_di TEXT; tinh_den TEXT;
BEGIN
 SELECT kh.cap_kho,kv.tinh_thanh INTO cap_di,tinh_di FROM kho_hang kh JOIN khu_vuc kv ON kv.id=kh.khu_vuc_id WHERE kh.id=NEW.kho_di_id;
 SELECT kh.cap_kho,kv.tinh_thanh INTO cap_den,tinh_den FROM kho_hang kh JOIN khu_vuc kv ON kv.id=kh.khu_vuc_id WHERE kh.id=NEW.kho_den_id;
 IF tinh_di IS DISTINCT FROM tinh_den AND (cap_di<>1 OR cap_den<>1) THEN RAISE EXCEPTION 'Chặng liên tỉnh chỉ được đi giữa kho cấp 1'; END IF;
 RETURN NEW;
END; $$;
CREATE TRIGGER trg_kiem_tra_chang_lien_tinh BEFORE INSERT OR UPDATE OF kho_di_id,kho_den_id
ON chuyen_xe_chang FOR EACH ROW EXECUTE FUNCTION kiem_tra_chang_lien_tinh();

-- Truy vấn kiểm tra tuyến: cấp 2 -> trung tâm -> trung tâm đích -> cấp 2.
SELECT dh.ma_van_don,kg.ma_kho kho_gui,tg.ma_kho trung_tam_gui,td.ma_kho trung_tam_dich,kd.ma_kho kho_dich
FROM don_hang dh LEFT JOIN kho_hang kg ON kg.id=dh.kho_gui_id
LEFT JOIN kho_hang tg ON tg.id=dh.kho_trung_tam_gui_id LEFT JOIN kho_hang td ON td.id=dh.kho_trung_tam_dich_id
LEFT JOIN kho_hang kd ON kd.id=dh.kho_dich_id;
