-- Chạy file này trong Supabase Dashboard > SQL Editor.
-- File thay thế trigger chỉ tạo khách hàng bằng trigger hỗ trợ cả khách hàng và nhân viên.

-- `database_full_setup.sql` cũ không có bảng nhân viên. Tạo bảng nếu dự án
-- đang dùng schema này; nếu đã có thì câu lệnh không làm thay đổi dữ liệu.
CREATE TABLE IF NOT EXISTS public.nhan_vien (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_user_id UUID UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  kho_hang_id BIGINT REFERENCES public.kho_hang(id) ON DELETE SET NULL,
  ho_ten TEXT NOT NULL,
  so_dien_thoai VARCHAR(20) NOT NULL,
  email TEXT UNIQUE,
  mat_khau TEXT NOT NULL DEFAULT 'SUPABASE_AUTH',
  dia_chi TEXT,
  so_cccd VARCHAR(20) UNIQUE,
  vai_tro VARCHAR(30) NOT NULL DEFAULT 'SHIPPER',
  trang_thai_duyet VARCHAR(30) NOT NULL DEFAULT 'CHO_DUYET',
  trang_thai VARCHAR(30) NOT NULL DEFAULT 'HOAT_DONG',
  ngay_tao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_nhan_vien_vai_tro CHECK (
    vai_tro IN ('ADMIN', 'QUAN_LY_KHO', 'NHAN_VIEN_KHO', 'VAN_CHUYEN', 'SHIPPER')
  ),
  CONSTRAINT chk_nhan_vien_duyet CHECK (
    trang_thai_duyet IN ('CHO_DUYET', 'DA_DUYET', 'TU_CHOI')
  )
);

ALTER TABLE public.khach_hang ADD COLUMN IF NOT EXISTS auth_user_id UUID;
ALTER TABLE public.nhan_vien ADD COLUMN IF NOT EXISTS auth_user_id UUID;

CREATE UNIQUE INDEX IF NOT EXISTS uq_khach_hang_auth_user
  ON public.khach_hang(auth_user_id) WHERE auth_user_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_nhan_vien_auth_user
  ON public.nhan_vien(auth_user_id) WHERE auth_user_id IS NOT NULL;

CREATE OR REPLACE FUNCTION public.tao_ho_so_nguoi_dung()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_loai TEXT := UPPER(COALESCE(NEW.raw_user_meta_data->>'vai_tro', 'KHACH_HANG'));
  v_vai_tro TEXT;
BEGIN
  IF v_loai = 'NHAN_VIEN' THEN
    v_vai_tro := UPPER(COALESCE(NEW.raw_user_meta_data->>'vai_tro_nhan_vien', 'SHIPPER'));
    IF v_vai_tro NOT IN ('NHAN_VIEN_KHO', 'VAN_CHUYEN', 'SHIPPER') THEN
      RAISE EXCEPTION 'Vai trò nhân viên không hợp lệ';
    END IF;

    INSERT INTO public.nhan_vien (
      auth_user_id, ho_ten, so_dien_thoai, email, mat_khau,
      vai_tro, trang_thai_duyet, trang_thai
    ) VALUES (
      NEW.id,
      COALESCE(NULLIF(BTRIM(NEW.raw_user_meta_data->>'ho_ten'), ''), 'Nhân viên'),
      COALESCE(NULLIF(BTRIM(NEW.raw_user_meta_data->>'so_dien_thoai'), ''), NEW.id::TEXT),
      NEW.email, 'SUPABASE_AUTH', v_vai_tro, 'CHO_DUYET', 'HOAT_DONG'
    );
  ELSE
    INSERT INTO public.khach_hang (
      auth_user_id, ho_ten, so_dien_thoai, email, mat_khau, dia_chi, trang_thai
    ) VALUES (
      NEW.id,
      COALESCE(NULLIF(BTRIM(NEW.raw_user_meta_data->>'ho_ten'), ''), 'Khách hàng'),
      COALESCE(NULLIF(BTRIM(NEW.raw_user_meta_data->>'so_dien_thoai'), ''), NEW.id::TEXT),
      NEW.email, 'SUPABASE_AUTH',
      NULLIF(BTRIM(NEW.raw_user_meta_data->>'dia_chi'), ''), 'HOAT_DONG'
    );
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_tao_ho_so_khach_hang ON auth.users;
DROP TRIGGER IF EXISTS trg_tao_ho_so_nguoi_dung ON auth.users;
CREATE TRIGGER trg_tao_ho_so_nguoi_dung
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.tao_ho_so_nguoi_dung();

ALTER TABLE public.nhan_vien ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Nhan vien xem ho so cua minh" ON public.nhan_vien;
CREATE POLICY "Nhan vien xem ho so cua minh" ON public.nhan_vien
  FOR SELECT TO authenticated USING (auth.uid() = auth_user_id);
GRANT SELECT ON public.nhan_vien TO authenticated;

-- Sau khi kiểm tra hồ sơ, quản trị viên duyệt tài khoản bằng câu lệnh sau:
-- UPDATE public.nhan_vien SET trang_thai_duyet = 'DA_DUYET'
-- WHERE email = 'email-nhan-vien@example.com';
