-- Nhân viên chặng đầu/chặng cuối theo địa bàn phường/xã và kho cấp 2.
-- Chạy sau warehouse_level2_creation_setup.sql.

-- Tự chứa hàm chuẩn hóa tiếng Việt, không phụ thuộc extension unaccent hay
-- các file cài đặt đã chạy trước đó.
CREATE OR REPLACE FUNCTION public.bo_dau_lower(p_text TEXT)
RETURNS TEXT LANGUAGE sql IMMUTABLE PARALLEL SAFE AS $$
  SELECT regexp_replace(
    regexp_replace(
      regexp_replace(
        regexp_replace(
          regexp_replace(
            regexp_replace(
              regexp_replace(lower(COALESCE(p_text,'')),
                '[áàảãạăắằẳẵặâấầẩẫậ]', 'a', 'g'),
              '[éèẻẽẹêếềểễệ]', 'e', 'g'),
            '[íìỉĩị]', 'i', 'g'),
          '[óòỏõọôốồổỗộơớờởỡợ]', 'o', 'g'),
        '[úùủũụưứừửữự]', 'u', 'g'),
      '[ýỳỷỹỵ]', 'y', 'g'),
    'đ', 'd', 'g')
$$;

ALTER TABLE public.nhan_vien
  ADD COLUMN IF NOT EXISTS khu_vuc_id BIGINT REFERENCES public.khu_vuc(id);

CREATE TABLE IF NOT EXISTS public.dia_ban_giao_nhan (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  khu_vuc_id BIGINT NOT NULL REFERENCES public.khu_vuc(id) ON DELETE CASCADE,
  ten_dia_ban VARCHAR(160) NOT NULL,
  loai_dia_ban VARCHAR(20) NOT NULL CHECK (loai_dia_ban IN ('KHU_PHO','AP_THON')),
  trang_thai VARCHAR(20) NOT NULL DEFAULT 'HOAT_DONG'
    CHECK (trang_thai IN ('HOAT_DONG','NGUNG_HOAT_DONG')),
  ngay_tao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(khu_vuc_id,ten_dia_ban)
);

-- Danh mục mẫu đã xác minh cho Phường An Phú, TP.HCM: 07 khu phố.
-- Giao diện chỉ cho chọn từ danh mục này, không cho nhân viên tự nhập.
INSERT INTO public.dia_ban_giao_nhan(khu_vuc_id,ten_dia_ban,loai_dia_ban)
SELECT kv.id,'Khu phố ' || gs.n,'KHU_PHO'
FROM public.khu_vuc kv
CROSS JOIN generate_series(1,7) AS gs(n)
WHERE public.bo_dau_lower(kv.phuong_xa)='phuong an phu'
  AND public.bo_dau_lower(kv.tinh_thanh) IN (
    'thanh pho ho chi minh','tp ho chi minh','ho chi minh'
  )
ON CONFLICT (khu_vuc_id,ten_dia_ban)
DO UPDATE SET trang_thai='HOAT_DONG';

ALTER TABLE public.nhan_vien
  ADD COLUMN IF NOT EXISTS dia_ban_giao_nhan_id BIGINT
    REFERENCES public.dia_ban_giao_nhan(id);

ALTER TABLE public.nhan_vien DROP CONSTRAINT IF EXISTS chk_nhan_vien_vai_tro;
ALTER TABLE public.nhan_vien ADD CONSTRAINT chk_nhan_vien_vai_tro CHECK (
  vai_tro IN ('ADMIN','QUAN_LY_KHO','NHAN_VIEN_KHO','VAN_CHUYEN','SHIPPER',
              'NHAN_VIEN_LAY_HANG','NHAN_VIEN_GIAO_HANG')
);

ALTER TABLE public.don_hang
  ADD COLUMN IF NOT EXISTS khu_vuc_lay_hang_id BIGINT REFERENCES public.khu_vuc(id),
  ADD COLUMN IF NOT EXISTS khu_vuc_giao_hang_id BIGINT REFERENCES public.khu_vuc(id),
  ADD COLUMN IF NOT EXISTS dia_ban_lay_hang_id BIGINT REFERENCES public.dia_ban_giao_nhan(id),
  ADD COLUMN IF NOT EXISTS dia_ban_giao_hang_id BIGINT REFERENCES public.dia_ban_giao_nhan(id),
  ADD COLUMN IF NOT EXISTS nhan_vien_lay_hang_id BIGINT REFERENCES public.nhan_vien(id),
  ADD COLUMN IF NOT EXISTS nhan_vien_giao_hang_id BIGINT REFERENCES public.nhan_vien(id);

CREATE INDEX IF NOT EXISTS idx_nhan_vien_chang_cuoi
  ON public.nhan_vien(vai_tro,kho_hang_id,khu_vuc_id,dia_ban_giao_nhan_id,trang_thai_duyet,trang_thai);
CREATE INDEX IF NOT EXISTS idx_don_hang_nv_lay
  ON public.don_hang(nhan_vien_lay_hang_id,trang_thai);
CREATE INDEX IF NOT EXISTS idx_don_hang_nv_giao
  ON public.don_hang(nhan_vien_giao_hang_id,trang_thai);

CREATE OR REPLACE FUNCTION public.kiem_tra_dia_ban_nhan_vien_chang_cuoi()
RETURNS TRIGGER LANGUAGE plpgsql SET search_path=public AS $$
DECLARE
  v_kho_cap SMALLINT;
  v_kho_tinh_thanh TEXT;
  v_nhan_vien_tinh_thanh TEXT;
  v_dia_ban_khu_vuc_id BIGINT;
BEGIN
  IF NEW.vai_tro NOT IN ('NHAN_VIEN_LAY_HANG','NHAN_VIEN_GIAO_HANG') THEN
    RETURN NEW;
  END IF;
  IF NEW.kho_hang_id IS NULL OR NEW.khu_vuc_id IS NULL OR NEW.dia_ban_giao_nhan_id IS NULL THEN
    RAISE EXCEPTION 'Nhân viên lấy/giao hàng phải có kho cấp 2 và khu phố/ấp/thôn phụ trách';
  END IF;
  SELECT kh.cap_kho, kv.tinh_thanh
  INTO v_kho_cap, v_kho_tinh_thanh
  FROM public.kho_hang kh
  JOIN public.khu_vuc kv ON kv.id=kh.khu_vuc_id
  WHERE kh.id=NEW.kho_hang_id;
  IF v_kho_cap IS DISTINCT FROM 2 THEN
    RAISE EXCEPTION 'Nhân viên lấy/giao hàng chỉ được gán vào kho cấp 2';
  END IF;
  SELECT kv.tinh_thanh INTO v_nhan_vien_tinh_thanh
  FROM public.khu_vuc kv WHERE kv.id=NEW.khu_vuc_id;
  IF public.bo_dau_lower(v_kho_tinh_thanh)
     IS DISTINCT FROM public.bo_dau_lower(v_nhan_vien_tinh_thanh) THEN
    RAISE EXCEPTION 'Phường/xã phụ trách phải cùng tỉnh/thành với kho cấp 2';
  END IF;
  SELECT db.khu_vuc_id INTO v_dia_ban_khu_vuc_id
  FROM public.dia_ban_giao_nhan db WHERE db.id=NEW.dia_ban_giao_nhan_id;
  IF v_dia_ban_khu_vuc_id IS DISTINCT FROM NEW.khu_vuc_id THEN
    RAISE EXCEPTION 'Khu phố/ấp/thôn không thuộc phường/xã đã chọn';
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_kiem_tra_dia_ban_nhan_vien_chang_cuoi ON public.nhan_vien;
CREATE TRIGGER trg_kiem_tra_dia_ban_nhan_vien_chang_cuoi
BEFORE INSERT OR UPDATE OF vai_tro,kho_hang_id,khu_vuc_id,dia_ban_giao_nhan_id ON public.nhan_vien
FOR EACH ROW EXECUTE FUNCTION public.kiem_tra_dia_ban_nhan_vien_chang_cuoi();

CREATE OR REPLACE FUNCTION public.tim_khu_vuc_theo_dia_chi(p_dia_chi TEXT)
RETURNS BIGINT LANGUAGE sql STABLE SET search_path=public AS $$
  SELECT kv.id FROM public.khu_vuc kv
  WHERE public.bo_dau_lower(p_dia_chi) LIKE '%' || public.bo_dau_lower(kv.phuong_xa) || '%'
    AND public.bo_dau_lower(p_dia_chi) LIKE '%' || public.bo_dau_lower(kv.tinh_thanh) || '%'
  ORDER BY LENGTH(kv.phuong_xa) DESC, kv.id LIMIT 1
$$;

CREATE OR REPLACE FUNCTION public.tim_dia_ban_giao_nhan(
  p_dia_chi TEXT, p_khu_vuc_id BIGINT
) RETURNS BIGINT LANGUAGE sql STABLE SET search_path=public AS $$
  SELECT db.id FROM public.dia_ban_giao_nhan db
  WHERE db.khu_vuc_id=p_khu_vuc_id AND db.trang_thai='HOAT_DONG'
    AND public.bo_dau_lower(p_dia_chi)
        LIKE '%' || public.bo_dau_lower(db.ten_dia_ban) || '%'
  ORDER BY LENGTH(db.ten_dia_ban) DESC, db.id LIMIT 1
$$;

CREATE OR REPLACE FUNCTION public.phan_cong_nhan_vien_chang_cuoi()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN
  IF NEW.khu_vuc_lay_hang_id IS NULL THEN
    NEW.khu_vuc_lay_hang_id := public.tim_khu_vuc_theo_dia_chi(NEW.nguoi_gui_dia_chi);
  END IF;
  IF NEW.khu_vuc_giao_hang_id IS NULL THEN
    NEW.khu_vuc_giao_hang_id := public.tim_khu_vuc_theo_dia_chi(NEW.nguoi_nhan_dia_chi);
  END IF;
  NEW.dia_ban_lay_hang_id := public.tim_dia_ban_giao_nhan(
    NEW.nguoi_gui_dia_chi, NEW.khu_vuc_lay_hang_id);
  NEW.dia_ban_giao_hang_id := public.tim_dia_ban_giao_nhan(
    NEW.nguoi_nhan_dia_chi, NEW.khu_vuc_giao_hang_id);

  -- Không tự gán nhân viên. Nhân viên lấy hàng tự chọn đơn; nhân viên giao
  -- hàng quét mã kiện ở kho. Hai thao tác nhận được khóa nguyên tử bằng RPC.
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_phan_cong_nhan_vien_chang_cuoi ON public.don_hang;
CREATE TRIGGER trg_phan_cong_nhan_vien_chang_cuoi
BEFORE INSERT OR UPDATE OF trang_thai,kho_gui_id,kho_dich_id,nguoi_gui_dia_chi,nguoi_nhan_dia_chi,nhan_vien_lay_hang_id,nhan_vien_giao_hang_id ON public.don_hang
FOR EACH ROW EXECUTE FUNCTION public.phan_cong_nhan_vien_chang_cuoi();

CREATE OR REPLACE FUNCTION public.tai_phan_cong_khi_nhan_vien_thay_doi()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN
  IF TG_OP='UPDATE' AND OLD.vai_tro='NHAN_VIEN_LAY_HANG'
     AND (NEW.trang_thai<>'HOAT_DONG' OR NEW.trang_thai_duyet<>'DA_DUYET'
          OR NEW.kho_hang_id IS DISTINCT FROM OLD.kho_hang_id
          OR NEW.khu_vuc_id IS DISTINCT FROM OLD.khu_vuc_id) THEN
    UPDATE public.don_hang SET nhan_vien_lay_hang_id=NULL
    WHERE nhan_vien_lay_hang_id=OLD.id AND trang_thai='CHO_LAY_HANG';
  END IF;
  IF TG_OP='UPDATE' AND OLD.vai_tro='NHAN_VIEN_GIAO_HANG'
     AND (NEW.trang_thai<>'HOAT_DONG' OR NEW.trang_thai_duyet<>'DA_DUYET'
          OR NEW.kho_hang_id IS DISTINCT FROM OLD.kho_hang_id
          OR NEW.khu_vuc_id IS DISTINCT FROM OLD.khu_vuc_id) THEN
    UPDATE public.don_hang SET nhan_vien_giao_hang_id=NULL
    WHERE nhan_vien_giao_hang_id=OLD.id
      AND trang_thai IN ('DEN_KHO_DICH','GIAO_CHO_SHIPPER');
  END IF;
  IF NEW.trang_thai='HOAT_DONG' AND NEW.trang_thai_duyet='DA_DUYET' THEN
    IF NEW.vai_tro='NHAN_VIEN_LAY_HANG' THEN
      UPDATE public.don_hang SET nhan_vien_lay_hang_id=NULL
      WHERE kho_gui_id=NEW.kho_hang_id AND khu_vuc_lay_hang_id=NEW.khu_vuc_id
        AND nhan_vien_lay_hang_id IS NULL AND trang_thai='CHO_LAY_HANG';
    ELSIF NEW.vai_tro='NHAN_VIEN_GIAO_HANG' THEN
      UPDATE public.don_hang SET nhan_vien_giao_hang_id=NULL
      WHERE kho_dich_id=NEW.kho_hang_id AND khu_vuc_giao_hang_id=NEW.khu_vuc_id
        AND nhan_vien_giao_hang_id IS NULL
        AND trang_thai IN ('DEN_KHO_DICH','GIAO_CHO_SHIPPER');
    END IF;
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_tai_phan_cong_khi_nhan_vien_thay_doi ON public.nhan_vien;
CREATE TRIGGER trg_tai_phan_cong_khi_nhan_vien_thay_doi
AFTER INSERT OR UPDATE OF vai_tro,kho_hang_id,khu_vuc_id,trang_thai_duyet,trang_thai
ON public.nhan_vien FOR EACH ROW EXECUTE FUNCTION public.tai_phan_cong_khi_nhan_vien_thay_doi();

-- Bản mới không tự tái phân công theo tải công việc.
DROP TRIGGER IF EXISTS trg_tai_phan_cong_khi_nhan_vien_thay_doi ON public.nhan_vien;

-- Phân công cả các đơn đang chờ tồn tại trước khi cài bản nâng cấp.
UPDATE public.don_hang SET nhan_vien_lay_hang_id=NULL
WHERE trang_thai='CHO_LAY_HANG';
UPDATE public.don_hang SET nhan_vien_giao_hang_id=NULL
WHERE trang_thai IN ('DEN_KHO_DICH','GIAO_CHO_SHIPPER');

CREATE OR REPLACE FUNCTION public.nhan_vien_chang_cuoi_cong_viec_v2()
RETURNS TABLE(id BIGINT,ma_van_don VARCHAR,ma_qr UUID,loai_cong_viec TEXT,ten_khach TEXT,
  so_dien_thoai TEXT,dia_chi TEXT,ten_kho TEXT,trang_thai VARCHAR,da_nhan BOOLEAN,ngay_cap_nhat TIMESTAMPTZ)
LANGUAGE plpgsql SECURITY DEFINER STABLE SET search_path=public AS $$
DECLARE v_nv public.nhan_vien%ROWTYPE;
BEGIN
  SELECT nv.* INTO v_nv FROM public.nhan_vien nv WHERE nv.auth_user_id=auth.uid()
    AND nv.vai_tro IN ('NHAN_VIEN_LAY_HANG','NHAN_VIEN_GIAO_HANG')
    AND nv.trang_thai_duyet='DA_DUYET' AND nv.trang_thai='HOAT_DONG';
  IF NOT FOUND THEN RAISE EXCEPTION 'Tài khoản chưa được duyệt hoặc không đúng vai trò'; END IF;
  RETURN QUERY
  SELECT dh.id,dh.ma_van_don::VARCHAR,dh.ma_qr,
    CASE WHEN v_nv.vai_tro='NHAN_VIEN_LAY_HANG' THEN 'LAY_HANG' ELSE 'GIAO_HANG' END,
    CASE WHEN v_nv.vai_tro='NHAN_VIEN_LAY_HANG' THEN dh.nguoi_gui_ten ELSE dh.nguoi_nhan_ten END,
    CASE WHEN v_nv.vai_tro='NHAN_VIEN_LAY_HANG' THEN dh.nguoi_gui_sdt ELSE dh.nguoi_nhan_sdt END,
    CASE WHEN v_nv.vai_tro='NHAN_VIEN_LAY_HANG' THEN dh.nguoi_gui_dia_chi ELSE dh.nguoi_nhan_dia_chi END,
    kh.ten_kho::TEXT,dh.trang_thai::VARCHAR,
    CASE WHEN v_nv.vai_tro='NHAN_VIEN_LAY_HANG' THEN dh.nhan_vien_lay_hang_id=v_nv.id
         ELSE dh.nhan_vien_giao_hang_id=v_nv.id END,dh.ngay_cap_nhat
  FROM public.don_hang dh
  JOIN public.kho_hang kh ON kh.id=CASE WHEN v_nv.vai_tro='NHAN_VIEN_LAY_HANG' THEN dh.kho_gui_id ELSE dh.kho_dich_id END
  WHERE (v_nv.vai_tro='NHAN_VIEN_LAY_HANG' AND dh.kho_gui_id=v_nv.kho_hang_id
         AND dh.khu_vuc_lay_hang_id=v_nv.khu_vuc_id
         AND dh.dia_ban_lay_hang_id=v_nv.dia_ban_giao_nhan_id AND dh.trang_thai='CHO_LAY_HANG'
         AND (dh.nhan_vien_lay_hang_id IS NULL OR dh.nhan_vien_lay_hang_id=v_nv.id))
     OR (v_nv.vai_tro='NHAN_VIEN_GIAO_HANG' AND dh.nhan_vien_giao_hang_id=v_nv.id
         AND dh.trang_thai IN ('DEN_KHO_DICH','GIAO_CHO_SHIPPER','DANG_GIAO_HANG'))
  ORDER BY dh.ngay_cap_nhat;
END;
$$;

CREATE OR REPLACE FUNCTION public.nhan_vien_lay_hang_nhan_don(p_don_hang_id BIGINT)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_nv public.nhan_vien%ROWTYPE; v_id BIGINT;
BEGIN
  SELECT nv.* INTO v_nv FROM public.nhan_vien nv WHERE nv.auth_user_id=auth.uid()
    AND nv.vai_tro='NHAN_VIEN_LAY_HANG' AND nv.trang_thai_duyet='DA_DUYET' AND nv.trang_thai='HOAT_DONG';
  IF NOT FOUND THEN RAISE EXCEPTION 'Tài khoản không phải nhân viên lấy hàng đang hoạt động'; END IF;
  UPDATE public.don_hang dh SET nhan_vien_lay_hang_id=v_nv.id,nhan_vien_hien_tai_id=v_nv.id,ngay_cap_nhat=NOW()
  WHERE dh.id=p_don_hang_id AND dh.trang_thai='CHO_LAY_HANG'
    AND dh.kho_gui_id=v_nv.kho_hang_id AND dh.khu_vuc_lay_hang_id=v_nv.khu_vuc_id
    AND dh.dia_ban_lay_hang_id=v_nv.dia_ban_giao_nhan_id
    AND dh.nhan_vien_lay_hang_id IS NULL RETURNING dh.id INTO v_id;
  IF v_id IS NULL THEN
    IF EXISTS(SELECT 1 FROM public.don_hang dh WHERE dh.id=p_don_hang_id AND dh.nhan_vien_lay_hang_id=v_nv.id) THEN RETURN; END IF;
    RAISE EXCEPTION 'Đơn đã được nhân viên khác nhận hoặc không thuộc khu vực của bạn';
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.nhan_vien_giao_hang_quet_kien(p_ma TEXT)
RETURNS BIGINT LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_nv public.nhan_vien%ROWTYPE; v_don public.don_hang%ROWTYPE;
BEGIN
  SELECT nv.* INTO v_nv FROM public.nhan_vien nv WHERE nv.auth_user_id=auth.uid()
    AND nv.vai_tro='NHAN_VIEN_GIAO_HANG' AND nv.trang_thai_duyet='DA_DUYET' AND nv.trang_thai='HOAT_DONG';
  IF NOT FOUND THEN RAISE EXCEPTION 'Tài khoản không phải nhân viên giao hàng đang hoạt động'; END IF;
  SELECT dh.* INTO v_don FROM public.don_hang dh
  WHERE dh.ma_qr::TEXT=BTRIM(p_ma) OR UPPER(dh.ma_van_don)=UPPER(BTRIM(p_ma)) FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Không tìm thấy kiện hàng'; END IF;
  IF v_don.kho_dich_id<>v_nv.kho_hang_id
     OR v_don.khu_vuc_giao_hang_id<>v_nv.khu_vuc_id
     OR v_don.dia_ban_giao_hang_id<>v_nv.dia_ban_giao_nhan_id THEN
    RAISE EXCEPTION 'Kiện hàng không thuộc khu phố/ấp/thôn bạn phụ trách';
  END IF;
  IF v_don.trang_thai NOT IN ('DEN_KHO_DICH','GIAO_CHO_SHIPPER') THEN
    RAISE EXCEPTION 'Kiện hàng chưa sẵn sàng để giao';
  END IF;
  IF v_don.nhan_vien_giao_hang_id IS NOT NULL AND v_don.nhan_vien_giao_hang_id<>v_nv.id THEN
    RAISE EXCEPTION 'Kiện hàng đã được nhân viên khác quét nhận';
  END IF;
  UPDATE public.don_hang SET nhan_vien_giao_hang_id=v_nv.id,nhan_vien_hien_tai_id=v_nv.id,
    trang_thai='GIAO_CHO_SHIPPER',ngay_cap_nhat=NOW() WHERE id=v_don.id;
  RETURN v_don.id;
END;
$$;

CREATE OR REPLACE FUNCTION public.nhan_vien_chang_cuoi_xac_nhan(p_don_hang_id BIGINT)
RETURNS VARCHAR LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_nv public.nhan_vien%ROWTYPE; v_don public.don_hang%ROWTYPE; v_moi VARCHAR;
BEGIN
  SELECT nv.* INTO v_nv FROM public.nhan_vien nv WHERE nv.auth_user_id=auth.uid()
    AND nv.vai_tro IN ('NHAN_VIEN_LAY_HANG','NHAN_VIEN_GIAO_HANG')
    AND nv.trang_thai_duyet='DA_DUYET' AND nv.trang_thai='HOAT_DONG';
  SELECT * INTO v_don FROM public.don_hang WHERE id=p_don_hang_id FOR UPDATE;
  IF v_nv.vai_tro='NHAN_VIEN_LAY_HANG' THEN
    IF v_don.nhan_vien_lay_hang_id<>v_nv.id OR v_don.trang_thai<>'CHO_LAY_HANG' THEN
      RAISE EXCEPTION 'Đơn không thuộc địa bàn lấy hàng của bạn';
    END IF;
    v_moi := 'DA_LAY_HANG';
    UPDATE public.don_hang SET trang_thai=v_moi,kho_hien_tai_id=NULL,
      nhan_vien_hien_tai_id=v_nv.id,ngay_lay_hang=NOW(),ngay_cap_nhat=NOW() WHERE id=p_don_hang_id;
  ELSE
    IF v_don.nhan_vien_giao_hang_id<>v_nv.id OR v_don.trang_thai NOT IN ('DEN_KHO_DICH','GIAO_CHO_SHIPPER','DANG_GIAO_HANG') THEN
      RAISE EXCEPTION 'Đơn không thuộc địa bàn giao hàng của bạn';
    END IF;
    v_moi := CASE WHEN v_don.trang_thai='DANG_GIAO_HANG' THEN 'DA_GIAO_HANG' ELSE 'DANG_GIAO_HANG' END;
    UPDATE public.don_hang SET trang_thai=v_moi,nhan_vien_hien_tai_id=v_nv.id,
      ngay_giao_hang=CASE WHEN v_moi='DA_GIAO_HANG' THEN NOW() ELSE ngay_giao_hang END,
      ngay_cap_nhat=NOW() WHERE id=p_don_hang_id;
  END IF;
  RETURN v_moi;
END;
$$;

CREATE OR REPLACE FUNCTION public.danh_sach_khu_vuc_phan_cong()
RETURNS TABLE(id BIGINT,ten_khu_vuc VARCHAR,tinh_thanh VARCHAR,phuong_xa VARCHAR)
LANGUAGE sql SECURITY DEFINER STABLE SET search_path=public AS $$
  SELECT kv.id,kv.ten_khu_vuc,kv.tinh_thanh,kv.phuong_xa FROM public.khu_vuc kv
  WHERE auth.uid() IS NOT NULL ORDER BY kv.tinh_thanh,kv.phuong_xa
$$;

CREATE OR REPLACE FUNCTION public.danh_sach_dia_ban_giao_nhan(
  p_khu_vuc_id BIGINT
) RETURNS TABLE(id BIGINT,ten_dia_ban VARCHAR,loai_dia_ban VARCHAR)
LANGUAGE sql SECURITY DEFINER STABLE SET search_path=public AS $$
  SELECT db.id,db.ten_dia_ban,db.loai_dia_ban
  FROM public.dia_ban_giao_nhan db
  WHERE db.khu_vuc_id=p_khu_vuc_id AND db.trang_thai='HOAT_DONG'
    AND auth.uid() IS NOT NULL
  ORDER BY public.bo_dau_lower(db.ten_dia_ban),db.id
$$;

CREATE OR REPLACE FUNCTION public.luu_dia_ban_giao_nhan(
  p_khu_vuc_id BIGINT, p_ten_dia_ban TEXT
) RETURNS BIGINT LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE
  v_id BIGINT;
  v_phuong_xa TEXT;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.nhan_vien nv
    WHERE nv.auth_user_id=auth.uid()
      AND nv.vai_tro IN ('ADMIN','QUAN_LY_KHO')
      AND nv.trang_thai_duyet='DA_DUYET' AND nv.trang_thai='HOAT_DONG'
  ) THEN
    RAISE EXCEPTION 'Bạn không có quyền thêm địa bàn';
  END IF;
  IF BTRIM(COALESCE(p_ten_dia_ban,''))='' THEN
    RAISE EXCEPTION 'Tên khu phố/ấp/thôn không được trống';
  END IF;
  SELECT kv.phuong_xa INTO v_phuong_xa FROM public.khu_vuc kv WHERE kv.id=p_khu_vuc_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Phường/xã không tồn tại'; END IF;
  INSERT INTO public.dia_ban_giao_nhan(khu_vuc_id,ten_dia_ban,loai_dia_ban)
  VALUES (
    p_khu_vuc_id,BTRIM(p_ten_dia_ban),
    CASE WHEN public.bo_dau_lower(v_phuong_xa) LIKE 'xa %' THEN 'AP_THON' ELSE 'KHU_PHO' END
  )
  ON CONFLICT (khu_vuc_id,ten_dia_ban)
  DO UPDATE SET trang_thai='HOAT_DONG'
  RETURNING id INTO v_id;
  RETURN v_id;
END;
$$;

ALTER TABLE public.dia_ban_giao_nhan ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS dia_ban_giao_nhan_doc ON public.dia_ban_giao_nhan;
CREATE POLICY dia_ban_giao_nhan_doc ON public.dia_ban_giao_nhan
FOR SELECT TO authenticated USING (TRUE);

REVOKE ALL ON FUNCTION public.nhan_vien_chang_cuoi_cong_viec_v2() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.nhan_vien_chang_cuoi_xac_nhan(BIGINT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.nhan_vien_lay_hang_nhan_don(BIGINT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.nhan_vien_giao_hang_quet_kien(TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.nhan_vien_chang_cuoi_cong_viec_v2() TO authenticated;
GRANT EXECUTE ON FUNCTION public.nhan_vien_chang_cuoi_xac_nhan(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.nhan_vien_lay_hang_nhan_don(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.nhan_vien_giao_hang_quet_kien(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.danh_sach_khu_vuc_phan_cong() TO authenticated;
GRANT EXECUTE ON FUNCTION public.danh_sach_dia_ban_giao_nhan(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.luu_dia_ban_giao_nhan(BIGINT,TEXT) TO authenticated;
NOTIFY pgrst,'reload schema';


-- ============================================================
-- GO TINH NANG DIA BAN NHO - SU DUNG API PHUONG/XA
-- ============================================================
-- Go tinh nang khu pho/ap/thon, quay lai phan cong theo phuong/xa.
-- KHONG xoa don hang, khach hang hoac nhan vien.

DROP FUNCTION IF EXISTS public.danh_sach_dia_ban_giao_nhan(BIGINT);
DROP FUNCTION IF EXISTS public.luu_dia_ban_giao_nhan(BIGINT,TEXT);
DROP FUNCTION IF EXISTS public.tim_dia_ban_giao_nhan(TEXT,BIGINT);

ALTER TABLE public.nhan_vien
  DROP COLUMN IF EXISTS dia_ban_giao_nhan_id;

ALTER TABLE public.don_hang
  DROP COLUMN IF EXISTS dia_ban_lay_hang_id,
  DROP COLUMN IF EXISTS dia_ban_giao_hang_id;

DROP TABLE IF EXISTS public.dia_ban_giao_nhan;

CREATE OR REPLACE FUNCTION public.kiem_tra_dia_ban_nhan_vien_chang_cuoi()
RETURNS TRIGGER LANGUAGE plpgsql SET search_path=public AS $$
DECLARE
  v_kho_cap SMALLINT;
  v_kho_tinh_thanh TEXT;
  v_nhan_vien_tinh_thanh TEXT;
BEGIN
  IF NEW.vai_tro NOT IN ('NHAN_VIEN_LAY_HANG','NHAN_VIEN_GIAO_HANG') THEN
    RETURN NEW;
  END IF;
  IF NEW.kho_hang_id IS NULL OR NEW.khu_vuc_id IS NULL THEN
    RAISE EXCEPTION 'Nhân viên lấy/giao hàng phải có kho cấp 2 và phường/xã phụ trách';
  END IF;
  SELECT kh.cap_kho,kv.tinh_thanh
  INTO v_kho_cap,v_kho_tinh_thanh
  FROM public.kho_hang kh
  JOIN public.khu_vuc kv ON kv.id=kh.khu_vuc_id
  WHERE kh.id=NEW.kho_hang_id;
  IF v_kho_cap IS DISTINCT FROM 2 THEN
    RAISE EXCEPTION 'Nhân viên lấy/giao hàng chỉ được gán vào kho cấp 2';
  END IF;
  SELECT kv.tinh_thanh INTO v_nhan_vien_tinh_thanh
  FROM public.khu_vuc kv WHERE kv.id=NEW.khu_vuc_id;
  IF public.bo_dau_lower(v_kho_tinh_thanh)
     IS DISTINCT FROM public.bo_dau_lower(v_nhan_vien_tinh_thanh) THEN
    RAISE EXCEPTION 'Phường/xã phụ trách phải cùng tỉnh/thành với kho cấp 2';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_kiem_tra_dia_ban_nhan_vien_chang_cuoi
ON public.nhan_vien;
CREATE TRIGGER trg_kiem_tra_dia_ban_nhan_vien_chang_cuoi
BEFORE INSERT OR UPDATE OF vai_tro,kho_hang_id,khu_vuc_id
ON public.nhan_vien
FOR EACH ROW EXECUTE FUNCTION public.kiem_tra_dia_ban_nhan_vien_chang_cuoi();

CREATE OR REPLACE FUNCTION public.phan_cong_nhan_vien_chang_cuoi()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN
  IF NEW.khu_vuc_lay_hang_id IS NULL THEN
    NEW.khu_vuc_lay_hang_id := public.tim_khu_vuc_theo_dia_chi(NEW.nguoi_gui_dia_chi);
  END IF;
  IF NEW.khu_vuc_giao_hang_id IS NULL THEN
    NEW.khu_vuc_giao_hang_id := public.tim_khu_vuc_theo_dia_chi(NEW.nguoi_nhan_dia_chi);
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.nhan_vien_chang_cuoi_cong_viec_v2()
RETURNS TABLE(id BIGINT,ma_van_don VARCHAR,ma_qr UUID,loai_cong_viec TEXT,
  ten_khach TEXT,so_dien_thoai TEXT,dia_chi TEXT,ten_kho TEXT,
  trang_thai VARCHAR,da_nhan BOOLEAN,ngay_cap_nhat TIMESTAMPTZ)
LANGUAGE plpgsql SECURITY DEFINER STABLE SET search_path=public AS $$
DECLARE v_nv public.nhan_vien%ROWTYPE;
BEGIN
  SELECT nv.* INTO v_nv FROM public.nhan_vien nv
  WHERE nv.auth_user_id=auth.uid()
    AND nv.vai_tro IN ('NHAN_VIEN_LAY_HANG','NHAN_VIEN_GIAO_HANG')
    AND nv.trang_thai_duyet='DA_DUYET' AND nv.trang_thai='HOAT_DONG';
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Tài khoản chưa được duyệt hoặc không đúng vai trò';
  END IF;
  RETURN QUERY
  SELECT dh.id,dh.ma_van_don::VARCHAR,dh.ma_qr,
    CASE WHEN v_nv.vai_tro='NHAN_VIEN_LAY_HANG' THEN 'LAY_HANG' ELSE 'GIAO_HANG' END,
    CASE WHEN v_nv.vai_tro='NHAN_VIEN_LAY_HANG' THEN dh.nguoi_gui_ten ELSE dh.nguoi_nhan_ten END,
    CASE WHEN v_nv.vai_tro='NHAN_VIEN_LAY_HANG' THEN dh.nguoi_gui_sdt ELSE dh.nguoi_nhan_sdt END,
    CASE WHEN v_nv.vai_tro='NHAN_VIEN_LAY_HANG' THEN dh.nguoi_gui_dia_chi ELSE dh.nguoi_nhan_dia_chi END,
    kh.ten_kho::TEXT,dh.trang_thai::VARCHAR,
    CASE WHEN v_nv.vai_tro='NHAN_VIEN_LAY_HANG'
      THEN dh.nhan_vien_lay_hang_id=v_nv.id
      ELSE dh.nhan_vien_giao_hang_id=v_nv.id END,
    dh.ngay_cap_nhat
  FROM public.don_hang dh
  JOIN public.kho_hang kh ON kh.id=CASE
    WHEN v_nv.vai_tro='NHAN_VIEN_LAY_HANG' THEN dh.kho_gui_id
    ELSE dh.kho_dich_id END
  WHERE (v_nv.vai_tro='NHAN_VIEN_LAY_HANG'
         AND dh.kho_gui_id=v_nv.kho_hang_id
         AND dh.khu_vuc_lay_hang_id=v_nv.khu_vuc_id
         AND dh.trang_thai='CHO_LAY_HANG'
         AND (dh.nhan_vien_lay_hang_id IS NULL OR dh.nhan_vien_lay_hang_id=v_nv.id))
     OR (v_nv.vai_tro='NHAN_VIEN_GIAO_HANG'
         AND dh.nhan_vien_giao_hang_id=v_nv.id
         AND dh.trang_thai IN ('DEN_KHO_DICH','GIAO_CHO_SHIPPER','DANG_GIAO_HANG'))
  ORDER BY dh.ngay_cap_nhat;
END;
$$;

CREATE OR REPLACE FUNCTION public.nhan_vien_lay_hang_nhan_don(p_don_hang_id BIGINT)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_nv public.nhan_vien%ROWTYPE; v_id BIGINT;
BEGIN
  SELECT nv.* INTO v_nv FROM public.nhan_vien nv
  WHERE nv.auth_user_id=auth.uid()
    AND nv.vai_tro='NHAN_VIEN_LAY_HANG'
    AND nv.trang_thai_duyet='DA_DUYET' AND nv.trang_thai='HOAT_DONG';
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Tài khoản không phải nhân viên lấy hàng đang hoạt động';
  END IF;
  UPDATE public.don_hang dh
  SET nhan_vien_lay_hang_id=v_nv.id,nhan_vien_hien_tai_id=v_nv.id,
      ngay_cap_nhat=NOW()
  WHERE dh.id=p_don_hang_id AND dh.trang_thai='CHO_LAY_HANG'
    AND dh.kho_gui_id=v_nv.kho_hang_id
    AND dh.khu_vuc_lay_hang_id=v_nv.khu_vuc_id
    AND dh.nhan_vien_lay_hang_id IS NULL
  RETURNING dh.id INTO v_id;
  IF v_id IS NULL THEN
    IF EXISTS(SELECT 1 FROM public.don_hang dh
      WHERE dh.id=p_don_hang_id AND dh.nhan_vien_lay_hang_id=v_nv.id) THEN
      RETURN;
    END IF;
    RAISE EXCEPTION 'Đơn đã được nhân viên khác nhận hoặc không thuộc phường/xã của bạn';
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.nhan_vien_giao_hang_quet_kien(p_ma TEXT)
RETURNS BIGINT LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_nv public.nhan_vien%ROWTYPE; v_don public.don_hang%ROWTYPE;
BEGIN
  SELECT nv.* INTO v_nv FROM public.nhan_vien nv
  WHERE nv.auth_user_id=auth.uid()
    AND nv.vai_tro='NHAN_VIEN_GIAO_HANG'
    AND nv.trang_thai_duyet='DA_DUYET' AND nv.trang_thai='HOAT_DONG';
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Tài khoản không phải nhân viên giao hàng đang hoạt động';
  END IF;
  SELECT dh.* INTO v_don FROM public.don_hang dh
  WHERE dh.ma_qr::TEXT=BTRIM(p_ma)
     OR UPPER(dh.ma_van_don)=UPPER(BTRIM(p_ma)) FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Không tìm thấy kiện hàng'; END IF;
  IF v_don.kho_dich_id<>v_nv.kho_hang_id
     OR v_don.khu_vuc_giao_hang_id<>v_nv.khu_vuc_id THEN
    RAISE EXCEPTION 'Kiện hàng không thuộc kho hoặc phường/xã bạn phụ trách';
  END IF;
  IF v_don.trang_thai NOT IN ('DEN_KHO_DICH','GIAO_CHO_SHIPPER') THEN
    RAISE EXCEPTION 'Kiện hàng chưa sẵn sàng để giao';
  END IF;
  IF v_don.nhan_vien_giao_hang_id IS NOT NULL
     AND v_don.nhan_vien_giao_hang_id<>v_nv.id THEN
    RAISE EXCEPTION 'Kiện hàng đã được nhân viên khác quét nhận';
  END IF;
  UPDATE public.don_hang
  SET nhan_vien_giao_hang_id=v_nv.id,nhan_vien_hien_tai_id=v_nv.id,
      trang_thai='GIAO_CHO_SHIPPER',ngay_cap_nhat=NOW()
  WHERE id=v_don.id;
  RETURN v_don.id;
END;
$$;

NOTIFY pgrst,'reload schema';

-- ============================================================
-- BẢN VÁ KIỂU TRẢ VỀ CÔNG VIỆC NHÂN VIÊN CHẶNG CUỐI
-- ============================================================
-- VINEXPRESS - Sửa kiểu dữ liệu hàm công việc nhân viên lấy/giao hàng.
-- Chạy an toàn: chỉ thay nội dung hàm, không xóa bảng và không xóa dữ liệu.

CREATE OR REPLACE FUNCTION public.nhan_vien_chang_cuoi_cong_viec_v2()
RETURNS TABLE(
  id BIGINT,
  ma_van_don VARCHAR,
  ma_qr UUID,
  loai_cong_viec TEXT,
  ten_khach TEXT,
  so_dien_thoai TEXT,
  dia_chi TEXT,
  ten_kho TEXT,
  trang_thai VARCHAR,
  da_nhan BOOLEAN,
  ngay_cap_nhat TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
SET search_path=public
AS $$
DECLARE
  v_nv public.nhan_vien%ROWTYPE;
BEGIN
  SELECT nv.* INTO v_nv
  FROM public.nhan_vien nv
  WHERE nv.auth_user_id=auth.uid()
    AND nv.vai_tro IN ('NHAN_VIEN_LAY_HANG','NHAN_VIEN_GIAO_HANG')
    AND nv.trang_thai_duyet='DA_DUYET'
    AND nv.trang_thai='HOAT_DONG';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Tài khoản chưa được duyệt hoặc không đúng vai trò';
  END IF;

  RETURN QUERY
  SELECT
    dh.id,
    dh.ma_van_don::VARCHAR,
    dh.ma_qr,
    (CASE WHEN v_nv.vai_tro='NHAN_VIEN_LAY_HANG'
      THEN 'LAY_HANG' ELSE 'GIAO_HANG' END)::TEXT,
    (CASE WHEN v_nv.vai_tro='NHAN_VIEN_LAY_HANG'
      THEN dh.nguoi_gui_ten ELSE dh.nguoi_nhan_ten END)::TEXT,
    (CASE WHEN v_nv.vai_tro='NHAN_VIEN_LAY_HANG'
      THEN dh.nguoi_gui_sdt ELSE dh.nguoi_nhan_sdt END)::TEXT,
    (CASE WHEN v_nv.vai_tro='NHAN_VIEN_LAY_HANG'
      THEN dh.nguoi_gui_dia_chi ELSE dh.nguoi_nhan_dia_chi END)::TEXT,
    kh.ten_kho::TEXT,
    dh.trang_thai::VARCHAR,
    CASE WHEN v_nv.vai_tro='NHAN_VIEN_LAY_HANG'
      THEN dh.nhan_vien_lay_hang_id=v_nv.id
      ELSE dh.nhan_vien_giao_hang_id=v_nv.id END,
    dh.ngay_cap_nhat
  FROM public.don_hang dh
  JOIN public.kho_hang kh ON kh.id=CASE
    WHEN v_nv.vai_tro='NHAN_VIEN_LAY_HANG' THEN dh.kho_gui_id
    ELSE dh.kho_dich_id END
  WHERE (
    v_nv.vai_tro='NHAN_VIEN_LAY_HANG'
    AND dh.kho_gui_id=v_nv.kho_hang_id
    AND dh.khu_vuc_lay_hang_id=v_nv.khu_vuc_id
    AND dh.trang_thai='CHO_LAY_HANG'
    AND (dh.nhan_vien_lay_hang_id IS NULL OR dh.nhan_vien_lay_hang_id=v_nv.id)
  ) OR (
    v_nv.vai_tro='NHAN_VIEN_GIAO_HANG'
    AND dh.nhan_vien_giao_hang_id=v_nv.id
    AND dh.trang_thai IN ('DEN_KHO_DICH','GIAO_CHO_SHIPPER','DANG_GIAO_HANG')
  )
  ORDER BY dh.ngay_cap_nhat;
END;
$$;

REVOKE ALL ON FUNCTION public.nhan_vien_chang_cuoi_cong_viec_v2() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.nhan_vien_chang_cuoi_cong_viec_v2() TO authenticated;

NOTIFY pgrst,'reload schema';

-- ============================================================
-- BẢN VÁ NHẬN DIỆN PHƯỜNG/XÃ VÀ ƯU TIÊN KHO CẤP 2
-- ============================================================
-- VINEXPRESS - Sửa đơn không hiện dù nhân viên và đơn cùng phường/xã.
-- Nguyên nhân: dữ liệu khu_vuc có thể trùng tên nhưng khác id.
-- Bản vá chỉ thay hàm, không xóa dữ liệu.

-- Khi một phường/xã có cả kho cấp 1 và cấp 2, đơn phải vào kho cấp 2 trước.
CREATE OR REPLACE FUNCTION public.tim_kho_theo_dia_chi(
  p_dia_chi TEXT,
  p_kho_bo_qua BIGINT DEFAULT NULL
)
RETURNS BIGINT
LANGUAGE plpgsql SECURITY DEFINER STABLE SET search_path=public AS $$
DECLARE
  v_kho_id BIGINT;
BEGIN
  SELECT kh.id INTO v_kho_id
  FROM public.kho_hang kh
  JOIN public.khu_vuc kv ON kv.id=kh.khu_vuc_id
  WHERE kh.trang_thai='HOAT_DONG'
    AND public.bo_dau_lower(p_dia_chi)
      LIKE '%' || public.bo_dau_lower(kv.tinh_thanh) || '%'
    AND public.bo_dau_lower(p_dia_chi)
      LIKE '%' || public.bo_dau_lower(kv.phuong_xa) || '%'
    AND (p_kho_bo_qua IS NULL OR kh.id<>p_kho_bo_qua)
  ORDER BY kh.cap_kho DESC, kh.id
  LIMIT 1;

  IF v_kho_id IS NULL THEN
    RAISE EXCEPTION 'Phường/xã trong địa chỉ chưa có kho hoạt động: %',p_dia_chi;
  END IF;
  RETURN v_kho_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.nhan_vien_chang_cuoi_cong_viec_v2()
RETURNS TABLE(
  id BIGINT, ma_van_don VARCHAR, ma_qr UUID, loai_cong_viec TEXT,
  ten_khach TEXT, so_dien_thoai TEXT, dia_chi TEXT, ten_kho TEXT,
  trang_thai VARCHAR, da_nhan BOOLEAN, ngay_cap_nhat TIMESTAMPTZ
)
LANGUAGE plpgsql SECURITY DEFINER STABLE SET search_path=public AS $$
DECLARE
  v_nv public.nhan_vien%ROWTYPE;
BEGIN
  SELECT nv.* INTO v_nv
  FROM public.nhan_vien nv
  WHERE nv.auth_user_id=auth.uid()
    AND nv.vai_tro IN ('NHAN_VIEN_LAY_HANG','NHAN_VIEN_GIAO_HANG')
    AND nv.trang_thai_duyet='DA_DUYET'
    AND nv.trang_thai='HOAT_DONG';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Tài khoản chưa được duyệt hoặc không đúng vai trò';
  END IF;

  RETURN QUERY
  SELECT
    dh.id,
    dh.ma_van_don::VARCHAR,
    dh.ma_qr,
    (CASE WHEN v_nv.vai_tro='NHAN_VIEN_LAY_HANG'
      THEN 'LAY_HANG' ELSE 'GIAO_HANG' END)::TEXT,
    (CASE WHEN v_nv.vai_tro='NHAN_VIEN_LAY_HANG'
      THEN dh.nguoi_gui_ten ELSE dh.nguoi_nhan_ten END)::TEXT,
    (CASE WHEN v_nv.vai_tro='NHAN_VIEN_LAY_HANG'
      THEN dh.nguoi_gui_sdt ELSE dh.nguoi_nhan_sdt END)::TEXT,
    (CASE WHEN v_nv.vai_tro='NHAN_VIEN_LAY_HANG'
      THEN dh.nguoi_gui_dia_chi ELSE dh.nguoi_nhan_dia_chi END)::TEXT,
    kh.ten_kho::TEXT,
    dh.trang_thai::VARCHAR,
    CASE WHEN v_nv.vai_tro='NHAN_VIEN_LAY_HANG'
      THEN dh.nhan_vien_lay_hang_id=v_nv.id
      ELSE dh.nhan_vien_giao_hang_id=v_nv.id END,
    dh.ngay_cap_nhat
  FROM public.don_hang dh
  JOIN public.kho_hang kh ON kh.id=CASE
    WHEN v_nv.vai_tro='NHAN_VIEN_LAY_HANG' THEN v_nv.kho_hang_id
    ELSE dh.kho_dich_id END
  WHERE (
    v_nv.vai_tro='NHAN_VIEN_LAY_HANG'
    AND dh.trang_thai='CHO_LAY_HANG'
    AND (dh.nhan_vien_lay_hang_id IS NULL OR dh.nhan_vien_lay_hang_id=v_nv.id)
    AND EXISTS (
      SELECT 1
      FROM public.khu_vuc kv_don
      JOIN public.khu_vuc kv_nv ON kv_nv.id=v_nv.khu_vuc_id
      WHERE kv_don.id=dh.khu_vuc_lay_hang_id
        AND public.bo_dau_lower(kv_don.phuong_xa)=public.bo_dau_lower(kv_nv.phuong_xa)
        AND public.bo_dau_lower(kv_don.tinh_thanh)=public.bo_dau_lower(kv_nv.tinh_thanh)
    )
  ) OR (
    v_nv.vai_tro='NHAN_VIEN_GIAO_HANG'
    AND dh.nhan_vien_giao_hang_id=v_nv.id
    AND dh.trang_thai IN ('DEN_KHO_DICH','GIAO_CHO_SHIPPER','DANG_GIAO_HANG')
  )
  ORDER BY dh.ngay_cap_nhat;
END;
$$;

CREATE OR REPLACE FUNCTION public.nhan_vien_lay_hang_nhan_don(
  p_don_hang_id BIGINT
)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE
  v_nv public.nhan_vien%ROWTYPE;
  v_id BIGINT;
BEGIN
  SELECT nv.* INTO v_nv
  FROM public.nhan_vien nv
  WHERE nv.auth_user_id=auth.uid()
    AND nv.vai_tro='NHAN_VIEN_LAY_HANG'
    AND nv.trang_thai_duyet='DA_DUYET'
    AND nv.trang_thai='HOAT_DONG';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Tài khoản không phải nhân viên lấy hàng đang hoạt động';
  END IF;

  UPDATE public.don_hang dh
  SET nhan_vien_lay_hang_id=v_nv.id,
      nhan_vien_hien_tai_id=v_nv.id,
      kho_gui_id=v_nv.kho_hang_id,
      kho_trung_tam_gui_id=(
        SELECT CASE
          WHEN kh.cap_kho=1 THEN kh.id
          ELSE kh.kho_trung_tam_id
        END
        FROM public.kho_hang kh
        WHERE kh.id=v_nv.kho_hang_id
      ),
      ngay_cap_nhat=NOW()
  WHERE dh.id=p_don_hang_id
    AND dh.trang_thai='CHO_LAY_HANG'
    AND dh.nhan_vien_lay_hang_id IS NULL
    AND EXISTS (
      SELECT 1
      FROM public.khu_vuc kv_don
      JOIN public.khu_vuc kv_nv ON kv_nv.id=v_nv.khu_vuc_id
      WHERE kv_don.id=dh.khu_vuc_lay_hang_id
        AND public.bo_dau_lower(kv_don.phuong_xa)=public.bo_dau_lower(kv_nv.phuong_xa)
        AND public.bo_dau_lower(kv_don.tinh_thanh)=public.bo_dau_lower(kv_nv.tinh_thanh)
    )
  RETURNING dh.id INTO v_id;

  IF v_id IS NULL THEN
    IF EXISTS (
      SELECT 1 FROM public.don_hang dh
      WHERE dh.id=p_don_hang_id AND dh.nhan_vien_lay_hang_id=v_nv.id
    ) THEN
      RETURN;
    END IF;
    RAISE EXCEPTION 'Đơn đã được nhân viên khác nhận hoặc không thuộc phường/xã và kho của bạn';
  END IF;
END;
$$;

REVOKE ALL ON FUNCTION public.nhan_vien_chang_cuoi_cong_viec_v2() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.nhan_vien_lay_hang_nhan_don(BIGINT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.nhan_vien_chang_cuoi_cong_viec_v2() TO authenticated;
GRANT EXECUTE ON FUNCTION public.nhan_vien_lay_hang_nhan_don(BIGINT) TO authenticated;

NOTIFY pgrst,'reload schema';

