-- Không cho một xe nhận đồng thời nhiều chuyến chưa kết thúc.
-- Chuyến từ kho cấp 2 lên kho cấp 1 và chuyến quay về là hai chuyến độc lập.
-- Chạy an toàn nhiều lần trong Supabase SQL Editor, không xóa dữ liệu hiện tại.

-- Ghi nhận vị trí vật lý của xe sau khi hoàn tất dỡ hàng. Nhờ đó kho cấp 1
-- vẫn thấy xe của tài xế thuộc kho cấp 2 để tạo chuyến quay về mới.
ALTER TABLE public.xe
ADD COLUMN IF NOT EXISTS kho_hien_tai_id BIGINT
REFERENCES public.kho_hang(id) ON UPDATE CASCADE ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_xe_kho_hien_tai
ON public.xe(kho_hien_tai_id);

-- Ghi rõ kiện thuộc chặng nào để kiện lượt đi không bị nhầm sang lượt về.
ALTER TABLE public.chi_tiet_chuyen_xe
ADD COLUMN IF NOT EXISTS chuyen_xe_chang_id BIGINT
REFERENCES public.chuyen_xe_chang(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE public.chi_tiet_chuyen_xe
ADD COLUMN IF NOT EXISTS da_quet_nhap_kho BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS idx_chi_tiet_chuyen_xe_chang
ON public.chi_tiet_chuyen_xe(chuyen_xe_chang_id);

-- Nhật ký này là bằng chứng duy nhất rằng kiện đã được nhân viên quét nhập
-- tại kho đến. Tháo niêm phong hoặc đổi trạng thái chuyến không tạo bản ghi này.
CREATE TABLE IF NOT EXISTS public.quet_nhap_kho_chang (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chuyen_xe_chang_id BIGINT NOT NULL
    REFERENCES public.chuyen_xe_chang(id) ON UPDATE CASCADE ON DELETE CASCADE,
  don_hang_id BIGINT NOT NULL
    REFERENCES public.don_hang(id) ON UPDATE CASCADE ON DELETE CASCADE,
  kho_hang_id BIGINT NOT NULL
    REFERENCES public.kho_hang(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  nhan_vien_id BIGINT
    REFERENCES public.nhan_vien(id) ON UPDATE CASCADE ON DELETE SET NULL,
  quet_luc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_quet_nhap_kho_chang UNIQUE(chuyen_xe_chang_id,don_hang_id)
);

CREATE INDEX IF NOT EXISTS idx_quet_nhap_kho_chang_don
ON public.quet_nhap_kho_chang(don_hang_id);

UPDATE public.chi_tiet_chuyen_xe ct
SET chuyen_xe_chang_id=c.id
FROM public.chuyen_xe_chang c
WHERE ct.chuyen_xe_chang_id IS NULL
  AND c.chuyen_xe_id=ct.chuyen_xe_id
  AND c.thu_tu_chuyen=1;

-- Chỉ các chuyến đã kết thúc từ trước mới được coi là đã nhập kho.
-- Chuyến đang DA_DEN phải quét thật tại kho đến, kể cả dữ liệu trạng thái cũ bị sai.
UPDATE public.chi_tiet_chuyen_xe ct
SET da_quet_nhap_kho=TRUE
FROM public.chuyen_xe cx
WHERE cx.id=ct.chuyen_xe_id
  AND cx.trang_thai='DA_HOAN_THANH'
  AND ct.trang_thai='DA_DO_HANG';

-- Sửa các chuyến từng bị chuyển nhầm sang DANG_XEP_HANG ngay sau khi tháo
-- niêm phong. Nếu chặng đến đã DA_DEN nhưng còn kiện chưa quét nhập thì xe
-- vẫn đang ở công đoạn dỡ hàng tại kho đến.
UPDATE public.chuyen_xe cx
SET trang_thai='DA_DEN',ngay_cap_nhat=NOW()
WHERE cx.trang_thai='DANG_XEP_HANG'
  AND EXISTS(
    SELECT 1
    FROM public.chuyen_xe_chang c
    JOIN public.chi_tiet_chuyen_xe ct
      ON ct.chuyen_xe_chang_id=c.id
    WHERE c.chuyen_xe_id=cx.id
      AND c.trang_thai='DA_DEN'
      AND ct.da_quet_nhap_kho=FALSE
  );

CREATE OR REPLACE FUNCTION public.kiem_tra_xe_chi_co_mot_chuyen_dang_hoat_dong()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path=public
AS $$
BEGIN
  IF NEW.trang_thai IN ('DA_HOAN_THANH','DA_HUY') THEN
    RETURN NEW;
  END IF;

  -- Chỉ kiểm tra khi tạo mới, đổi xe hoặc mở lại một chuyến đã kết thúc.
  -- Các lần cập nhật trạng thái bình thường của chính chuyến không bị chặn.
  IF TG_OP='UPDATE'
    AND NEW.xe_id=OLD.xe_id
    AND OLD.trang_thai NOT IN ('DA_HOAN_THANH','DA_HUY') THEN
    RETURN NEW;
  END IF;

  -- Khóa theo xe để hai yêu cầu gán xe chạy đồng thời không thể cùng thành công.
  PERFORM 1 FROM public.xe x WHERE x.id=NEW.xe_id FOR UPDATE;

  IF EXISTS(
    SELECT 1
    FROM public.chuyen_xe cx
    WHERE cx.xe_id=NEW.xe_id
      AND cx.id<>COALESCE(NEW.id,0)
      AND cx.trang_thai NOT IN ('DA_HOAN_THANH','DA_HUY')
  ) THEN
    RAISE EXCEPTION 'Xe đang có chuyến chưa hoàn thành, không thể gán thêm chuyến';
  END IF;

  RETURN NEW;
END;
$$;

-- Gắn trạng thái niêm phong vào đúng từng chặng để giao diện tài xế chỉ mở
-- nút khởi hành khi niêm phong được tạo tại kho đi của chặng đó.
CREATE OR REPLACE FUNCTION public.chuyen_xe_cua_tai_xe_co_chang()
RETURNS TABLE (
  id BIGINT,ma_chuyen VARCHAR,trang_thai VARCHAR,
  ngay_khoi_hanh TIMESTAMPTZ,ngay_du_kien TIMESTAMPTZ,ngay_den_thuc_te TIMESTAMPTZ,
  bien_so_xe VARCHAR,tai_trong NUMERIC,kho_di_ten VARCHAR,kho_den_ten VARCHAR,
  so_don_hang BIGINT,chang_duong JSONB,da_niem_phong BOOLEAN,ma_niem_phong VARCHAR
)
LANGUAGE plpgsql SECURITY DEFINER STABLE SET search_path=public AS $$
BEGIN
  IF NOT EXISTS(SELECT 1 FROM public.nhan_vien nv
    WHERE nv.auth_user_id=auth.uid() AND nv.vai_tro='VAN_CHUYEN'
      AND nv.trang_thai_duyet='DA_DUYET' AND nv.trang_thai='HOAT_DONG') THEN
    RAISE EXCEPTION 'Không có quyền xem chuyến xe';
  END IF;

  RETURN QUERY
  SELECT cx.id,cx.ma_chuyen::VARCHAR,cx.trang_thai::VARCHAR,
    cx.ngay_khoi_hanh,cx.ngay_du_kien,cx.ngay_den_thuc_te,
    x.bien_so_xe::VARCHAR,x.tai_trong,kd.ten_kho::VARCHAR,kden.ten_kho::VARCHAR,
    (SELECT COUNT(*) FROM public.chi_tiet_chuyen_xe ct
      WHERE ct.chuyen_xe_id=cx.id)::BIGINT,
    COALESCE(tuyen.chang_duong,'[]'::JSONB),
    (niem_phong.id IS NOT NULL),niem_phong.ma_niem_phong::VARCHAR
  FROM public.chuyen_xe cx
  JOIN public.xe x ON x.id=cx.xe_id
  JOIN public.nhan_vien nv ON nv.id=x.tai_xe_id
  LEFT JOIN LATERAL (SELECT c.kho_di_id FROM public.chuyen_xe_chang c
    WHERE c.chuyen_xe_id=cx.id ORDER BY c.thu_tu_chuyen LIMIT 1) dau ON TRUE
  LEFT JOIN LATERAL (SELECT c.kho_den_id FROM public.chuyen_xe_chang c
    WHERE c.chuyen_xe_id=cx.id ORDER BY c.thu_tu_chuyen DESC LIMIT 1) cuoi ON TRUE
  LEFT JOIN public.kho_hang kd ON kd.id=dau.kho_di_id
  LEFT JOIN public.kho_hang kden ON kden.id=cuoi.kho_den_id
  LEFT JOIN LATERAL (
    SELECT jsonb_agg(jsonb_build_object(
      'id',c.id,'thu_tu_chuyen',c.thu_tu_chuyen,'trang_thai',c.trang_thai,
      'ngay_khoi_hanh',c.ngay_khoi_hanh,'ngay_den_du_kien',c.ngay_den_du_kien,
      'ngay_den_thuc_te',c.ngay_den_thuc_te,
      'kho_di_id',kdi.id,'kho_di_ma',kdi.ma_kho,'kho_di_ten',kdi.ten_kho,
      'kho_di_dia_chi',kdi.dia_chi,'kho_di_so_dien_thoai',kdi.so_dien_thoai,
      'kho_den_id',kde.id,'kho_den_ma',kde.ma_kho,'kho_den_ten',kde.ten_kho,
      'kho_den_dia_chi',kde.dia_chi,'kho_den_so_dien_thoai',kde.so_dien_thoai,
      'da_niem_phong',COALESCE(niem_phong_chang.da_niem_phong,FALSE)
    ) ORDER BY c.thu_tu_chuyen) AS chang_duong
    FROM public.chuyen_xe_chang c
    JOIN public.kho_hang kdi ON kdi.id=c.kho_di_id
    JOIN public.kho_hang kde ON kde.id=c.kho_den_id
    LEFT JOIN LATERAL (
      SELECT TRUE AS da_niem_phong
      FROM public.niem_phong_xe np
      WHERE np.chuyen_xe_id=cx.id
        AND np.kho_niem_phong_id=c.kho_di_id
        AND np.trang_thai='DA_NIEM_PHONG'
      LIMIT 1
    ) niem_phong_chang ON TRUE
    WHERE c.chuyen_xe_id=cx.id
  ) tuyen ON TRUE
  LEFT JOIN LATERAL (SELECT np.id,np.ma_niem_phong FROM public.niem_phong_xe np
    WHERE np.chuyen_xe_id=cx.id AND np.trang_thai='DA_NIEM_PHONG'
    ORDER BY np.thoi_gian_niem_phong DESC LIMIT 1) niem_phong ON TRUE
  WHERE nv.auth_user_id=auth.uid()
  ORDER BY CASE cx.trang_thai WHEN 'DANG_DI' THEN 1 WHEN 'DANG_XEP_HANG' THEN 2
    WHEN 'CHO_KHOI_HANH' THEN 3 WHEN 'DA_DEN' THEN 4 ELSE 5 END,cx.ngay_tao DESC;
END;
$$;

-- Trả đúng thao tác của chặng hiện tại tại kho: dỡ xong chặng đến mới chuyển
-- sang xếp hàng cho chặng kế tiếp. Mỗi lần chỉ trả một chặng của một chuyến.
CREATE OR REPLACE FUNCTION public.nhan_vien_kho_tim_chuyen_theo_xe(
  p_tu_khoa TEXT
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
SET search_path=public
AS $$
DECLARE
  v_kho_id BIGINT;
  v_xe public.xe%ROWTYPE;
  v_tu_khoa TEXT := BTRIM(COALESCE(p_tu_khoa,''));
  v_bien_so_chuan TEXT;
  v_chuyen_xe JSONB;
BEGIN
  SELECT nv.kho_hang_id INTO v_kho_id
  FROM public.nhan_vien nv
  WHERE nv.auth_user_id=auth.uid()
    AND nv.vai_tro='NHAN_VIEN_KHO'
    AND nv.trang_thai_duyet='DA_DUYET'
    AND nv.trang_thai='HOAT_DONG';
  IF v_kho_id IS NULL THEN RAISE EXCEPTION 'Nhân viên chưa được gán kho'; END IF;
  IF v_tu_khoa='' THEN RAISE EXCEPTION 'Hãy nhập ID xe hoặc biển số xe'; END IF;

  v_bien_so_chuan := regexp_replace(UPPER(v_tu_khoa),'[^A-Z0-9]','','g');
  SELECT x.* INTO v_xe
  FROM public.xe x
  LEFT JOIN public.nhan_vien tx ON tx.id=x.tai_xe_id
  WHERE (
      (v_tu_khoa ~ '^[0-9]+$' AND x.id::TEXT=v_tu_khoa)
      OR regexp_replace(UPPER(x.bien_so_xe),'[^A-Z0-9]','','g')=v_bien_so_chuan
    )
    AND (
      tx.kho_hang_id=v_kho_id
      OR EXISTS(
        SELECT 1 FROM public.chuyen_xe cx
        JOIN public.chuyen_xe_chang c ON c.chuyen_xe_id=cx.id
        WHERE cx.xe_id=x.id
          AND cx.trang_thai NOT IN ('DA_HOAN_THANH','DA_HUY')
          AND (c.kho_di_id=v_kho_id OR c.kho_den_id=v_kho_id)
      )
    )
  ORDER BY CASE WHEN x.id::TEXT=v_tu_khoa THEN 0 ELSE 1 END
  LIMIT 1;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Không tìm thấy xe trong phạm vi kho với ID hoặc biển số đã nhập';
  END IF;

  SELECT COALESCE(jsonb_agg(to_jsonb(q)-'ngay_tao' ORDER BY q.ngay_tao DESC),'[]'::JSONB)
  INTO v_chuyen_xe
  FROM (
    SELECT cx.id,cx.ma_chuyen::VARCHAR,cx.trang_thai::VARCHAR,
      x.bien_so_xe::VARCHAR,tx.ho_ten::VARCHAR AS ten_tai_xe,
      c.id AS chang_id,c.thu_tu_chuyen,c.kho_di_id,
      kd.ten_kho::VARCHAR AS ten_kho_di,c.kho_den_id,
      kn.ten_kho::VARCHAR AS ten_kho_den,
      CASE WHEN c.kho_di_id=v_kho_id THEN 'XEP_LEN_XE' ELSE 'NHAP_KHO' END AS thao_tac,
      EXISTS(
        SELECT 1 FROM public.niem_phong_xe np
        WHERE np.chuyen_xe_id=cx.id AND np.trang_thai='DA_NIEM_PHONG'
      ) AS da_niem_phong,
      (SELECT np.ma_niem_phong FROM public.niem_phong_xe np
        WHERE np.chuyen_xe_id=cx.id AND np.trang_thai='DA_NIEM_PHONG'
        ORDER BY np.thoi_gian_niem_phong DESC LIMIT 1) AS ma_niem_phong,
      (SELECT COUNT(*) FROM public.chi_tiet_chuyen_xe ct
        WHERE ct.chuyen_xe_id=cx.id)::BIGINT AS so_kien,
      (SELECT COUNT(*) FROM public.chi_tiet_chuyen_xe ct
        WHERE ct.chuyen_xe_chang_id=c.id)::BIGINT AS so_kien_chang,
      (SELECT COUNT(*) FROM public.quet_nhap_kho_chang qn
        WHERE qn.chuyen_xe_chang_id=c.id)::BIGINT AS so_kien_da_nhap,
      NOT EXISTS(
        SELECT 1 FROM public.chi_tiet_chuyen_xe ct
        WHERE ct.chuyen_xe_chang_id=c.id
          AND NOT EXISTS(
            SELECT 1 FROM public.quet_nhap_kho_chang qn
            WHERE qn.chuyen_xe_chang_id=c.id
              AND qn.don_hang_id=ct.don_hang_id
          )
      ) AS da_do_xong,
      cx.ngay_tao
    FROM public.chuyen_xe cx
    JOIN public.xe x ON x.id=cx.xe_id
    LEFT JOIN public.nhan_vien tx ON tx.id=x.tai_xe_id
    JOIN LATERAL (
      SELECT c0.*
      FROM public.chuyen_xe_chang c0
      LEFT JOIN LATERAL (
        SELECT 1 AS tim_thay
        FROM public.niem_phong_xe np0
        WHERE np0.chuyen_xe_id=cx.id
          AND np0.kho_niem_phong_id=c0.kho_di_id
          AND np0.trang_thai='DA_NIEM_PHONG'
        LIMIT 1
      ) niem_phong_chang ON TRUE
      LEFT JOIN LATERAL (
        SELECT 1 AS tim_thay
        FROM public.chi_tiet_chuyen_xe ct0
        WHERE ct0.chuyen_xe_id=cx.id
          AND ct0.chuyen_xe_chang_id=c0.id
          AND NOT EXISTS(
            SELECT 1 FROM public.quet_nhap_kho_chang qn0
            WHERE qn0.chuyen_xe_chang_id=c0.id
              AND qn0.don_hang_id=ct0.don_hang_id
          )
        LIMIT 1
      ) kien_chua_do ON TRUE
      WHERE c0.chuyen_xe_id=cx.id
        AND (
          (
            c0.kho_den_id=v_kho_id
            AND c0.trang_thai IN ('DANG_DI','DA_DEN')
            AND (
              c0.trang_thai='DANG_DI'
              OR cx.trang_thai='DA_DEN'
              OR niem_phong_chang.tim_thay IS NOT NULL
              OR kien_chua_do.tim_thay IS NOT NULL
            )
          )
          OR (
            c0.kho_di_id=v_kho_id
            AND c0.trang_thai='CHO_KHOI_HANH'
            AND cx.trang_thai IN ('CHO_KHOI_HANH','DANG_XEP_HANG')
            AND NOT EXISTS(
              SELECT 1 FROM public.chuyen_xe_chang truoc
              WHERE truoc.chuyen_xe_id=cx.id
                AND truoc.thu_tu_chuyen<c0.thu_tu_chuyen
                AND truoc.trang_thai<>'DA_DEN'
            )
            AND NOT EXISTS(
              SELECT 1
              FROM public.chuyen_xe_chang truoc
              JOIN public.chi_tiet_chuyen_xe ct_truoc
                ON ct_truoc.chuyen_xe_id=truoc.chuyen_xe_id
                AND ct_truoc.chuyen_xe_chang_id=truoc.id
              WHERE truoc.chuyen_xe_id=c0.chuyen_xe_id
                AND truoc.thu_tu_chuyen<c0.thu_tu_chuyen
                AND NOT EXISTS(
                  SELECT 1 FROM public.quet_nhap_kho_chang qn_truoc
                  WHERE qn_truoc.chuyen_xe_chang_id=truoc.id
                    AND qn_truoc.don_hang_id=ct_truoc.don_hang_id
                )
            )
          )
        )
      ORDER BY CASE WHEN c0.kho_den_id=v_kho_id THEN 0 ELSE 1 END,
        c0.thu_tu_chuyen
      LIMIT 1
    ) c ON TRUE
    JOIN public.kho_hang kd ON kd.id=c.kho_di_id
    JOIN public.kho_hang kn ON kn.id=c.kho_den_id
    WHERE cx.xe_id=v_xe.id
      AND cx.trang_thai NOT IN ('DA_HOAN_THANH','DA_HUY')
  ) q;

  RETURN jsonb_build_object(
    'xe',jsonb_build_object(
      'id',v_xe.id,'bien_so_xe',v_xe.bien_so_xe,
      'trang_thai',v_xe.trang_thai,
      'ten_tai_xe',(SELECT nv.ho_ten FROM public.nhan_vien nv WHERE nv.id=v_xe.tai_xe_id)
    ),
    'chuyen_xe',v_chuyen_xe
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.nhan_vien_kho_xac_nhan_do_xong(
  p_chuyen_xe_id BIGINT
) RETURNS VARCHAR
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE
  v_nv public.nhan_vien%ROWTYPE;
  v_chuyen public.chuyen_xe%ROWTYPE;
  v_chang public.chuyen_xe_chang%ROWTYPE;
  v_con_lai BIGINT;
  v_la_chuyen_len_cap_1 BOOLEAN := FALSE;
BEGIN
  SELECT nv.* INTO v_nv FROM public.nhan_vien nv
  WHERE nv.auth_user_id=auth.uid() AND nv.vai_tro='NHAN_VIEN_KHO'
    AND nv.trang_thai_duyet='DA_DUYET' AND nv.trang_thai='HOAT_DONG';
  IF NOT FOUND OR v_nv.kho_hang_id IS NULL THEN
    RAISE EXCEPTION 'Nhân viên chưa được gán kho';
  END IF;

  SELECT cx.* INTO v_chuyen FROM public.chuyen_xe cx
  WHERE cx.id=p_chuyen_xe_id
    AND cx.trang_thai NOT IN ('DA_HOAN_THANH','DA_HUY')
  FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Không tìm thấy chuyến đang xử lý'; END IF;

  SELECT c.* INTO v_chang FROM public.chuyen_xe_chang c
  WHERE c.chuyen_xe_id=p_chuyen_xe_id
    AND c.kho_den_id=v_nv.kho_hang_id
    AND c.trang_thai='DA_DEN'
  ORDER BY c.thu_tu_chuyen DESC LIMIT 1;
  IF NOT FOUND THEN RAISE EXCEPTION 'Không có chặng đang dỡ tại kho này'; END IF;

  IF EXISTS(
    SELECT 1 FROM public.niem_phong_xe np
    WHERE np.chuyen_xe_id=p_chuyen_xe_id
      AND np.trang_thai='DA_NIEM_PHONG'
  ) THEN
    RAISE EXCEPTION 'Phải mở niêm phong trước khi xác nhận dỡ xong';
  END IF;

  SELECT COUNT(*) INTO v_con_lai
  FROM public.chi_tiet_chuyen_xe ct
  WHERE ct.chuyen_xe_chang_id=v_chang.id
    AND NOT EXISTS(
      SELECT 1 FROM public.quet_nhap_kho_chang qn
      WHERE qn.chuyen_xe_chang_id=v_chang.id
        AND qn.don_hang_id=ct.don_hang_id
    );
  IF v_con_lai>0 THEN
    RAISE EXCEPTION 'Còn % kiện chưa quét nhập kho',v_con_lai;
  END IF;

  SELECT EXISTS(
    SELECT 1
    FROM public.kho_hang k_di
    JOIN public.kho_hang k_den ON k_den.id=v_chang.kho_den_id
    WHERE k_di.id=v_chang.kho_di_id
      AND k_di.cap_kho=2 AND k_den.cap_kho=1
      AND k_di.kho_trung_tam_id=k_den.id
  ) INTO v_la_chuyen_len_cap_1;

  IF v_la_chuyen_len_cap_1 THEN
    -- Chuyến cấp 2 lên cấp 1 kết thúc hoàn toàn sau khi dỡ xong. Chuyến quay
    -- về phải do quản lý tạo thành một chuyến mới có mã và niêm phong riêng.
    IF EXISTS(
      SELECT 1
      FROM public.chuyen_xe_chang c_sau
      JOIN public.chi_tiet_chuyen_xe ct ON ct.chuyen_xe_chang_id=c_sau.id
      WHERE c_sau.chuyen_xe_id=p_chuyen_xe_id
        AND c_sau.thu_tu_chuyen>v_chang.thu_tu_chuyen
        AND c_sau.trang_thai='CHO_KHOI_HANH'
    ) THEN
      RAISE EXCEPTION 'Chặng tiếp theo của chuyến cũ đã có kiện, không thể kết thúc';
    END IF;

    DELETE FROM public.chuyen_xe_chang c_sau
    WHERE c_sau.chuyen_xe_id=p_chuyen_xe_id
      AND c_sau.thu_tu_chuyen>v_chang.thu_tu_chuyen
      AND c_sau.trang_thai='CHO_KHOI_HANH';
  ELSIF EXISTS(
    SELECT 1 FROM public.chuyen_xe_chang c_sau
    WHERE c_sau.chuyen_xe_id=p_chuyen_xe_id
      AND c_sau.thu_tu_chuyen>v_chang.thu_tu_chuyen
      AND c_sau.kho_di_id=v_nv.kho_hang_id
      AND c_sau.trang_thai='CHO_KHOI_HANH'
  ) THEN
    UPDATE public.chuyen_xe
    SET trang_thai='DANG_XEP_HANG',ngay_cap_nhat=NOW()
    WHERE id=p_chuyen_xe_id;
    RETURN 'DANG_XEP_HANG';
  END IF;

  UPDATE public.chuyen_xe
  SET trang_thai='DA_HOAN_THANH',ngay_cap_nhat=NOW()
  WHERE id=p_chuyen_xe_id;
  UPDATE public.xe
  SET trang_thai='SAN_SANG',kho_hien_tai_id=v_nv.kho_hang_id,
    ngay_cap_nhat=NOW()
  WHERE id=v_chuyen.xe_id;
  RETURN 'DA_HOAN_THANH';
END;
$$;

CREATE OR REPLACE FUNCTION public.nhan_vien_kho_quet_kien_chuyen(
  p_chuyen_xe_id BIGINT,p_ma TEXT,p_thao_tac TEXT
) RETURNS VARCHAR
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE
  v_nv public.nhan_vien%ROWTYPE;
  v_don public.don_hang%ROWTYPE;
  v_chang public.chuyen_xe_chang%ROWTYPE;
  v_chang_do public.chuyen_xe_chang%ROWTYPE;
  v_thao_tac TEXT := UPPER(BTRIM(COALESCE(p_thao_tac,'')));
  v_trang_thai VARCHAR;
BEGIN
  SELECT nv.* INTO v_nv FROM public.nhan_vien nv
  WHERE nv.auth_user_id=auth.uid() AND nv.vai_tro='NHAN_VIEN_KHO'
    AND nv.trang_thai_duyet='DA_DUYET' AND nv.trang_thai='HOAT_DONG';
  IF NOT FOUND OR v_nv.kho_hang_id IS NULL THEN RAISE EXCEPTION 'Nhân viên chưa được gán kho'; END IF;

  IF v_thao_tac='XEP_LEN_XE' THEN
    SELECT c.* INTO v_chang FROM public.chuyen_xe_chang c
    WHERE c.chuyen_xe_id=p_chuyen_xe_id
      AND c.kho_di_id=v_nv.kho_hang_id
      AND c.trang_thai='CHO_KHOI_HANH'
      AND NOT EXISTS(SELECT 1 FROM public.chuyen_xe_chang truoc
        WHERE truoc.chuyen_xe_id=c.chuyen_xe_id
          AND truoc.thu_tu_chuyen<c.thu_tu_chuyen
          AND truoc.trang_thai<>'DA_DEN')
    ORDER BY c.thu_tu_chuyen LIMIT 1;
  ELSIF v_thao_tac='NHAP_KHO' THEN
    SELECT c.* INTO v_chang FROM public.chuyen_xe_chang c
    WHERE c.chuyen_xe_id=p_chuyen_xe_id
      AND c.kho_den_id=v_nv.kho_hang_id
      AND c.trang_thai='DA_DEN'
    ORDER BY c.thu_tu_chuyen DESC LIMIT 1;
  ELSE
    RAISE EXCEPTION 'Thao tác quét không hợp lệ';
  END IF;
  IF NOT FOUND THEN RAISE EXCEPTION 'Không tìm thấy chặng phù hợp tại kho của bạn'; END IF;

  SELECT dh.* INTO v_don FROM public.don_hang dh
  WHERE dh.ma_qr::TEXT=BTRIM(p_ma) OR UPPER(dh.ma_van_don)=UPPER(BTRIM(p_ma))
  FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Không tìm thấy kiện hàng'; END IF;

  IF v_thao_tac='XEP_LEN_XE' THEN
    IF EXISTS(SELECT 1 FROM public.niem_phong_xe np
      WHERE np.chuyen_xe_id=p_chuyen_xe_id AND np.trang_thai='DA_NIEM_PHONG') THEN
      RAISE EXCEPTION 'Xe đã niêm phong, không thể xếp thêm kiện';
    END IF;
    IF v_don.kho_hien_tai_id IS DISTINCT FROM v_nv.kho_hang_id THEN
      RAISE EXCEPTION 'Kiện hàng chưa có trong kho này';
    END IF;
    IF EXISTS(SELECT 1 FROM public.chi_tiet_chuyen_xe ct
      JOIN public.chuyen_xe cx ON cx.id=ct.chuyen_xe_id
      WHERE ct.don_hang_id=v_don.id AND cx.id<>p_chuyen_xe_id
        AND cx.trang_thai NOT IN ('DA_HOAN_THANH','DA_HUY')) THEN
      RAISE EXCEPTION 'Kiện hàng đã thuộc chuyến xe khác';
    END IF;
    -- Một xe có thể đi nhiều kho cấp 2. Kiện được gắn vào đúng chặng nơi
    -- kiện phải dỡ; các chặng trước chỉ là chặng kiện đi xuyên qua.
    SELECT c_do.* INTO v_chang_do
    FROM public.chuyen_xe_chang c_do
    WHERE c_do.chuyen_xe_id=p_chuyen_xe_id
      AND c_do.thu_tu_chuyen>=v_chang.thu_tu_chuyen
      AND c_do.kho_den_id=v_don.kho_dich_id
      AND c_do.trang_thai='CHO_KHOI_HANH'
    ORDER BY c_do.thu_tu_chuyen
    LIMIT 1;
    IF NOT FOUND THEN
      IF v_chang.kho_den_id=v_don.kho_dich_id THEN
        v_chang_do := v_chang;
      ELSE
        RAISE EXCEPTION 'Tuyến xe chưa có điểm dừng tại kho đích của kiện hàng';
      END IF;
    END IF;
    INSERT INTO public.chi_tiet_chuyen_xe(
      chuyen_xe_id,don_hang_id,chuyen_xe_chang_id,trang_thai
    )
    VALUES(p_chuyen_xe_id,v_don.id,v_chang_do.id,'DA_XEP_HANG')
    ON CONFLICT(chuyen_xe_id,don_hang_id) DO UPDATE
      SET chuyen_xe_chang_id=EXCLUDED.chuyen_xe_chang_id,
          da_quet_nhap_kho=FALSE,trang_thai='DA_XEP_HANG',
          ngay_xep_hang=NOW(),ngay_do_hang=NULL;
    UPDATE public.chuyen_xe SET trang_thai='DANG_XEP_HANG',ngay_cap_nhat=NOW()
    WHERE id=p_chuyen_xe_id AND trang_thai IN ('CHO_KHOI_HANH','DA_DEN');
    v_trang_thai := 'DA_XEP_HANG';
  ELSE
    IF EXISTS(SELECT 1 FROM public.niem_phong_xe np
      WHERE np.chuyen_xe_id=p_chuyen_xe_id AND np.trang_thai='DA_NIEM_PHONG') THEN
      RAISE EXCEPTION 'Hãy mở niêm phong xe trước khi quét dỡ kiện';
    END IF;
    IF NOT EXISTS(SELECT 1 FROM public.chi_tiet_chuyen_xe ct
      WHERE ct.chuyen_xe_id=p_chuyen_xe_id
        AND ct.chuyen_xe_chang_id=v_chang.id
        AND ct.don_hang_id=v_don.id) THEN
      RAISE EXCEPTION 'Kiện hàng không thuộc chặng đang vận chuyển của xe này';
    END IF;
    IF EXISTS(
      SELECT 1 FROM public.quet_nhap_kho_chang qn
      WHERE qn.chuyen_xe_chang_id=v_chang.id
        AND qn.don_hang_id=v_don.id
    ) THEN
      RAISE EXCEPTION 'Kiện hàng đã được nhập vào kho này';
    END IF;
    UPDATE public.chi_tiet_chuyen_xe
    SET trang_thai='DA_DO_HANG',da_quet_nhap_kho=TRUE,ngay_do_hang=NOW()
    WHERE chuyen_xe_id=p_chuyen_xe_id
      AND chuyen_xe_chang_id=v_chang.id
      AND don_hang_id=v_don.id;
    INSERT INTO public.quet_nhap_kho_chang(
      chuyen_xe_chang_id,don_hang_id,kho_hang_id,nhan_vien_id,quet_luc
    ) VALUES(v_chang.id,v_don.id,v_nv.kho_hang_id,v_nv.id,NOW())
    ON CONFLICT(chuyen_xe_chang_id,don_hang_id) DO NOTHING;
    UPDATE public.don_hang SET kho_hien_tai_id=v_nv.kho_hang_id,
      nhan_vien_hien_tai_id=v_nv.id,
      trang_thai=CASE WHEN kho_dich_id=v_nv.kho_hang_id
        THEN 'DEN_KHO_DICH' ELSE 'DEN_KHO_TRUNG_CHUYEN' END,
      ngay_cap_nhat=NOW() WHERE id=v_don.id;

    -- Giữ công đoạn dỡ xe sau lần quét cuối. Nhân viên phải bấm xác nhận
    -- đã dỡ xong để tránh tự chuyển chặng khi thực tế còn kiện trên thùng xe.
    v_trang_thai := 'DA_NHAP_KHO';
  END IF;
  RETURN v_trang_thai;
END;
$$;

CREATE OR REPLACE FUNCTION public.nhan_vien_kho_niem_phong_chuyen(
  p_chuyen_xe_id BIGINT,p_ma_niem_phong TEXT
) RETURNS VARCHAR
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE
  v_nv public.nhan_vien%ROWTYPE;
  v_chuyen public.chuyen_xe%ROWTYPE;
  v_chang public.chuyen_xe_chang%ROWTYPE;
  v_ma TEXT := UPPER(BTRIM(COALESCE(p_ma_niem_phong,'')));
  v_so_kien BIGINT;
BEGIN
  SELECT nv.* INTO v_nv FROM public.nhan_vien nv
  WHERE nv.auth_user_id=auth.uid() AND nv.vai_tro='NHAN_VIEN_KHO'
    AND nv.trang_thai_duyet='DA_DUYET' AND nv.trang_thai='HOAT_DONG';
  IF NOT FOUND OR v_nv.kho_hang_id IS NULL THEN RAISE EXCEPTION 'Nhân viên chưa được gán kho'; END IF;
  IF v_ma='' THEN RAISE EXCEPTION 'Hãy nhập mã niêm phong'; END IF;

  SELECT cx.* INTO v_chuyen FROM public.chuyen_xe cx
  WHERE cx.id=p_chuyen_xe_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Không tìm thấy chuyến xe'; END IF;
  SELECT c.* INTO v_chang FROM public.chuyen_xe_chang c
  WHERE c.chuyen_xe_id=p_chuyen_xe_id
    AND c.kho_di_id=v_nv.kho_hang_id
    AND c.trang_thai='CHO_KHOI_HANH'
    AND NOT EXISTS(SELECT 1 FROM public.chuyen_xe_chang truoc
      WHERE truoc.chuyen_xe_id=c.chuyen_xe_id
        AND truoc.thu_tu_chuyen<c.thu_tu_chuyen
        AND truoc.trang_thai<>'DA_DEN')
  ORDER BY c.thu_tu_chuyen LIMIT 1;
  IF NOT FOUND THEN RAISE EXCEPTION 'Không có chặng chờ khởi hành từ kho của bạn'; END IF;
  IF v_chuyen.trang_thai NOT IN ('CHO_KHOI_HANH','DANG_XEP_HANG','DA_DEN') THEN
    RAISE EXCEPTION 'Trạng thái chuyến không cho phép niêm phong';
  END IF;
  IF EXISTS(SELECT 1 FROM public.niem_phong_xe np
    WHERE np.chuyen_xe_id=p_chuyen_xe_id AND np.trang_thai='DA_NIEM_PHONG') THEN
    RAISE EXCEPTION 'Xe đã được niêm phong';
  END IF;
  IF EXISTS(SELECT 1 FROM public.niem_phong_xe np
    WHERE UPPER(BTRIM(np.ma_niem_phong))=v_ma) THEN
    RAISE EXCEPTION 'Mã niêm phong đã được sử dụng';
  END IF;
  IF v_chang.thu_tu_chuyen>1 THEN
    IF EXISTS(
      SELECT 1
      FROM public.chuyen_xe_chang truoc
      JOIN public.chi_tiet_chuyen_xe ct
        ON ct.chuyen_xe_id=truoc.chuyen_xe_id
        AND ct.chuyen_xe_chang_id=truoc.id
      WHERE truoc.chuyen_xe_id=p_chuyen_xe_id
        AND truoc.thu_tu_chuyen<v_chang.thu_tu_chuyen
        AND NOT EXISTS(
          SELECT 1 FROM public.quet_nhap_kho_chang qn
          WHERE qn.chuyen_xe_chang_id=truoc.id
            AND qn.don_hang_id=ct.don_hang_id
        )
    ) THEN
      RAISE EXCEPTION 'Phải dỡ hết kiện của chặng trước trước khi niêm phong chặng về';
    END IF;
  END IF;

  SELECT COUNT(*) INTO v_so_kien FROM public.chi_tiet_chuyen_xe ct
  WHERE ct.chuyen_xe_id=p_chuyen_xe_id
    AND ct.chuyen_xe_chang_id=v_chang.id
    AND ct.trang_thai='DA_XEP_HANG';
  IF v_so_kien=0 AND v_chang.thu_tu_chuyen=1 THEN
    RAISE EXCEPTION 'Chuyến chưa có kiện hàng để niêm phong';
  END IF;

  BEGIN
    INSERT INTO public.niem_phong_xe(
      chuyen_xe_id,ma_niem_phong,kho_niem_phong_id,nguoi_niem_phong_id,trang_thai
    ) VALUES(p_chuyen_xe_id,v_ma,v_nv.kho_hang_id,v_nv.id,'DA_NIEM_PHONG');
  EXCEPTION WHEN unique_violation THEN
    RAISE EXCEPTION 'Mã niêm phong đã được sử dụng';
  END;
  RETURN v_ma;
END;
$$;

CREATE OR REPLACE FUNCTION public.nhan_vien_kho_mo_niem_phong_chuyen(
  p_chuyen_xe_id BIGINT,p_ma_niem_phong TEXT
) RETURNS VARCHAR
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE
  v_nv public.nhan_vien%ROWTYPE;
  v_chang public.chuyen_xe_chang%ROWTYPE;
  v_niem_phong public.niem_phong_xe%ROWTYPE;
  v_ma TEXT := UPPER(BTRIM(COALESCE(p_ma_niem_phong,'')));
BEGIN
  SELECT nv.* INTO v_nv FROM public.nhan_vien nv
  WHERE nv.auth_user_id=auth.uid() AND nv.vai_tro='NHAN_VIEN_KHO'
    AND nv.trang_thai_duyet='DA_DUYET' AND nv.trang_thai='HOAT_DONG';
  IF NOT FOUND OR v_nv.kho_hang_id IS NULL THEN RAISE EXCEPTION 'Nhân viên chưa được gán kho'; END IF;
  IF v_ma='' THEN RAISE EXCEPTION 'Hãy nhập mã niêm phong trên xe'; END IF;

  SELECT c.* INTO v_chang FROM public.chuyen_xe_chang c
  WHERE c.chuyen_xe_id=p_chuyen_xe_id
    AND c.kho_den_id=v_nv.kho_hang_id
    AND c.trang_thai='DA_DEN'
  ORDER BY c.thu_tu_chuyen DESC LIMIT 1;
  IF NOT FOUND THEN RAISE EXCEPTION 'Tài xế chưa xác nhận đến kho của bạn'; END IF;

  SELECT np.* INTO v_niem_phong FROM public.niem_phong_xe np
  WHERE np.chuyen_xe_id=p_chuyen_xe_id
    AND np.kho_niem_phong_id=v_chang.kho_di_id
    AND np.trang_thai='DA_NIEM_PHONG'
  ORDER BY np.thoi_gian_niem_phong DESC LIMIT 1 FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Không tìm thấy niêm phong đang đóng của chặng này'; END IF;
  IF UPPER(BTRIM(v_niem_phong.ma_niem_phong))<>v_ma THEN
    RAISE EXCEPTION 'Mã niêm phong không khớp với mã đã ghi nhận';
  END IF;
  UPDATE public.niem_phong_xe SET trang_thai='DA_MO',
    kho_mo_niem_phong_id=v_nv.kho_hang_id,nguoi_mo_id=v_nv.id,thoi_gian_mo=NOW()
  WHERE id=v_niem_phong.id;

  -- Mở niêm phong chỉ bắt đầu công đoạn dỡ xe. Không được tự chuyển sang
  -- chặng quay về trước khi từng kiện có nhật ký quét nhập tại kho đến.
  UPDATE public.chuyen_xe_chang
  SET trang_thai='DA_DEN',ngay_cap_nhat=NOW()
  WHERE id=v_chang.id;
  UPDATE public.chuyen_xe
  SET trang_thai='DA_DEN',ngay_cap_nhat=NOW()
  WHERE id=p_chuyen_xe_id;
  UPDATE public.chi_tiet_chuyen_xe ct
  SET da_quet_nhap_kho=FALSE,
      trang_thai='DANG_VAN_CHUYEN',
      ngay_do_hang=NULL
  WHERE ct.chuyen_xe_id=p_chuyen_xe_id
    AND (ct.chuyen_xe_chang_id=v_chang.id OR ct.chuyen_xe_chang_id IS NULL)
    AND NOT EXISTS(
      SELECT 1 FROM public.quet_nhap_kho_chang qn
      WHERE qn.chuyen_xe_chang_id=v_chang.id
        AND qn.don_hang_id=ct.don_hang_id
    );

  -- Tương thích chuyến cũ chỉ có một chặng: khi xe cấp 2 đã lên đúng
  -- kho cấp 1, gắn ngay chặng quay về kho cấp 2 sau khi mở niêm phong.
  IF v_chang.thu_tu_chuyen=1 THEN
    IF EXISTS(
      SELECT 1 FROM public.kho_hang k2
      WHERE k2.id=v_chang.kho_di_id
        AND k2.cap_kho=2
        AND k2.kho_trung_tam_id=v_chang.kho_den_id
    ) THEN
      IF NOT EXISTS(
        SELECT 1 FROM public.chuyen_xe_chang c2
        WHERE c2.chuyen_xe_id=p_chuyen_xe_id AND c2.thu_tu_chuyen>1
      ) THEN
        INSERT INTO public.chuyen_xe_chang(
          chuyen_xe_id,thu_tu_chuyen,kho_di_id,kho_den_id,
          nguoi_phan_cong_id,ngay_den_du_kien
        ) VALUES(
          p_chuyen_xe_id,2,v_chang.kho_den_id,v_chang.kho_di_id,
          v_chang.nguoi_phan_cong_id,NULL
        ) ON CONFLICT(chuyen_xe_id,thu_tu_chuyen) DO NOTHING;
      END IF;
    END IF;
  END IF;

  RETURN v_niem_phong.ma_niem_phong;
END;
$$;

DROP TRIGGER IF EXISTS trg_xe_chi_co_mot_chuyen_dang_hoat_dong
ON public.chuyen_xe;
CREATE TRIGGER trg_xe_chi_co_mot_chuyen_dang_hoat_dong
BEFORE INSERT OR UPDATE OF xe_id,trang_thai ON public.chuyen_xe
FOR EACH ROW
WHEN (NEW.trang_thai NOT IN ('DA_HOAN_THANH','DA_HUY'))
EXECUTE FUNCTION public.kiem_tra_xe_chi_co_mot_chuyen_dang_hoat_dong();

CREATE OR REPLACE FUNCTION public.quan_ly_kho_danh_sach_xe(p_kho_id BIGINT)
RETURNS TABLE(id BIGINT,bien_so_xe VARCHAR,tai_trong NUMERIC,trang_thai VARCHAR,
  tai_xe_id BIGINT,ten_tai_xe VARCHAR,so_dien_thoai VARCHAR)
LANGUAGE plpgsql SECURITY DEFINER STABLE SET search_path=public AS $$
BEGIN
  IF NOT public.quan_ly_kho_duoc_quan_ly(p_kho_id) THEN
    RAISE EXCEPTION 'Kho không thuộc phạm vi quản lý';
  END IF;

  RETURN QUERY
  SELECT x.id,x.bien_so_xe::VARCHAR,x.tai_trong,
    CASE
      WHEN x.kho_hien_tai_id=p_kho_id
        AND k_tx.cap_kho=2 AND k_tx.kho_trung_tam_id=p_kho_id
      THEN 'CHO_CHANG_VE'::VARCHAR
      ELSE 'SAN_SANG'::VARCHAR
    END AS trang_thai,
    x.tai_xe_id,nv.ho_ten::VARCHAR,nv.so_dien_thoai::VARCHAR
  FROM public.xe x
  JOIN public.nhan_vien nv ON nv.id=x.tai_xe_id
  LEFT JOIN public.kho_hang k_tx ON k_tx.id=nv.kho_hang_id
  WHERE x.trang_thai='SAN_SANG'
    AND nv.vai_tro='VAN_CHUYEN'
    AND nv.trang_thai_duyet='DA_DUYET'
    AND nv.trang_thai='HOAT_DONG'
    AND (
      nv.kho_hang_id=p_kho_id
      OR (x.kho_hien_tai_id=p_kho_id
        AND k_tx.cap_kho=2 AND k_tx.kho_trung_tam_id=p_kho_id)
    )
    AND NOT EXISTS(
      SELECT 1 FROM public.chuyen_xe cx
      WHERE cx.xe_id=x.id
        AND cx.trang_thai NOT IN ('DA_HOAN_THANH','DA_HUY')
    )
  ORDER BY CASE
      WHEN x.kho_hien_tai_id=p_kho_id
        AND k_tx.cap_kho=2 AND k_tx.kho_trung_tam_id=p_kho_id THEN 0
      ELSE 1
    END,x.bien_so_xe;
END;
$$;

-- Danh sách kho đến đúng cấp: kho cấp 2 đi lên kho cấp 1 cha; kho cấp 1 chỉ
-- phân tuyến xuống các kho cấp 2 trực thuộc, không đưa kho cấp 1 khác vào.
CREATE OR REPLACE FUNCTION public.quan_ly_kho_danh_sach_kho_den(p_kho_di_id BIGINT)
RETURNS TABLE(id BIGINT,ma_kho VARCHAR,ten_kho VARCHAR,dia_chi TEXT,
  cap_kho SMALLINT,kho_trung_tam_id BIGINT)
LANGUAGE plpgsql SECURITY DEFINER STABLE SET search_path=public AS $$
DECLARE v_cap SMALLINT; v_kho_cha BIGINT;
BEGIN
  IF NOT public.quan_ly_kho_duoc_quan_ly(p_kho_di_id) THEN
    RAISE EXCEPTION 'Kho khởi hành không thuộc phạm vi quản lý';
  END IF;
  SELECT kh.cap_kho,kh.kho_trung_tam_id INTO v_cap,v_kho_cha
  FROM public.kho_hang kh WHERE kh.id=p_kho_di_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Không tìm thấy kho khởi hành'; END IF;

  IF v_cap=2 THEN
    RETURN QUERY SELECT kh.id,kh.ma_kho::VARCHAR,kh.ten_kho::VARCHAR,
      kh.dia_chi,kh.cap_kho,kh.kho_trung_tam_id
    FROM public.kho_hang kh
    WHERE kh.id=v_kho_cha AND kh.cap_kho=1 AND kh.trang_thai='HOAT_DONG';
  ELSE
    RETURN QUERY SELECT kh.id,kh.ma_kho::VARCHAR,kh.ten_kho::VARCHAR,
      kh.dia_chi,kh.cap_kho,kh.kho_trung_tam_id
    FROM public.kho_hang kh
    WHERE kh.cap_kho=2 AND kh.kho_trung_tam_id=p_kho_di_id
      AND kh.trang_thai='HOAT_DONG'
    ORDER BY kh.ten_kho;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.quan_ly_kho_chang_ve_mac_dinh(
  p_kho_id BIGINT,p_xe_id BIGINT
) RETURNS BIGINT LANGUAGE plpgsql SECURITY DEFINER STABLE SET search_path=public AS $$
DECLARE v_kho_cap_2_id BIGINT;
BEGIN
  IF NOT public.quan_ly_kho_duoc_quan_ly(p_kho_id) THEN
    RAISE EXCEPTION 'Kho không thuộc phạm vi quản lý';
  END IF;
  SELECT tx.kho_hang_id INTO v_kho_cap_2_id
  FROM public.xe x
  JOIN public.nhan_vien tx ON tx.id=x.tai_xe_id
  JOIN public.kho_hang k2 ON k2.id=tx.kho_hang_id
  WHERE x.id=p_xe_id AND x.trang_thai='SAN_SANG'
    AND x.kho_hien_tai_id=p_kho_id
    AND k2.cap_kho=2 AND k2.kho_trung_tam_id=p_kho_id
    AND NOT EXISTS(
      SELECT 1 FROM public.chuyen_xe cx
      WHERE cx.xe_id=x.id
        AND cx.trang_thai NOT IN ('DA_HOAN_THANH','DA_HUY')
    );
  RETURN v_kho_cap_2_id;
END;
$$;

-- Màn quản lý phải hiển thị chặng đang xử lý tại kho, không cố định chặng 1.
-- Sau khi xác nhận dỡ xong, thẻ chuyến đổi từ chặng đến sang chặng xuất phát.
CREATE OR REPLACE FUNCTION public.quan_ly_kho_danh_sach_chuyen(p_kho_id BIGINT)
RETURNS TABLE(id BIGINT,ma_chuyen VARCHAR,trang_thai VARCHAR,xe_id BIGINT,
  bien_so_xe VARCHAR,ten_tai_xe VARCHAR,kho_di_id BIGINT,ten_kho_di VARCHAR,
  kho_den_id BIGINT,ten_kho_den VARCHAR,ngay_du_kien TIMESTAMPTZ,
  so_kien BIGINT)
LANGUAGE plpgsql SECURITY DEFINER STABLE SET search_path=public AS $$
BEGIN
  IF NOT public.quan_ly_kho_duoc_quan_ly(p_kho_id) THEN
    RAISE EXCEPTION 'Kho không thuộc phạm vi quản lý';
  END IF;
  RETURN QUERY
  SELECT cx.id,cx.ma_chuyen::VARCHAR,cx.trang_thai::VARCHAR,cx.xe_id,
    x.bien_so_xe::VARCHAR,nv.ho_ten::VARCHAR,c.kho_di_id,kd.ten_kho::VARCHAR,
    c.kho_den_id,kn.ten_kho::VARCHAR,cx.ngay_du_kien,
    (SELECT COUNT(*) FROM public.chi_tiet_chuyen_xe ct
      WHERE ct.chuyen_xe_id=cx.id)::BIGINT
  FROM public.chuyen_xe cx
  JOIN public.xe x ON x.id=cx.xe_id
  LEFT JOIN public.nhan_vien nv ON nv.id=x.tai_xe_id
  JOIN LATERAL (
    SELECT c0.*
    FROM public.chuyen_xe_chang c0
    WHERE c0.chuyen_xe_id=cx.id
      AND (c0.kho_di_id=p_kho_id OR c0.kho_den_id=p_kho_id)
    ORDER BY CASE
      WHEN cx.trang_thai IN ('CHO_KHOI_HANH','DANG_XEP_HANG')
        AND c0.kho_di_id=p_kho_id
        AND c0.trang_thai='CHO_KHOI_HANH'
        AND NOT EXISTS(
          SELECT 1 FROM public.chuyen_xe_chang c_truoc
          WHERE c_truoc.chuyen_xe_id=c0.chuyen_xe_id
            AND c_truoc.thu_tu_chuyen<c0.thu_tu_chuyen
            AND c_truoc.trang_thai<>'DA_DEN'
        ) THEN 0
      WHEN cx.trang_thai IN ('DANG_DI','DA_DEN')
        AND c0.kho_den_id=p_kho_id
        AND c0.trang_thai IN ('DANG_DI','DA_DEN') THEN 0
      WHEN c0.trang_thai='DANG_DI' THEN 1
      WHEN c0.trang_thai='DA_DEN' THEN 2
      WHEN c0.trang_thai='CHO_KHOI_HANH' THEN 3
      ELSE 4
    END,c0.thu_tu_chuyen
    LIMIT 1
  ) c ON TRUE
  JOIN public.kho_hang kd ON kd.id=c.kho_di_id
  JOIN public.kho_hang kn ON kn.id=c.kho_den_id
  ORDER BY cx.ngay_tao DESC LIMIT 200;
END;
$$;

CREATE OR REPLACE FUNCTION public.quan_ly_kho_gan_xe_tao_chuyen(
  p_kho_di_id BIGINT,p_kho_den_id BIGINT,p_xe_id BIGINT,
  p_ngay_du_kien TIMESTAMPTZ DEFAULT NULL
) RETURNS BIGINT LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE
  v_nv_id BIGINT;
  v_chuyen_id BIGINT;
  v_ma VARCHAR;
  v_cap_di SMALLINT;
  v_kho_cha BIGINT;
BEGIN
  IF p_kho_di_id=p_kho_den_id THEN
    RAISE EXCEPTION 'Kho đi và kho đến phải khác nhau';
  END IF;
  IF NOT public.quan_ly_kho_duoc_quan_ly(p_kho_di_id) THEN
    RAISE EXCEPTION 'Bạn không quản lý kho khởi hành';
  END IF;

  SELECT nv.id INTO v_nv_id
  FROM public.nhan_vien nv
  WHERE nv.auth_user_id=auth.uid()
    AND nv.vai_tro='QUAN_LY_KHO'
    AND nv.trang_thai_duyet='DA_DUYET'
    AND nv.trang_thai='HOAT_DONG';
  IF v_nv_id IS NULL THEN
    RAISE EXCEPTION 'Tài khoản không phải quản lý kho';
  END IF;

  SELECT kh.cap_kho,kh.kho_trung_tam_id
  INTO v_cap_di,v_kho_cha
  FROM public.kho_hang kh
  WHERE kh.id=p_kho_di_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Không tìm thấy kho khởi hành'; END IF;
  IF v_cap_di=2 AND p_kho_den_id<>v_kho_cha THEN
    RAISE EXCEPTION 'Kho cấp 2 chỉ được tạo chuyến lên kho cấp 1 trực thuộc';
  END IF;
  IF NOT EXISTS(
    SELECT 1 FROM public.quan_ly_kho_danh_sach_kho_den(p_kho_di_id) d
    WHERE d.id=p_kho_den_id
  ) THEN
    RAISE EXCEPTION 'Kho đến không đúng tuyến được phép';
  END IF;

  -- Khóa bản ghi xe trước khi kiểm tra để chống hai quản lý gán cùng lúc.
  PERFORM 1 FROM public.xe x WHERE x.id=p_xe_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Không tìm thấy xe'; END IF;

  IF NOT EXISTS(
    SELECT 1 FROM public.xe x
    JOIN public.nhan_vien tx ON tx.id=x.tai_xe_id
    WHERE x.id=p_xe_id
      AND x.trang_thai='SAN_SANG'
      AND tx.vai_tro='VAN_CHUYEN'
      AND (tx.kho_hang_id=p_kho_di_id OR x.kho_hien_tai_id=p_kho_di_id)
      AND tx.trang_thai_duyet='DA_DUYET'
      AND tx.trang_thai='HOAT_DONG'
  ) THEN
    RAISE EXCEPTION 'Xe không sẵn sàng hoặc hiện không có tại kho này';
  END IF;
  IF EXISTS(
    SELECT 1 FROM public.chuyen_xe cx
    WHERE cx.xe_id=p_xe_id
      AND cx.trang_thai NOT IN ('DA_HOAN_THANH','DA_HUY')
  ) THEN
    RAISE EXCEPTION 'Xe đang có chuyến chưa hoàn thành, không thể gán thêm chuyến';
  END IF;

  v_ma := 'CX' || TO_CHAR(NOW(),'YYMMDDHH24MISS')
    || UPPER(SUBSTR(REPLACE(gen_random_uuid()::TEXT,'-',''),1,5));
  INSERT INTO public.chuyen_xe(xe_id,ma_chuyen,trang_thai,ngay_du_kien)
  VALUES(p_xe_id,v_ma,'CHO_KHOI_HANH',p_ngay_du_kien)
  RETURNING id INTO v_chuyen_id;

  INSERT INTO public.chuyen_xe_chang(
    chuyen_xe_id,thu_tu_chuyen,kho_di_id,kho_den_id,
    nguoi_phan_cong_id,ngay_den_du_kien
  ) VALUES(
    v_chuyen_id,1,p_kho_di_id,p_kho_den_id,v_nv_id,p_ngay_du_kien
  );

  RETURN v_chuyen_id;
END;
$$;

-- Tạo một chuyến mới từ kho cấp 1 đến một hoặc nhiều kho cấp 2.
CREATE OR REPLACE FUNCTION public.quan_ly_kho_gan_xe_tao_tuyen(
  p_kho_di_id BIGINT,p_kho_den_ids BIGINT[],p_xe_id BIGINT,
  p_ngay_du_kien TIMESTAMPTZ DEFAULT NULL
) RETURNS BIGINT LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE
  v_nv_id BIGINT;
  v_chuyen_id BIGINT;
  v_ma VARCHAR;
  v_kho_den_id BIGINT;
  v_kho_truoc_id BIGINT;
  v_thu_tu INTEGER;
BEGIN
  IF COALESCE(array_length(p_kho_den_ids,1),0)=0 THEN
    RAISE EXCEPTION 'Hãy chọn ít nhất một kho cấp 2';
  END IF;
  IF EXISTS(
    SELECT 1 FROM unnest(p_kho_den_ids) d(id)
    WHERE d.id IS NULL OR d.id=p_kho_di_id
  ) THEN
    RAISE EXCEPTION 'Danh sách điểm dừng không hợp lệ';
  END IF;
  IF (SELECT COUNT(*) FROM unnest(p_kho_den_ids) d(id))<>
     (SELECT COUNT(DISTINCT d.id) FROM unnest(p_kho_den_ids) d(id)) THEN
    RAISE EXCEPTION 'Không được chọn trùng kho trong cùng một tuyến';
  END IF;
  IF NOT public.quan_ly_kho_duoc_quan_ly(p_kho_di_id) THEN
    RAISE EXCEPTION 'Bạn không quản lý kho khởi hành';
  END IF;
  IF NOT EXISTS(
    SELECT 1 FROM public.kho_hang k
    WHERE k.id=p_kho_di_id AND k.cap_kho=1
  ) THEN
    RAISE EXCEPTION 'Chỉ kho cấp 1 được gán tuyến đến nhiều kho cấp 2';
  END IF;
  IF EXISTS(
    SELECT 1 FROM unnest(p_kho_den_ids) d(id)
    LEFT JOIN public.kho_hang k ON k.id=d.id
    WHERE k.id IS NULL OR k.cap_kho<>2 OR k.kho_trung_tam_id<>p_kho_di_id
  ) THEN
    RAISE EXCEPTION 'Các điểm dừng phải là kho cấp 2 trực thuộc kho cấp 1 này';
  END IF;

  SELECT nv.id INTO v_nv_id FROM public.nhan_vien nv
  WHERE nv.auth_user_id=auth.uid() AND nv.vai_tro='QUAN_LY_KHO'
    AND nv.trang_thai_duyet='DA_DUYET' AND nv.trang_thai='HOAT_DONG';
  IF v_nv_id IS NULL THEN RAISE EXCEPTION 'Tài khoản không phải quản lý kho'; END IF;

  PERFORM 1 FROM public.xe x WHERE x.id=p_xe_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Không tìm thấy xe'; END IF;

  IF EXISTS(
    SELECT 1 FROM public.chuyen_xe cx WHERE cx.xe_id=p_xe_id
      AND cx.trang_thai NOT IN ('DA_HOAN_THANH','DA_HUY')
  ) THEN
    RAISE EXCEPTION 'Xe đang có chuyến chưa hoàn thành, không thể tạo chuyến mới';
  END IF;
  IF NOT EXISTS(
    SELECT 1 FROM public.xe x JOIN public.nhan_vien tx ON tx.id=x.tai_xe_id
    WHERE x.id=p_xe_id AND x.trang_thai='SAN_SANG'
      AND (tx.kho_hang_id=p_kho_di_id OR x.kho_hien_tai_id=p_kho_di_id)
      AND tx.vai_tro='VAN_CHUYEN'
      AND tx.trang_thai_duyet='DA_DUYET' AND tx.trang_thai='HOAT_DONG'
  ) THEN
    RAISE EXCEPTION 'Xe không sẵn sàng hoặc hiện không có tại kho này';
  END IF;

  v_ma := 'CX' || TO_CHAR(NOW(),'YYMMDDHH24MISS')
    || UPPER(SUBSTR(REPLACE(gen_random_uuid()::TEXT,'-',''),1,5));
  INSERT INTO public.chuyen_xe(xe_id,ma_chuyen,trang_thai,ngay_du_kien)
  VALUES(p_xe_id,v_ma,'CHO_KHOI_HANH',p_ngay_du_kien)
  RETURNING id INTO v_chuyen_id;
  v_kho_truoc_id := p_kho_di_id;
  v_thu_tu := 0;

  FOREACH v_kho_den_id IN ARRAY p_kho_den_ids LOOP
    v_thu_tu := v_thu_tu+1;
    INSERT INTO public.chuyen_xe_chang(
      chuyen_xe_id,thu_tu_chuyen,kho_di_id,kho_den_id,
      nguoi_phan_cong_id,ngay_den_du_kien
    ) VALUES(
      v_chuyen_id,v_thu_tu,v_kho_truoc_id,v_kho_den_id,
      v_nv_id,p_ngay_du_kien
    );
    v_kho_truoc_id := v_kho_den_id;
  END LOOP;

  RETURN v_chuyen_id;
END;
$$;

-- Khôi phục các chuyến đã bị chuyển nhầm sang chặng về trước khi có nhật ký
-- quét nhập. Khi chưa có bất kỳ lần quét nhập nào tại chặng đến, toàn bộ kiện
-- vẫn thuộc chặng đi và chuyến phải ở trạng thái DA_DEN để tiếp tục dỡ hàng.
UPDATE public.chuyen_xe_chang c1
SET trang_thai='DA_DEN',ngay_cap_nhat=NOW()
WHERE c1.thu_tu_chuyen=1
  AND EXISTS(
    SELECT 1 FROM public.chuyen_xe cx
    WHERE cx.id=c1.chuyen_xe_id
      AND cx.trang_thai NOT IN ('DA_HOAN_THANH','DA_HUY')
  )
  AND EXISTS(
    SELECT 1 FROM public.niem_phong_xe np
    WHERE np.chuyen_xe_id=c1.chuyen_xe_id
      AND np.kho_niem_phong_id=c1.kho_di_id
      AND np.kho_mo_niem_phong_id=c1.kho_den_id
      AND np.trang_thai='DA_MO'
  )
  AND EXISTS(
    SELECT 1 FROM public.chi_tiet_chuyen_xe ct
    WHERE ct.chuyen_xe_id=c1.chuyen_xe_id
      AND NOT EXISTS(
        SELECT 1 FROM public.quet_nhap_kho_chang qn
        WHERE qn.chuyen_xe_chang_id=c1.id
          AND qn.don_hang_id=ct.don_hang_id
      )
  )
  AND NOT EXISTS(
    SELECT 1
    FROM public.chuyen_xe_chang c_sau
    JOIN public.niem_phong_xe np_sau
      ON np_sau.chuyen_xe_id=c_sau.chuyen_xe_id
      AND np_sau.kho_niem_phong_id=c_sau.kho_di_id
      AND np_sau.trang_thai='DA_NIEM_PHONG'
    WHERE c_sau.chuyen_xe_id=c1.chuyen_xe_id
      AND c_sau.thu_tu_chuyen>c1.thu_tu_chuyen
  );

WITH chuyen_can_sua AS (
  SELECT cx.id AS chuyen_xe_id,c1.id AS chang_den_id
  FROM public.chuyen_xe cx
  JOIN public.chuyen_xe_chang c1
    ON c1.chuyen_xe_id=cx.id AND c1.thu_tu_chuyen=1 AND c1.trang_thai='DA_DEN'
  JOIN public.chuyen_xe_chang c2
    ON c2.chuyen_xe_id=cx.id AND c2.thu_tu_chuyen=2 AND c2.trang_thai='CHO_KHOI_HANH'
  JOIN public.kho_hang k2
    ON k2.id=c1.kho_di_id AND k2.cap_kho=2
    AND k2.kho_trung_tam_id=c1.kho_den_id
  WHERE cx.trang_thai IN ('DA_DEN','DANG_XEP_HANG')
    AND NOT EXISTS(
      SELECT 1 FROM public.chuyen_xe_chang c3
      WHERE c3.chuyen_xe_id=cx.id AND c3.thu_tu_chuyen>2
    )
    AND NOT EXISTS(
      SELECT 1 FROM public.quet_nhap_kho_chang qn
      WHERE qn.chuyen_xe_chang_id=c1.id
    )
    AND NOT EXISTS(
      SELECT 1 FROM public.niem_phong_xe np
      WHERE np.chuyen_xe_id=cx.id
        AND np.kho_niem_phong_id=c2.kho_di_id
        AND np.trang_thai='DA_NIEM_PHONG'
    )
)
UPDATE public.chi_tiet_chuyen_xe ct
SET chuyen_xe_chang_id=s.chang_den_id,
    da_quet_nhap_kho=FALSE,
    trang_thai='DANG_VAN_CHUYEN',
    ngay_do_hang=NULL
FROM chuyen_can_sua s
WHERE ct.chuyen_xe_id=s.chuyen_xe_id;

UPDATE public.chuyen_xe cx
SET trang_thai='DA_DEN',ngay_cap_nhat=NOW()
WHERE cx.trang_thai='DANG_XEP_HANG'
  AND EXISTS(
    SELECT 1
    FROM public.chuyen_xe_chang c1
    JOIN public.chi_tiet_chuyen_xe ct ON ct.chuyen_xe_chang_id=c1.id
    WHERE c1.chuyen_xe_id=cx.id
      AND c1.thu_tu_chuyen=1
      AND c1.trang_thai='DA_DEN'
      AND NOT EXISTS(
        SELECT 1 FROM public.quet_nhap_kho_chang qn
        WHERE qn.chuyen_xe_chang_id=c1.id
          AND qn.don_hang_id=ct.don_hang_id
      )
  );

-- Chuyển đổi dữ liệu cũ: nếu chuyến đến đã mở niêm phong và mọi kiện của
-- chặng đến đã được quét, kết thúc chuyến cũ và trả xe về trạng thái sẵn sàng
-- tại kho đến. Chặng quay về trống từng được tạo tự động sẽ được bỏ đi; quản
-- lý kho cấp 1 sẽ tạo một chuyến mới có mã chuyến riêng.
WITH chang_da_do_xong AS (
  SELECT cx.id AS chuyen_xe_id,c_den.id AS chang_den_id
  FROM public.chuyen_xe cx
  JOIN public.chuyen_xe_chang c_den ON c_den.chuyen_xe_id=cx.id
  JOIN public.kho_hang k_di ON k_di.id=c_den.kho_di_id
    AND k_di.cap_kho=2 AND k_di.kho_trung_tam_id=c_den.kho_den_id
  JOIN public.kho_hang k_den ON k_den.id=c_den.kho_den_id AND k_den.cap_kho=1
  WHERE cx.trang_thai IN ('DA_DEN','DANG_XEP_HANG')
    AND c_den.thu_tu_chuyen=1 AND c_den.trang_thai='DA_DEN'
    AND NOT EXISTS(
      SELECT 1 FROM public.niem_phong_xe np
      WHERE np.chuyen_xe_id=cx.id AND np.trang_thai='DA_NIEM_PHONG'
    )
    AND EXISTS(
      SELECT 1 FROM public.chi_tiet_chuyen_xe ct
      WHERE ct.chuyen_xe_id=cx.id AND ct.chuyen_xe_chang_id=c_den.id
    )
    AND NOT EXISTS(
      SELECT 1 FROM public.chi_tiet_chuyen_xe ct
      WHERE ct.chuyen_xe_id=cx.id AND ct.chuyen_xe_chang_id=c_den.id
        AND NOT EXISTS(
          SELECT 1 FROM public.quet_nhap_kho_chang qn
          WHERE qn.chuyen_xe_chang_id=c_den.id
            AND qn.don_hang_id=ct.don_hang_id
        )
    )
)
DELETE FROM public.chuyen_xe_chang c_sau
USING chang_da_do_xong d
WHERE c_sau.chuyen_xe_id=d.chuyen_xe_id
  AND c_sau.id<>d.chang_den_id
  AND c_sau.trang_thai='CHO_KHOI_HANH'
  AND NOT EXISTS(
    SELECT 1 FROM public.chi_tiet_chuyen_xe ct
    WHERE ct.chuyen_xe_chang_id=c_sau.id
  );

WITH chuyen_da_do_xong AS (
  SELECT cx.id,cx.xe_id,c_den.kho_den_id
  FROM public.chuyen_xe cx
  JOIN public.chuyen_xe_chang c_den ON c_den.chuyen_xe_id=cx.id
  JOIN public.kho_hang k_di ON k_di.id=c_den.kho_di_id
    AND k_di.cap_kho=2 AND k_di.kho_trung_tam_id=c_den.kho_den_id
  JOIN public.kho_hang k_den ON k_den.id=c_den.kho_den_id AND k_den.cap_kho=1
  WHERE cx.trang_thai IN ('DA_DEN','DANG_XEP_HANG')
    AND c_den.thu_tu_chuyen=1 AND c_den.trang_thai='DA_DEN'
    AND NOT EXISTS(
      SELECT 1 FROM public.chuyen_xe_chang c_cho
      WHERE c_cho.chuyen_xe_id=cx.id AND c_cho.trang_thai='CHO_KHOI_HANH'
    )
    AND NOT EXISTS(
      SELECT 1 FROM public.niem_phong_xe np
      WHERE np.chuyen_xe_id=cx.id AND np.trang_thai='DA_NIEM_PHONG'
    )
    AND EXISTS(
      SELECT 1 FROM public.chi_tiet_chuyen_xe ct
      WHERE ct.chuyen_xe_id=cx.id AND ct.chuyen_xe_chang_id=c_den.id
    )
    AND NOT EXISTS(
      SELECT 1 FROM public.chi_tiet_chuyen_xe ct
      WHERE ct.chuyen_xe_id=cx.id AND ct.chuyen_xe_chang_id=c_den.id
        AND NOT EXISTS(
          SELECT 1 FROM public.quet_nhap_kho_chang qn
          WHERE qn.chuyen_xe_chang_id=c_den.id
            AND qn.don_hang_id=ct.don_hang_id
        )
    )
), chuyen_vua_dong AS (
  UPDATE public.chuyen_xe cx
  SET trang_thai='DA_HOAN_THANH',
      ngay_den_thuc_te=COALESCE(cx.ngay_den_thuc_te,NOW()),
      ngay_cap_nhat=NOW()
  FROM chuyen_da_do_xong d
  WHERE cx.id=d.id
  RETURNING cx.id,cx.xe_id,d.kho_den_id
)
UPDATE public.xe x
SET trang_thai='SAN_SANG',kho_hien_tai_id=d.kho_den_id,ngay_cap_nhat=NOW()
FROM chuyen_vua_dong d
WHERE x.id=d.xe_id
  AND NOT EXISTS(
    SELECT 1 FROM public.chuyen_xe cx_khac
    WHERE cx_khac.xe_id=x.id
      AND cx_khac.trang_thai NOT IN ('DA_HOAN_THANH','DA_HUY')
  );

-- Đồng bộ lại vị trí cho các chuyến đã được đánh dấu hoàn thành từ trước.
-- Chỉ lấy chuyến hoàn thành gần nhất của mỗi xe và không đụng tới xe đang
-- bảo trì/ngừng hoạt động hoặc xe đã nhận một chuyến mới.
WITH chuyen_hoan_thanh_gan_nhat AS (
  SELECT DISTINCT ON (cx.xe_id)
    cx.xe_id,c_cuoi.kho_den_id
  FROM public.chuyen_xe cx
  JOIN LATERAL (
    SELECT c.kho_den_id
    FROM public.chuyen_xe_chang c
    WHERE c.chuyen_xe_id=cx.id AND c.trang_thai='DA_DEN'
    ORDER BY c.thu_tu_chuyen DESC
    LIMIT 1
  ) c_cuoi ON TRUE
  WHERE cx.trang_thai='DA_HOAN_THANH'
    AND NOT EXISTS(
      SELECT 1 FROM public.chuyen_xe cx_moi
      WHERE cx_moi.xe_id=cx.xe_id
        AND cx_moi.trang_thai NOT IN ('DA_HOAN_THANH','DA_HUY')
    )
  ORDER BY cx.xe_id,
    COALESCE(cx.ngay_den_thuc_te,cx.ngay_cap_nhat,cx.ngay_tao) DESC,
    cx.id DESC
)
UPDATE public.xe x
SET trang_thai='SAN_SANG',
    kho_hien_tai_id=g.kho_den_id,
    ngay_cap_nhat=NOW()
FROM chuyen_hoan_thanh_gan_nhat g
WHERE x.id=g.xe_id
  AND x.trang_thai IN ('DANG_CHAY','SAN_SANG');

-- Cập nhật đúng từng chặng trong một chuyến nhiều điểm dừng.
CREATE OR REPLACE FUNCTION public.cap_nhat_chuyen_xe_tai_xe(
  p_chuyen_xe_id BIGINT,
  p_trang_thai_moi TEXT
) RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path=public
AS $$
DECLARE
  v_trang_thai VARCHAR(30);
  v_xe_id BIGINT;
  v_chang_id BIGINT;
  v_kho_hien_tai_id BIGINT;
  v_con_chang_cho BOOLEAN;
BEGIN
  SELECT cx.trang_thai,x.id
  INTO v_trang_thai,v_xe_id
  FROM public.chuyen_xe cx
  JOIN public.xe x ON x.id=cx.xe_id
  JOIN public.nhan_vien nv ON nv.id=x.tai_xe_id
  WHERE cx.id=p_chuyen_xe_id
    AND nv.auth_user_id=auth.uid()
    AND nv.vai_tro='VAN_CHUYEN'
    AND nv.trang_thai_duyet='DA_DUYET'
    AND nv.trang_thai='HOAT_DONG'
  FOR UPDATE OF cx,x;
  IF NOT FOUND THEN RAISE EXCEPTION 'Không tìm thấy chuyến xe được phân công'; END IF;

  IF p_trang_thai_moi='DANG_DI' THEN
    IF v_trang_thai NOT IN ('CHO_KHOI_HANH','DANG_XEP_HANG','DA_DEN') THEN
      RAISE EXCEPTION 'Không thể bắt đầu chặng từ trạng thái %',v_trang_thai;
    END IF;
    SELECT c.id INTO v_chang_id
    FROM public.chuyen_xe_chang c
    WHERE c.chuyen_xe_id=p_chuyen_xe_id
      AND c.trang_thai='CHO_KHOI_HANH'
    ORDER BY c.thu_tu_chuyen
    LIMIT 1
    FOR UPDATE;
    IF v_chang_id IS NULL THEN RAISE EXCEPTION 'Chuyến không còn chặng chờ khởi hành'; END IF;
    IF NOT EXISTS(
      SELECT 1
      FROM public.niem_phong_xe np
      JOIN public.chuyen_xe_chang c ON c.id=v_chang_id
      WHERE np.chuyen_xe_id=p_chuyen_xe_id
        AND np.kho_niem_phong_id=c.kho_di_id
        AND np.trang_thai='DA_NIEM_PHONG'
    ) THEN
      RAISE EXCEPTION 'Xe phải được kho khởi hành niêm phong trước khi chạy chặng này';
    END IF;

    UPDATE public.chuyen_xe_chang
    SET trang_thai='DANG_DI',
        ngay_khoi_hanh=COALESCE(ngay_khoi_hanh,NOW()),
        ngay_cap_nhat=NOW()
    WHERE id=v_chang_id;
    UPDATE public.chuyen_xe
    SET trang_thai='DANG_DI',
        ngay_khoi_hanh=COALESCE(ngay_khoi_hanh,NOW()),
        ngay_cap_nhat=NOW()
    WHERE id=p_chuyen_xe_id;
    UPDATE public.xe SET trang_thai='DANG_CHAY',ngay_cap_nhat=NOW()
    WHERE id=v_xe_id;
    UPDATE public.chi_tiet_chuyen_xe SET trang_thai='DANG_VAN_CHUYEN'
    WHERE chuyen_xe_id=p_chuyen_xe_id AND trang_thai='DA_XEP_HANG';

  ELSIF p_trang_thai_moi='DA_DEN' THEN
    IF v_trang_thai<>'DANG_DI' THEN
      RAISE EXCEPTION 'Không thể xác nhận đến kho từ trạng thái %',v_trang_thai;
    END IF;
    SELECT c.id INTO v_chang_id
    FROM public.chuyen_xe_chang c
    WHERE c.chuyen_xe_id=p_chuyen_xe_id AND c.trang_thai='DANG_DI'
    ORDER BY c.thu_tu_chuyen
    LIMIT 1
    FOR UPDATE;
    IF v_chang_id IS NULL THEN RAISE EXCEPTION 'Không tìm thấy chặng đang di chuyển'; END IF;

    UPDATE public.chuyen_xe_chang
    SET trang_thai='DA_DEN',
        ngay_den_thuc_te=COALESCE(ngay_den_thuc_te,NOW()),
        ngay_cap_nhat=NOW()
    WHERE id=v_chang_id;
    SELECT EXISTS(
      SELECT 1 FROM public.chuyen_xe_chang c
      WHERE c.chuyen_xe_id=p_chuyen_xe_id AND c.trang_thai='CHO_KHOI_HANH'
    ) INTO v_con_chang_cho;
    UPDATE public.chuyen_xe
    SET trang_thai='DA_DEN',
        ngay_den_thuc_te=CASE WHEN v_con_chang_cho THEN ngay_den_thuc_te
          ELSE COALESCE(ngay_den_thuc_te,NOW()) END,
        ngay_cap_nhat=NOW()
    WHERE id=p_chuyen_xe_id;
    SELECT c.kho_den_id INTO v_kho_hien_tai_id
    FROM public.chuyen_xe_chang c WHERE c.id=v_chang_id;
    UPDATE public.xe
    SET kho_hien_tai_id=v_kho_hien_tai_id,ngay_cap_nhat=NOW()
    WHERE id=v_xe_id;

  ELSIF p_trang_thai_moi='DA_HOAN_THANH' THEN
    IF v_trang_thai<>'DA_DEN' THEN
      RAISE EXCEPTION 'Không thể hoàn thành chuyến từ trạng thái %',v_trang_thai;
    END IF;
    IF EXISTS(
      SELECT 1 FROM public.chuyen_xe_chang c
      WHERE c.chuyen_xe_id=p_chuyen_xe_id AND c.trang_thai<>'DA_DEN'
    ) THEN
      RAISE EXCEPTION 'Xe còn điểm dừng chưa hoàn thành';
    END IF;
    IF EXISTS(SELECT 1 FROM public.niem_phong_xe np
      WHERE np.chuyen_xe_id=p_chuyen_xe_id AND np.trang_thai='DA_NIEM_PHONG') THEN
      RAISE EXCEPTION 'Kho đến phải mở niêm phong trước khi hoàn thành chuyến';
    END IF;
    IF EXISTS(SELECT 1 FROM public.chi_tiet_chuyen_xe ct
      WHERE ct.chuyen_xe_id=p_chuyen_xe_id AND ct.da_quet_nhap_kho=FALSE) THEN
      RAISE EXCEPTION 'Kho đến chưa dỡ hết kiện hàng';
    END IF;
    UPDATE public.chuyen_xe
    SET trang_thai='DA_HOAN_THANH',
        ngay_den_thuc_te=COALESCE(ngay_den_thuc_te,NOW()),
        ngay_cap_nhat=NOW()
    WHERE id=p_chuyen_xe_id;
    SELECT c.kho_den_id INTO v_kho_hien_tai_id
    FROM public.chuyen_xe_chang c
    WHERE c.chuyen_xe_id=p_chuyen_xe_id AND c.trang_thai='DA_DEN'
    ORDER BY c.thu_tu_chuyen DESC LIMIT 1;
    UPDATE public.xe
    SET trang_thai='SAN_SANG',kho_hien_tai_id=v_kho_hien_tai_id,
        ngay_cap_nhat=NOW()
    WHERE id=v_xe_id;
    UPDATE public.chi_tiet_chuyen_xe
    SET trang_thai='DA_DO_HANG',ngay_do_hang=COALESCE(ngay_do_hang,NOW())
    WHERE chuyen_xe_id=p_chuyen_xe_id;
  ELSE
    RAISE EXCEPTION 'Trạng thái chuyến không hợp lệ';
  END IF;
END;
$$;

REVOKE ALL ON FUNCTION public.quan_ly_kho_danh_sach_xe(BIGINT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.quan_ly_kho_danh_sach_kho_den(BIGINT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.quan_ly_kho_chang_ve_mac_dinh(BIGINT,BIGINT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.quan_ly_kho_danh_sach_chuyen(BIGINT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.quan_ly_kho_gan_xe_tao_chuyen(BIGINT,BIGINT,BIGINT,TIMESTAMPTZ) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.quan_ly_kho_gan_xe_tao_tuyen(BIGINT,BIGINT[],BIGINT,TIMESTAMPTZ) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.cap_nhat_chuyen_xe_tai_xe(BIGINT,TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.chuyen_xe_cua_tai_xe_co_chang() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.nhan_vien_kho_tim_chuyen_theo_xe(TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.nhan_vien_kho_xac_nhan_do_xong(BIGINT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.nhan_vien_kho_quet_kien_chuyen(BIGINT,TEXT,TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.nhan_vien_kho_niem_phong_chuyen(BIGINT,TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.nhan_vien_kho_mo_niem_phong_chuyen(BIGINT,TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.quan_ly_kho_danh_sach_xe(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.quan_ly_kho_danh_sach_kho_den(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.quan_ly_kho_chang_ve_mac_dinh(BIGINT,BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.quan_ly_kho_danh_sach_chuyen(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.quan_ly_kho_gan_xe_tao_chuyen(BIGINT,BIGINT,BIGINT,TIMESTAMPTZ) TO authenticated;
GRANT EXECUTE ON FUNCTION public.quan_ly_kho_gan_xe_tao_tuyen(BIGINT,BIGINT[],BIGINT,TIMESTAMPTZ) TO authenticated;
GRANT EXECUTE ON FUNCTION public.cap_nhat_chuyen_xe_tai_xe(BIGINT,TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.chuyen_xe_cua_tai_xe_co_chang() TO authenticated;
GRANT EXECUTE ON FUNCTION public.nhan_vien_kho_tim_chuyen_theo_xe(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.nhan_vien_kho_xac_nhan_do_xong(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.nhan_vien_kho_quet_kien_chuyen(BIGINT,TEXT,TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.nhan_vien_kho_niem_phong_chuyen(BIGINT,TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.nhan_vien_kho_mo_niem_phong_chuyen(BIGINT,TEXT) TO authenticated;
NOTIFY pgrst,'reload schema';
