-- Chạy trong Supabase Dashboard > SQL Editor sau customer_orders_setup.sql.
-- Bán kính mặc định để shipper thấy/nhận đơn: 10 km.

ALTER TABLE public.nhan_vien
    ADD COLUMN IF NOT EXISTS auth_user_id UUID;

CREATE UNIQUE INDEX IF NOT EXISTS uq_nhan_vien_auth_user
    ON public.nhan_vien(auth_user_id)
    WHERE auth_user_id IS NOT NULL;

ALTER TABLE public.nhan_vien
    DROP CONSTRAINT IF EXISTS fk_nhan_vien_auth_user;
ALTER TABLE public.nhan_vien
    ADD CONSTRAINT fk_nhan_vien_auth_user
    FOREIGN KEY (auth_user_id)
    REFERENCES auth.users(id)
    ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS public.vi_tri_nhan_vien (
    nhan_vien_id BIGINT PRIMARY KEY
        REFERENCES public.nhan_vien(id) ON DELETE CASCADE,
    vi_do DOUBLE PRECISION NOT NULL CHECK (vi_do BETWEEN -90 AND 90),
    kinh_do DOUBLE PRECISION NOT NULL CHECK (kinh_do BETWEEN -180 AND 180),
    do_chinh_xac_met DOUBLE PRECISION,
    dang_truc_tuyen BOOLEAN NOT NULL DEFAULT TRUE,
    thoi_gian_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.don_hang
    ADD COLUMN IF NOT EXISTS thoi_gian_bat_dau_tim_shipper TIMESTAMPTZ;

ALTER TABLE public.don_hang
    ALTER COLUMN thoi_gian_bat_dau_tim_shipper SET DEFAULT NOW();

UPDATE public.don_hang
SET thoi_gian_bat_dau_tim_shipper = NOW()
WHERE trang_thai = 'CHO_LAY_HANG'
  AND phuong_tien = 'XE_MAY'
  AND nhan_vien_hien_tai_id IS NULL
  AND thoi_gian_bat_dau_tim_shipper IS NULL;

CREATE TABLE IF NOT EXISTS public.loi_moi_don_hang_shipper (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_hang_id BIGINT NOT NULL
        REFERENCES public.don_hang(id) ON DELETE CASCADE,
    nhan_vien_id BIGINT NOT NULL
        REFERENCES public.nhan_vien(id) ON DELETE CASCADE,
    trang_thai VARCHAR(20) NOT NULL DEFAULT 'DANG_MOI'
        CHECK (trang_thai IN ('DANG_MOI', 'DA_NHAN', 'TU_CHOI', 'HET_HAN')),
    moi_luc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    het_han_luc TIMESTAMPTZ NOT NULL DEFAULT NOW() + INTERVAL '30 seconds',
    phan_hoi_luc TIMESTAMPTZ,
    UNIQUE (don_hang_id, nhan_vien_id)
);

-- Dọn dữ liệu lời mời trùng từ phiên bản cũ trước khi tạo khóa duy nhất.
WITH loi_moi_xep_hang AS (
    SELECT id, ROW_NUMBER() OVER (
        PARTITION BY don_hang_id ORDER BY moi_luc, id
    ) AS thu_tu
    FROM public.loi_moi_don_hang_shipper
    WHERE trang_thai = 'DANG_MOI'
)
UPDATE public.loi_moi_don_hang_shipper lm
SET trang_thai = 'HET_HAN', phan_hoi_luc = NOW()
FROM loi_moi_xep_hang xh
WHERE lm.id = xh.id AND xh.thu_tu > 1;

WITH loi_moi_xep_hang AS (
    SELECT id, ROW_NUMBER() OVER (
        PARTITION BY nhan_vien_id ORDER BY moi_luc, id
    ) AS thu_tu
    FROM public.loi_moi_don_hang_shipper
    WHERE trang_thai = 'DANG_MOI'
)
UPDATE public.loi_moi_don_hang_shipper lm
SET trang_thai = 'HET_HAN', phan_hoi_luc = NOW()
FROM loi_moi_xep_hang xh
WHERE lm.id = xh.id AND xh.thu_tu > 1;

CREATE UNIQUE INDEX IF NOT EXISTS uq_loi_moi_dang_hoat_dong
    ON public.loi_moi_don_hang_shipper(don_hang_id)
    WHERE trang_thai = 'DANG_MOI';

CREATE UNIQUE INDEX IF NOT EXISTS uq_shipper_chi_co_mot_loi_moi
    ON public.loi_moi_don_hang_shipper(nhan_vien_id)
    WHERE trang_thai = 'DANG_MOI';

CREATE INDEX IF NOT EXISTS idx_loi_moi_shipper_dang_moi
    ON public.loi_moi_don_hang_shipper(nhan_vien_id, het_han_luc)
    WHERE trang_thai = 'DANG_MOI';

REVOKE ALL ON TABLE public.loi_moi_don_hang_shipper FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS public.tu_choi_don_hang_shipper (
    don_hang_id BIGINT NOT NULL
        REFERENCES public.don_hang(id) ON DELETE CASCADE,
    nhan_vien_id BIGINT NOT NULL
        REFERENCES public.nhan_vien(id) ON DELETE CASCADE,
    ly_do TEXT,
    thoi_gian_tu_choi TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (don_hang_id, nhan_vien_id)
);

CREATE TABLE IF NOT EXISTS public.luong_shipper (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nhan_vien_id BIGINT NOT NULL
        REFERENCES public.nhan_vien(id) ON DELETE RESTRICT,
    don_hang_id BIGINT NOT NULL UNIQUE
        REFERENCES public.don_hang(id) ON DELETE RESTRICT,
    phi_van_chuyen NUMERIC(14,2) NOT NULL CHECK (phi_van_chuyen >= 0),
    phan_tram_san NUMERIC(5,2) NOT NULL
        CHECK (phan_tram_san BETWEEN 0 AND 100),
    tien_san NUMERIC(14,2) NOT NULL CHECK (tien_san >= 0),
    tien_shipper NUMERIC(14,2) NOT NULL CHECK (tien_shipper >= 0),
    trang_thai VARCHAR(30) NOT NULL DEFAULT 'CHUA_THANH_TOAN'
        CHECK (trang_thai IN ('CHUA_THANH_TOAN', 'DA_THANH_TOAN')),
    ngay_ghi_nhan TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ngay_thanh_toan TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_luong_shipper_nhan_vien
    ON public.luong_shipper(nhan_vien_id, ngay_ghi_nhan DESC);

-- Dọn các đơn nhận trùng từ phiên bản cũ. Ưu tiên đơn đã lấy/đang giao;
-- các đơn còn CHO_LAY_HANG được trả về hàng chờ cho shipper khác.
UPDATE public.don_hang cho_lay
SET nhan_vien_hien_tai_id = NULL
WHERE cho_lay.trang_thai = 'CHO_LAY_HANG'
  AND cho_lay.nhan_vien_hien_tai_id IS NOT NULL
  AND EXISTS (
      SELECT 1 FROM public.don_hang dang_giao
      WHERE dang_giao.nhan_vien_hien_tai_id = cho_lay.nhan_vien_hien_tai_id
        AND dang_giao.id <> cho_lay.id
        AND dang_giao.trang_thai IN (
            'DA_LAY_HANG', 'GIAO_CHO_SHIPPER', 'DANG_GIAO_HANG'
        )
  );

WITH xep_hang AS (
    SELECT id, ROW_NUMBER() OVER (
        PARTITION BY nhan_vien_hien_tai_id ORDER BY ngay_tao, id
    ) AS thu_tu
    FROM public.don_hang
    WHERE nhan_vien_hien_tai_id IS NOT NULL
      AND trang_thai = 'CHO_LAY_HANG'
)
UPDATE public.don_hang dh
SET nhan_vien_hien_tai_id = NULL
FROM xep_hang xh
WHERE dh.id = xh.id AND xh.thu_tu > 1;

REVOKE ALL ON TABLE public.luong_shipper FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.khoang_cach_km(
    p_vi_do_1 DOUBLE PRECISION,
    p_kinh_do_1 DOUBLE PRECISION,
    p_vi_do_2 DOUBLE PRECISION,
    p_kinh_do_2 DOUBLE PRECISION
)
RETURNS DOUBLE PRECISION
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $$
    SELECT 6371 * 2 * ASIN(
        SQRT(
            POWER(SIN(RADIANS(p_vi_do_2 - p_vi_do_1) / 2), 2)
            + COS(RADIANS(p_vi_do_1)) * COS(RADIANS(p_vi_do_2))
            * POWER(SIN(RADIANS(p_kinh_do_2 - p_kinh_do_1) / 2), 2)
        )
    );
$$;

CREATE OR REPLACE FUNCTION public.cap_nhat_vi_tri_shipper(
    p_vi_do DOUBLE PRECISION,
    p_kinh_do DOUBLE PRECISION,
    p_do_chinh_xac_met DOUBLE PRECISION DEFAULT NULL
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_nhan_vien_id BIGINT;
BEGIN
    SELECT nv.id INTO v_nhan_vien_id
    FROM public.nhan_vien nv
    WHERE nv.auth_user_id = auth.uid()
      AND nv.vai_tro = 'SHIPPER'
      AND nv.trang_thai = 'HOAT_DONG'
      AND nv.trang_thai_duyet = 'DA_DUYET';

    IF v_nhan_vien_id IS NULL THEN
        RAISE EXCEPTION 'Tài khoản không phải shipper đã được duyệt';
    END IF;

    INSERT INTO public.vi_tri_nhan_vien (
        nhan_vien_id, vi_do, kinh_do, do_chinh_xac_met,
        dang_truc_tuyen, thoi_gian_cap_nhat
    ) VALUES (
        v_nhan_vien_id, p_vi_do, p_kinh_do, p_do_chinh_xac_met,
        TRUE, NOW()
    )
    ON CONFLICT (nhan_vien_id) DO UPDATE SET
        vi_do = EXCLUDED.vi_do,
        kinh_do = EXCLUDED.kinh_do,
        do_chinh_xac_met = EXCLUDED.do_chinh_xac_met,
        dang_truc_tuyen = TRUE,
        thoi_gian_cap_nhat = NOW();
END;
$$;

CREATE OR REPLACE FUNCTION public.xu_ly_phan_don_shipper()
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_don RECORD;
    v_nhan_vien_id BIGINT;
BEGIN
    -- Mọi lời gọi phân đơn chạy tuần tự để hai thiết bị không thể đồng thời
    -- mời hai shipper cho cùng một đơn hoặc mời một shipper nhiều đơn.
    PERFORM pg_advisory_xact_lock(982451653);

    -- Lời mời quá 30 giây được đóng để chọn người tiếp theo.
    UPDATE public.loi_moi_don_hang_shipper
    SET trang_thai = 'HET_HAN', phan_hoi_luc = NOW()
    WHERE trang_thai = 'DANG_MOI' AND het_han_luc <= NOW();

    -- Sau tổng cộng 5 phút vẫn chưa ai nhận thì hủy và báo khách đặt lại.
    UPDATE public.don_hang dh
    SET trang_thai = 'DA_HUY',
        ghi_chu = CONCAT_WS(
            E'\n', NULLIF(BTRIM(dh.ghi_chu), ''),
            'Hệ thống hủy: không tìm thấy shipper trong vòng 5 phút. Vui lòng đặt lại đơn.'
        ),
        ngay_cap_nhat = NOW()
    WHERE dh.trang_thai = 'CHO_LAY_HANG'
      AND dh.phuong_tien = 'XE_MAY'
      AND dh.nhan_vien_hien_tai_id IS NULL
      AND dh.thoi_gian_bat_dau_tim_shipper <= NOW() - INTERVAL '5 minutes';

    UPDATE public.loi_moi_don_hang_shipper lm
    SET trang_thai = 'HET_HAN', phan_hoi_luc = NOW()
    FROM public.don_hang dh
    WHERE dh.id = lm.don_hang_id
      AND dh.trang_thai = 'DA_HUY'
      AND lm.trang_thai = 'DANG_MOI';

    FOR v_don IN
        SELECT dh.id, dh.nguoi_gui_vi_do, dh.nguoi_gui_kinh_do
        FROM public.don_hang dh
        WHERE dh.trang_thai = 'CHO_LAY_HANG'
          AND dh.phuong_tien = 'XE_MAY'
          AND dh.nhan_vien_hien_tai_id IS NULL
          AND dh.thoi_gian_bat_dau_tim_shipper > NOW() - INTERVAL '5 minutes'
          AND NOT EXISTS (
              SELECT 1 FROM public.loi_moi_don_hang_shipper lm
              WHERE lm.don_hang_id = dh.id AND lm.trang_thai = 'DANG_MOI'
          )
        ORDER BY dh.thoi_gian_bat_dau_tim_shipper, dh.id
        FOR UPDATE OF dh SKIP LOCKED
    LOOP
        SELECT nv.id INTO v_nhan_vien_id
        FROM public.nhan_vien nv
        JOIN public.vi_tri_nhan_vien vt ON vt.nhan_vien_id = nv.id
        WHERE nv.vai_tro = 'SHIPPER'
          AND nv.trang_thai = 'HOAT_DONG'
          AND nv.trang_thai_duyet = 'DA_DUYET'
          AND vt.dang_truc_tuyen = TRUE
          AND vt.thoi_gian_cap_nhat >= NOW() - INTERVAL '15 minutes'
          AND public.khoang_cach_km(
              vt.vi_do, vt.kinh_do,
              v_don.nguoi_gui_vi_do, v_don.nguoi_gui_kinh_do
          ) <= 10
          AND NOT EXISTS (
              SELECT 1 FROM public.don_hang dang_giao
              WHERE dang_giao.nhan_vien_hien_tai_id = nv.id
                AND dang_giao.trang_thai IN (
                    'CHO_LAY_HANG', 'DA_LAY_HANG',
                    'GIAO_CHO_SHIPPER', 'DANG_GIAO_HANG'
                )
          )
          AND NOT EXISTS (
              SELECT 1 FROM public.loi_moi_don_hang_shipper cu
              WHERE cu.don_hang_id = v_don.id AND cu.nhan_vien_id = nv.id
          )
          AND NOT EXISTS (
              SELECT 1 FROM public.loi_moi_don_hang_shipper dang_moi
              WHERE dang_moi.nhan_vien_id = nv.id
                AND dang_moi.trang_thai = 'DANG_MOI'
                AND dang_moi.het_han_luc > NOW()
          )
        ORDER BY public.khoang_cach_km(
            vt.vi_do, vt.kinh_do,
            v_don.nguoi_gui_vi_do, v_don.nguoi_gui_kinh_do
        ), vt.thoi_gian_cap_nhat DESC
        LIMIT 1;

        IF v_nhan_vien_id IS NOT NULL THEN
            INSERT INTO public.loi_moi_don_hang_shipper(
                don_hang_id, nhan_vien_id, het_han_luc
            ) VALUES (
                v_don.id, v_nhan_vien_id, NOW() + INTERVAL '30 seconds'
            ) ON CONFLICT (don_hang_id, nhan_vien_id) DO NOTHING;
        END IF;
    END LOOP;
END;
$$;

DROP FUNCTION IF EXISTS public.don_hang_gan_shipper(DOUBLE PRECISION);

CREATE OR REPLACE FUNCTION public.don_hang_gan_shipper(
    p_ban_kinh_km DOUBLE PRECISION DEFAULT 10
)
RETURNS TABLE (
    id BIGINT,
    ma_van_don VARCHAR,
    nguoi_gui_ten VARCHAR,
    nguoi_gui_sdt VARCHAR,
    nguoi_gui_dia_chi TEXT,
    nguoi_nhan_ten VARCHAR,
    nguoi_nhan_sdt VARCHAR,
    nguoi_nhan_dia_chi TEXT,
    nguoi_gui_vi_do DOUBLE PRECISION,
    nguoi_gui_kinh_do DOUBLE PRECISION,
    nguoi_nhan_vi_do DOUBLE PRECISION,
    nguoi_nhan_kinh_do DOUBLE PRECISION,
    can_nang NUMERIC,
    cod NUMERIC,
    phi_van_chuyen NUMERIC,
    tien_shipper_du_kien NUMERIC,
    khoang_cach_den_diem_lay_km DOUBLE PRECISION,
    loi_moi_het_han_luc TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_nhan_vien_id BIGINT;
    v_vi_do DOUBLE PRECISION;
    v_kinh_do DOUBLE PRECISION;
BEGIN
    PERFORM public.xu_ly_phan_don_shipper();
    SELECT nv.id, vt.vi_do, vt.kinh_do
    INTO v_nhan_vien_id, v_vi_do, v_kinh_do
    FROM public.nhan_vien nv
    JOIN public.vi_tri_nhan_vien vt ON vt.nhan_vien_id = nv.id
    WHERE nv.auth_user_id = auth.uid()
      AND nv.vai_tro = 'SHIPPER'
      AND nv.trang_thai = 'HOAT_DONG'
      AND nv.trang_thai_duyet = 'DA_DUYET'
      AND vt.dang_truc_tuyen = TRUE
      AND vt.thoi_gian_cap_nhat >= NOW() - INTERVAL '15 minutes';

    IF v_nhan_vien_id IS NULL THEN
        RAISE EXCEPTION 'Vui lòng cập nhật vị trí hiện tại trước';
    END IF;

    -- Shipper đang có đơn thì không trả thêm danh sách đơn có thể nhận.
    IF EXISTS (
        SELECT 1 FROM public.don_hang dang_giao
        WHERE dang_giao.nhan_vien_hien_tai_id = v_nhan_vien_id
          AND dang_giao.trang_thai IN (
              'CHO_LAY_HANG', 'DA_LAY_HANG',
              'GIAO_CHO_SHIPPER', 'DANG_GIAO_HANG'
          )
    ) THEN
        RETURN;
    END IF;

    RETURN QUERY
    SELECT
        dh.id,
        dh.ma_van_don,
        dh.nguoi_gui_ten,
        dh.nguoi_gui_sdt,
        dh.nguoi_gui_dia_chi,
        dh.nguoi_nhan_ten,
        dh.nguoi_nhan_sdt,
        dh.nguoi_nhan_dia_chi,
        dh.nguoi_gui_vi_do,
        dh.nguoi_gui_kinh_do,
        dh.nguoi_nhan_vi_do,
        dh.nguoi_nhan_kinh_do,
        dh.can_nang,
        dh.cod,
        dh.phi_van_chuyen,
        ROUND(
            dh.phi_van_chuyen *
            (100 - COALESCE((
                SELECT pvc.phan_tram_san
                FROM public.phi_van_chuyen pvc
                WHERE pvc.id = 1
            ), 20)) / 100,
            0
        ),
        public.khoang_cach_km(
            v_vi_do, v_kinh_do,
            dh.nguoi_gui_vi_do, dh.nguoi_gui_kinh_do
        ) AS khoang_cach_den_diem_lay_km,
        lm.het_han_luc
    FROM public.don_hang dh
    JOIN public.loi_moi_don_hang_shipper lm
      ON lm.don_hang_id = dh.id
     AND lm.nhan_vien_id = v_nhan_vien_id
     AND lm.trang_thai = 'DANG_MOI'
     AND lm.het_han_luc > NOW()
    WHERE dh.trang_thai = 'CHO_LAY_HANG'
      AND dh.phuong_tien = 'XE_MAY'
      AND dh.nhan_vien_hien_tai_id IS NULL
      AND dh.nguoi_gui_vi_do IS NOT NULL
      AND dh.nguoi_gui_kinh_do IS NOT NULL
      AND NOT EXISTS (
          SELECT 1
          FROM public.tu_choi_don_hang_shipper tc
          WHERE tc.don_hang_id = dh.id
            AND tc.nhan_vien_id = v_nhan_vien_id
      )
      AND public.khoang_cach_km(
          v_vi_do, v_kinh_do,
          dh.nguoi_gui_vi_do, dh.nguoi_gui_kinh_do
      ) <= p_ban_kinh_km
    ORDER BY khoang_cach_den_diem_lay_km, dh.ngay_tao;
END;
$$;

CREATE OR REPLACE FUNCTION public.tu_choi_don_hang_gan(
    p_don_hang_id BIGINT,
    p_ly_do TEXT DEFAULT NULL
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_nhan_vien_id BIGINT;
    v_da_tu_choi INTEGER;
BEGIN
    SELECT nv.id INTO v_nhan_vien_id
    FROM public.nhan_vien nv
    WHERE nv.auth_user_id = auth.uid()
      AND nv.vai_tro = 'SHIPPER'
      AND nv.trang_thai = 'HOAT_DONG'
      AND nv.trang_thai_duyet = 'DA_DUYET';

    IF v_nhan_vien_id IS NULL THEN
        RAISE EXCEPTION 'Tài khoản không phải shipper đã được duyệt';
    END IF;

    UPDATE public.loi_moi_don_hang_shipper
    SET trang_thai = 'TU_CHOI', phan_hoi_luc = NOW()
    WHERE don_hang_id = p_don_hang_id
      AND nhan_vien_id = v_nhan_vien_id
      AND trang_thai = 'DANG_MOI'
      AND het_han_luc > NOW();

    GET DIAGNOSTICS v_da_tu_choi = ROW_COUNT;
    IF v_da_tu_choi = 0 THEN
        PERFORM public.xu_ly_phan_don_shipper();
        RETURN;
    END IF;

    INSERT INTO public.tu_choi_don_hang_shipper (
        don_hang_id, nhan_vien_id, ly_do
    ) VALUES (
        p_don_hang_id, v_nhan_vien_id, NULLIF(TRIM(p_ly_do), '')
    )
    ON CONFLICT (don_hang_id, nhan_vien_id) DO UPDATE SET
        ly_do = EXCLUDED.ly_do,
        thoi_gian_tu_choi = NOW();

    PERFORM public.xu_ly_phan_don_shipper();
END;
$$;

DROP FUNCTION IF EXISTS public.don_hang_dang_giao_cua_shipper();

CREATE OR REPLACE FUNCTION public.don_hang_dang_giao_cua_shipper()
RETURNS TABLE (
    id BIGINT,
    ma_van_don VARCHAR,
    trang_thai VARCHAR,
    nguoi_gui_ten VARCHAR,
    nguoi_gui_sdt VARCHAR,
    nguoi_gui_dia_chi TEXT,
    nguoi_nhan_ten VARCHAR,
    nguoi_nhan_sdt VARCHAR,
    nguoi_nhan_dia_chi TEXT,
    nguoi_gui_vi_do DOUBLE PRECISION,
    nguoi_gui_kinh_do DOUBLE PRECISION,
    nguoi_nhan_vi_do DOUBLE PRECISION,
    nguoi_nhan_kinh_do DOUBLE PRECISION,
    can_nang NUMERIC,
    cod NUMERIC,
    phi_van_chuyen NUMERIC,
    tien_shipper_du_kien NUMERIC
)
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
    SELECT
        dh.id,
        dh.ma_van_don,
        dh.trang_thai,
        dh.nguoi_gui_ten,
        dh.nguoi_gui_sdt,
        dh.nguoi_gui_dia_chi,
        dh.nguoi_nhan_ten,
        dh.nguoi_nhan_sdt,
        dh.nguoi_nhan_dia_chi,
        dh.nguoi_gui_vi_do,
        dh.nguoi_gui_kinh_do,
        dh.nguoi_nhan_vi_do,
        dh.nguoi_nhan_kinh_do,
        dh.can_nang,
        dh.cod,
        dh.phi_van_chuyen,
        ROUND(
            dh.phi_van_chuyen *
            (100 - COALESCE((
                SELECT pvc.phan_tram_san
                FROM public.phi_van_chuyen pvc
                WHERE pvc.id = 1
            ), 20)) / 100,
            0
        )
    FROM public.don_hang dh
    JOIN public.nhan_vien nv
      ON nv.id = dh.nhan_vien_hien_tai_id
    WHERE nv.auth_user_id = auth.uid()
      AND dh.trang_thai IN (
          'CHO_LAY_HANG', 'DA_LAY_HANG', 'GIAO_CHO_SHIPPER', 'DANG_GIAO_HANG'
      )
    ORDER BY dh.ngay_tao DESC;
$$;

CREATE OR REPLACE FUNCTION public.nhan_don_hang_gan(
    p_don_hang_id BIGINT,
    p_ban_kinh_km DOUBLE PRECISION DEFAULT 10
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_nhan_vien_id BIGINT;
    v_vi_do DOUBLE PRECISION;
    v_kinh_do DOUBLE PRECISION;
    v_don public.don_hang%ROWTYPE;
    v_khoang_cach DOUBLE PRECISION;
BEGIN
    SELECT nv.id, vt.vi_do, vt.kinh_do
    INTO v_nhan_vien_id, v_vi_do, v_kinh_do
    FROM public.nhan_vien nv
    JOIN public.vi_tri_nhan_vien vt ON vt.nhan_vien_id = nv.id
    WHERE nv.auth_user_id = auth.uid()
      AND nv.vai_tro = 'SHIPPER'
      AND nv.trang_thai = 'HOAT_DONG'
      AND nv.trang_thai_duyet = 'DA_DUYET'
      AND vt.dang_truc_tuyen = TRUE
      AND vt.thoi_gian_cap_nhat >= NOW() - INTERVAL '15 minutes';

    IF v_nhan_vien_id IS NULL THEN
        RAISE EXCEPTION 'Vui lòng cập nhật vị trí hiện tại trước';
    END IF;

    -- Khóa giao dịch theo shipper để hai request nhận đơn đồng thời
    -- không thể cùng vượt qua bước kiểm tra bên dưới.
    PERFORM pg_advisory_xact_lock(v_nhan_vien_id);

    IF EXISTS (
        SELECT 1 FROM public.don_hang dang_giao
        WHERE dang_giao.nhan_vien_hien_tai_id = v_nhan_vien_id
          AND dang_giao.trang_thai IN (
              'CHO_LAY_HANG', 'DA_LAY_HANG',
              'GIAO_CHO_SHIPPER', 'DANG_GIAO_HANG'
          )
    ) THEN
        RAISE EXCEPTION
            'Bạn đang có một đơn chưa hoàn thành. Hãy giao xong trước khi nhận đơn mới';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM public.loi_moi_don_hang_shipper lm
        WHERE lm.don_hang_id = p_don_hang_id
          AND lm.nhan_vien_id = v_nhan_vien_id
          AND lm.trang_thai = 'DANG_MOI'
          AND lm.het_han_luc > NOW()
    ) THEN
        RAISE EXCEPTION
            'Lời mời nhận đơn đã hết 30 giây. Đơn đang được chuyển cho shipper khác';
    END IF;

    SELECT * INTO v_don
    FROM public.don_hang
    WHERE don_hang.id = p_don_hang_id
    FOR UPDATE;

    IF NOT FOUND OR v_don.trang_thai <> 'CHO_LAY_HANG'
       OR v_don.nhan_vien_hien_tai_id IS NOT NULL
       OR v_don.phuong_tien <> 'XE_MAY' THEN
        RAISE EXCEPTION 'Đơn hàng không còn khả dụng';
    END IF;

    v_khoang_cach := public.khoang_cach_km(
        v_vi_do, v_kinh_do,
        v_don.nguoi_gui_vi_do, v_don.nguoi_gui_kinh_do
    );

    IF v_khoang_cach > p_ban_kinh_km THEN
        RAISE EXCEPTION 'Điểm lấy hàng nằm ngoài bán kính cho phép';
    END IF;

    UPDATE public.don_hang
    SET nhan_vien_hien_tai_id = v_nhan_vien_id
    WHERE don_hang.id = p_don_hang_id;

    UPDATE public.loi_moi_don_hang_shipper
    SET trang_thai = 'DA_NHAN', phan_hoi_luc = NOW()
    WHERE don_hang_id = p_don_hang_id
      AND nhan_vien_id = v_nhan_vien_id
      AND trang_thai = 'DANG_MOI';

    INSERT INTO public.nhat_ky_don_hang (
        nhan_vien_id, don_hang_id, khach_hang_id,
        hanh_dong, trang_thai_cu, trang_thai_moi,
        ghi_chu, vi_do, kinh_do
    ) VALUES (
        v_nhan_vien_id, v_don.id, v_don.khach_hang_id,
        'Shipper đã nhận đơn gần vị trí hiện tại',
        v_don.trang_thai, v_don.trang_thai,
        'Khoảng cách đến điểm lấy: ' || ROUND(v_khoang_cach::NUMERIC, 2) || ' km',
        v_vi_do, v_kinh_do
    );

    RETURN TRUE;
END;
$$;

DROP FUNCTION IF EXISTS public.cap_nhat_chang_giao_shipper(
    BIGINT, TEXT, DOUBLE PRECISION, DOUBLE PRECISION
);

CREATE OR REPLACE FUNCTION public.cap_nhat_chang_giao_shipper(
    p_don_hang_id BIGINT,
    p_trang_thai_moi TEXT,
    p_vi_do DOUBLE PRECISION DEFAULT NULL,
    p_kinh_do DOUBLE PRECISION DEFAULT NULL,
    p_minh_chung TEXT DEFAULT NULL
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_nhan_vien_id BIGINT;
    v_don public.don_hang%ROWTYPE;
    v_trang_thai_moi TEXT := UPPER(BTRIM(p_trang_thai_moi));
    v_phan_tram_san NUMERIC;
    v_tien_san NUMERIC;
    v_tien_shipper NUMERIC;
BEGIN
    SELECT nv.id INTO v_nhan_vien_id
    FROM public.nhan_vien nv
    WHERE nv.auth_user_id = auth.uid()
      AND nv.vai_tro = 'SHIPPER'
      AND nv.trang_thai = 'HOAT_DONG'
      AND nv.trang_thai_duyet = 'DA_DUYET';

    SELECT * INTO v_don
    FROM public.don_hang dh
    WHERE dh.id = p_don_hang_id
    FOR UPDATE;

    IF v_nhan_vien_id IS NULL OR NOT FOUND
       OR v_don.nhan_vien_hien_tai_id IS DISTINCT FROM v_nhan_vien_id THEN
        RAISE EXCEPTION 'Bạn không được phân công giao đơn hàng này';
    END IF;

    IF v_trang_thai_moi = 'DA_LAY_HANG'
       AND v_don.trang_thai = 'CHO_LAY_HANG' THEN
        IF p_minh_chung IS NULL OR BTRIM(p_minh_chung) = '' THEN
            RAISE EXCEPTION 'Phải có ảnh minh chứng khi xác nhận đã lấy hàng';
        END IF;
        UPDATE public.don_hang
        SET trang_thai = 'DA_LAY_HANG', ngay_lay_hang = NOW()
    WHERE id = p_don_hang_id;

    UPDATE public.loi_moi_don_hang_shipper
    SET trang_thai = 'DA_NHAN', phan_hoi_luc = NOW()
    WHERE don_hang_id = p_don_hang_id
      AND nhan_vien_id = v_nhan_vien_id
      AND trang_thai = 'DANG_MOI';
    ELSIF v_trang_thai_moi = 'DA_GIAO_HANG'
       AND v_don.trang_thai IN ('DA_LAY_HANG', 'DANG_GIAO_HANG') THEN
        IF p_minh_chung IS NULL OR BTRIM(p_minh_chung) = '' THEN
            RAISE EXCEPTION 'Phải có ảnh minh chứng khi xác nhận đã giao hàng';
        END IF;

        -- Chỉ khấu trừ COD khi xác nhận giao thành công. Nếu ví không đủ,
        -- toàn bộ giao dịch dừng và trạng thái đơn không bị thay đổi.
        PERFORM public.tam_giu_cod_vi_shipper(
            v_nhan_vien_id,
            v_don.id,
            COALESCE(v_don.cod, 0)
        );

        UPDATE public.don_hang
        SET trang_thai = 'DA_GIAO_HANG', ngay_giao_hang = NOW()
        WHERE id = p_don_hang_id;

        SELECT pvc.phan_tram_san
        INTO v_phan_tram_san
        FROM public.phi_van_chuyen pvc
        WHERE pvc.id = 1;

        IF v_phan_tram_san IS NULL THEN
            RAISE EXCEPTION 'Chưa cấu hình phần trăm phí sàn';
        END IF;

        v_tien_san := ROUND(
            COALESCE(v_don.phi_van_chuyen, 0) * v_phan_tram_san / 100,
            0
        );
        v_tien_shipper := COALESCE(v_don.phi_van_chuyen, 0) - v_tien_san;

        INSERT INTO public.luong_shipper (
            nhan_vien_id, don_hang_id, phi_van_chuyen,
            phan_tram_san, tien_san, tien_shipper,
            trang_thai, ngay_thanh_toan
        ) VALUES (
            v_nhan_vien_id, v_don.id, COALESCE(v_don.phi_van_chuyen, 0),
            v_phan_tram_san, v_tien_san, v_tien_shipper,
            'DA_THANH_TOAN', NOW()
        )
        ON CONFLICT (don_hang_id) DO NOTHING;

        PERFORM public.cong_thu_nhap_vi_shipper(
            v_nhan_vien_id,
            v_don.id,
            v_tien_shipper
        );
    ELSE
        RAISE EXCEPTION 'Không thể chuyển từ trạng thái % sang %',
            v_don.trang_thai, v_trang_thai_moi;
    END IF;

    INSERT INTO public.nhat_ky_don_hang (
        nhan_vien_id, don_hang_id, khach_hang_id,
        hanh_dong, trang_thai_cu, trang_thai_moi,
        ghi_chu, minh_chung, vi_do, kinh_do
    ) VALUES (
        v_nhan_vien_id, v_don.id, v_don.khach_hang_id,
        CASE v_trang_thai_moi
            WHEN 'DA_LAY_HANG' THEN 'Shipper đã lấy hàng'
            ELSE 'Shipper đã giao hàng thành công'
        END,
        v_don.trang_thai, v_trang_thai_moi,
        CASE v_trang_thai_moi
            WHEN 'DA_LAY_HANG' THEN
                'Địa chỉ minh chứng: ' || v_don.nguoi_gui_dia_chi
            ELSE
                'Địa chỉ minh chứng: ' || v_don.nguoi_nhan_dia_chi
        END,
        NULLIF(BTRIM(p_minh_chung), ''), p_vi_do, p_kinh_do
    );
END;
$$;

REVOKE ALL ON FUNCTION public.cap_nhat_vi_tri_shipper(
    DOUBLE PRECISION, DOUBLE PRECISION, DOUBLE PRECISION
) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.don_hang_gan_shipper(
    DOUBLE PRECISION
) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.nhan_don_hang_gan(
    BIGINT, DOUBLE PRECISION
) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tu_choi_don_hang_gan(
    BIGINT, TEXT
) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.cap_nhat_chang_giao_shipper(
    BIGINT, TEXT, DOUBLE PRECISION, DOUBLE PRECISION, TEXT
) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.don_hang_dang_giao_cua_shipper() FROM PUBLIC;

-- Khách hàng theo dõi shipper của chính đơn hàng mình theo tuyến đường bộ.
DROP FUNCTION IF EXISTS public.theo_doi_don_hang_khach_hang(BIGINT);

CREATE OR REPLACE FUNCTION public.theo_doi_don_hang_khach_hang(
    p_don_hang_id BIGINT
)
RETURNS TABLE (
    don_hang_id BIGINT,
    ma_van_don VARCHAR,
    trang_thai VARCHAR,
    nguoi_gui_dia_chi TEXT,
    nguoi_nhan_dia_chi TEXT,
    shipper_ten VARCHAR,
    shipper_sdt VARCHAR,
    shipper_vi_do DOUBLE PRECISION,
    shipper_kinh_do DOUBLE PRECISION,
    vi_tri_cap_nhat_luc TIMESTAMPTZ,
    diem_den_vi_do DOUBLE PRECISION,
    diem_den_kinh_do DOUBLE PRECISION,
    diem_den_dia_chi TEXT
)
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
    SELECT
        dh.id, dh.ma_van_don, dh.trang_thai,
        dh.nguoi_gui_dia_chi, dh.nguoi_nhan_dia_chi,
        nv.ho_ten, nv.so_dien_thoai,
        vt.vi_do, vt.kinh_do, vt.thoi_gian_cap_nhat,
        CASE
            WHEN dh.trang_thai IN ('DA_LAY_HANG', 'GIAO_CHO_SHIPPER', 'DANG_GIAO_HANG')
                THEN dh.nguoi_nhan_vi_do
            ELSE dh.nguoi_gui_vi_do
        END,
        CASE
            WHEN dh.trang_thai IN ('DA_LAY_HANG', 'GIAO_CHO_SHIPPER', 'DANG_GIAO_HANG')
                THEN dh.nguoi_nhan_kinh_do
            ELSE dh.nguoi_gui_kinh_do
        END,
        CASE
            WHEN dh.trang_thai IN ('DA_LAY_HANG', 'GIAO_CHO_SHIPPER', 'DANG_GIAO_HANG')
                THEN dh.nguoi_nhan_dia_chi
            ELSE dh.nguoi_gui_dia_chi
        END
    FROM public.don_hang dh
    JOIN public.khach_hang kh ON kh.id = dh.khach_hang_id
    LEFT JOIN public.nhan_vien nv ON nv.id = dh.nhan_vien_hien_tai_id
    LEFT JOIN public.vi_tri_nhan_vien vt ON vt.nhan_vien_id = nv.id
    WHERE dh.id = p_don_hang_id
      AND kh.auth_user_id = auth.uid();
$$;

REVOKE ALL ON FUNCTION public.theo_doi_don_hang_khach_hang(BIGINT)
FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.cap_nhat_vi_tri_shipper(
    DOUBLE PRECISION, DOUBLE PRECISION, DOUBLE PRECISION
) TO authenticated;
GRANT EXECUTE ON FUNCTION public.don_hang_gan_shipper(
    DOUBLE PRECISION
) TO authenticated;
GRANT EXECUTE ON FUNCTION public.nhan_don_hang_gan(
    BIGINT, DOUBLE PRECISION
) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tu_choi_don_hang_gan(
    BIGINT, TEXT
) TO authenticated;
GRANT EXECUTE ON FUNCTION public.cap_nhat_chang_giao_shipper(
    BIGINT, TEXT, DOUBLE PRECISION, DOUBLE PRECISION, TEXT
) TO authenticated;
GRANT EXECUTE ON FUNCTION public.don_hang_dang_giao_cua_shipper()
TO authenticated;
GRANT EXECUTE ON FUNCTION public.theo_doi_don_hang_khach_hang(BIGINT)
TO authenticated;

-- Chạy nền để hết 30 giây tự chuyển người và hết 5 phút tự hủy,
-- kể cả khi shipper không mở màn hình tìm đơn.
CREATE EXTENSION IF NOT EXISTS pg_cron;

DO $$
DECLARE
    v_job_id BIGINT;
BEGIN
    SELECT jobid INTO v_job_id
    FROM cron.job
    WHERE jobname = 'vinexpress-phan-don-5-giay';

    IF v_job_id IS NOT NULL THEN
        PERFORM cron.unschedule(v_job_id);
    END IF;

    PERFORM cron.schedule(
        'vinexpress-phan-don-5-giay',
        '5 seconds',
        'SELECT public.xu_ly_phan_don_shipper();'
    );
END;
$$;

-- Yêu cầu PostgREST nạp ngay chữ ký RPC mới có tham số p_minh_chung.
NOTIFY pgrst, 'reload schema';
