-- ============================================================
-- GHI NHẬN LƯƠNG SHIPPER KHI ĐƠN GIAO THÀNH CÔNG
-- Chạy sau customer_orders_setup.sql.
-- ============================================================

ALTER TABLE public.phi_van_chuyen
    ADD COLUMN IF NOT EXISTS phan_tram_san NUMERIC(5,2)
        NOT NULL DEFAULT 20 CHECK (phan_tram_san BETWEEN 0 AND 100);

-- Luôn bảo đảm có một dòng cấu hình phí mặc định.
INSERT INTO public.phi_van_chuyen (
    id,
    phi_van_chuyen,
    phan_tram_san,
    ngay_cap_nhat
) VALUES (
    1,
    5000,
    20,
    NOW()
)
ON CONFLICT (id) DO UPDATE SET
    phi_van_chuyen = COALESCE(public.phi_van_chuyen.phi_van_chuyen, 5000),
    phan_tram_san = COALESCE(public.phi_van_chuyen.phan_tram_san, 20);

CREATE TABLE IF NOT EXISTS public.luong_shipper (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nhan_vien_id BIGINT NOT NULL
        REFERENCES public.nhan_vien(id) ON DELETE RESTRICT,
    don_hang_id BIGINT NOT NULL UNIQUE
        REFERENCES public.don_hang(id) ON DELETE RESTRICT,
    phi_van_chuyen NUMERIC(14,2) NOT NULL CHECK (phi_van_chuyen >= 0),
    phan_tram_san NUMERIC(5,2) NOT NULL
        CHECK (phan_tram_san BETWEEN 0 AND 100),
    tien_san NUMERIC(14,2) NOT NULL CHECK (tien_san >= 0),
    tien_shipper NUMERIC(14,2) NOT NULL CHECK (tien_shipper >= 0),
    trang_thai VARCHAR(30) NOT NULL DEFAULT 'CHUA_THANH_TOAN'
        CHECK (trang_thai IN ('CHUA_THANH_TOAN', 'DA_THANH_TOAN')),
    ngay_ghi_nhan TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ngay_thanh_toan TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_luong_shipper_nhan_vien
    ON public.luong_shipper(nhan_vien_id, ngay_ghi_nhan DESC);

CREATE OR REPLACE FUNCTION public.tu_dong_ghi_luong_shipper()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_phan_tram_san NUMERIC;
    v_tien_san NUMERIC;
    v_tien_shipper NUMERIC;
BEGIN
    IF NEW.trang_thai <> 'DA_GIAO_HANG'
       OR OLD.trang_thai = 'DA_GIAO_HANG' THEN
        RETURN NEW;
    END IF;

    IF NEW.nhan_vien_hien_tai_id IS NULL THEN
        RAISE EXCEPTION 'Đơn giao thành công chưa có shipper phụ trách';
    END IF;

    SELECT pvc.phan_tram_san
    INTO v_phan_tram_san
    FROM public.phi_van_chuyen pvc
    WHERE pvc.id = 1;

    IF v_phan_tram_san IS NULL THEN
        RAISE EXCEPTION 'Chưa cấu hình phần trăm phí sàn';
    END IF;

    v_tien_san := ROUND(
        COALESCE(NEW.phi_van_chuyen, 0) * v_phan_tram_san / 100,
        0
    );
    v_tien_shipper := COALESCE(NEW.phi_van_chuyen, 0) - v_tien_san;

    INSERT INTO public.luong_shipper (
        nhan_vien_id,
        don_hang_id,
        phi_van_chuyen,
        phan_tram_san,
        tien_san,
        tien_shipper
    ) VALUES (
        NEW.nhan_vien_hien_tai_id,
        NEW.id,
        COALESCE(NEW.phi_van_chuyen, 0),
        v_phan_tram_san,
        v_tien_san,
        v_tien_shipper
    )
    ON CONFLICT (don_hang_id) DO NOTHING;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_tu_dong_ghi_luong_shipper
    ON public.don_hang;

CREATE TRIGGER trg_tu_dong_ghi_luong_shipper
AFTER UPDATE OF trang_thai ON public.don_hang
FOR EACH ROW
WHEN (NEW.trang_thai = 'DA_GIAO_HANG')
EXECUTE FUNCTION public.tu_dong_ghi_luong_shipper();

-- Ghi bổ sung các đơn đã giao trước khi cài trigger này.
INSERT INTO public.luong_shipper (
    nhan_vien_id,
    don_hang_id,
    phi_van_chuyen,
    phan_tram_san,
    tien_san,
    tien_shipper,
    ngay_ghi_nhan
)
SELECT
    dh.nhan_vien_hien_tai_id,
    dh.id,
    COALESCE(dh.phi_van_chuyen, 0),
    pvc.phan_tram_san,
    ROUND(COALESCE(dh.phi_van_chuyen, 0) * pvc.phan_tram_san / 100, 0),
    COALESCE(dh.phi_van_chuyen, 0) -
        ROUND(COALESCE(dh.phi_van_chuyen, 0) * pvc.phan_tram_san / 100, 0),
    COALESCE(dh.ngay_giao_hang, NOW())
FROM public.don_hang dh
CROSS JOIN public.phi_van_chuyen pvc
WHERE pvc.id = 1
  AND dh.trang_thai = 'DA_GIAO_HANG'
  AND dh.nhan_vien_hien_tai_id IS NOT NULL
ON CONFLICT (don_hang_id) DO NOTHING;

REVOKE ALL ON TABLE public.luong_shipper FROM anon, authenticated;

DROP FUNCTION IF EXISTS public.lich_su_don_hang_shipper();

CREATE OR REPLACE FUNCTION public.lich_su_don_hang_shipper()
RETURNS TABLE (
    id BIGINT,
    ma_van_don VARCHAR,
    nguoi_gui_ten VARCHAR,
    nguoi_gui_dia_chi TEXT,
    nguoi_nhan_dia_chi TEXT,
    phi_van_chuyen NUMERIC,
    phan_tram_san NUMERIC,
    tien_san NUMERIC,
    tien_shipper NUMERIC,
    ngay_giao_hang TIMESTAMPTZ,
    trang_thai_thanh_toan VARCHAR
)
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
    SELECT
        dh.id,
        dh.ma_van_don,
        dh.nguoi_gui_ten,
        dh.nguoi_gui_dia_chi,
        dh.nguoi_nhan_dia_chi,
        ls.phi_van_chuyen,
        ls.phan_tram_san,
        ls.tien_san,
        ls.tien_shipper,
        dh.ngay_giao_hang,
        ls.trang_thai
    FROM public.luong_shipper ls
    JOIN public.don_hang dh ON dh.id = ls.don_hang_id
    JOIN public.nhan_vien nv ON nv.id = ls.nhan_vien_id
    WHERE nv.auth_user_id = auth.uid()
      AND dh.trang_thai = 'DA_GIAO_HANG'
    ORDER BY dh.ngay_giao_hang DESC NULLS LAST, ls.ngay_ghi_nhan DESC;
$$;

REVOKE ALL ON FUNCTION public.lich_su_don_hang_shipper() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.lich_su_don_hang_shipper() TO authenticated;

-- Xem lương đã ghi nhận:
-- SELECT * FROM public.luong_shipper ORDER BY ngay_ghi_nhan DESC;
