-- ============================================================
-- VÍ HOẠT ĐỘNG CỦA SHIPPER
-- Chạy file này trước shipper_nearby_orders_setup.sql.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.vi_shipper (
    nhan_vien_id BIGINT PRIMARY KEY
        REFERENCES public.nhan_vien(id) ON DELETE CASCADE,
    so_du NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (so_du >= 0),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.giao_dich_vi_shipper (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nhan_vien_id BIGINT NOT NULL
        REFERENCES public.nhan_vien(id) ON DELETE CASCADE,
    don_hang_id BIGINT REFERENCES public.don_hang(id) ON DELETE RESTRICT,
    loai VARCHAR(30) NOT NULL CHECK (
        loai IN (
            'NAP_TIEN', 'TAM_GIU_COD', 'HOAN_COD',
            'THU_NHAP_GIAO_HANG', 'DIEU_CHINH'
        )
    ),
    so_tien NUMERIC(14,2) NOT NULL CHECK (so_tien > 0),
    so_du_sau NUMERIC(14,2) NOT NULL CHECK (so_du_sau >= 0),
    noi_dung TEXT,
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.giao_dich_vi_shipper
    DROP CONSTRAINT IF EXISTS giao_dich_vi_shipper_loai_check;
ALTER TABLE public.giao_dich_vi_shipper
    DROP CONSTRAINT IF EXISTS chk_giao_dich_vi_shipper_loai;
ALTER TABLE public.giao_dich_vi_shipper
    ADD CONSTRAINT chk_giao_dich_vi_shipper_loai CHECK (
        loai IN (
            'NAP_TIEN', 'TAM_GIU_COD', 'HOAN_COD',
            'THU_NHAP_GIAO_HANG', 'DIEU_CHINH'
        )
    );

CREATE UNIQUE INDEX IF NOT EXISTS uq_giao_dich_vi_tam_giu_cod
    ON public.giao_dich_vi_shipper(don_hang_id, loai)
    WHERE loai = 'TAM_GIU_COD';

CREATE UNIQUE INDEX IF NOT EXISTS uq_giao_dich_vi_thu_nhap_don
    ON public.giao_dich_vi_shipper(don_hang_id, loai)
    WHERE loai = 'THU_NHAP_GIAO_HANG';

CREATE INDEX IF NOT EXISTS idx_giao_dich_vi_shipper
    ON public.giao_dich_vi_shipper(nhan_vien_id, ngay_tao DESC);

CREATE TABLE IF NOT EXISTS public.yeu_cau_nap_vi_shipper (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nhan_vien_id BIGINT NOT NULL
        REFERENCES public.nhan_vien(id) ON DELETE CASCADE,
    so_tien NUMERIC(14,2) NOT NULL CHECK (so_tien >= 10000),
    phuong_thuc VARCHAR(30) NOT NULL DEFAULT 'CHUYEN_KHOAN',
    trang_thai VARCHAR(30) NOT NULL DEFAULT 'CHO_DUYET'
        CHECK (trang_thai IN ('CHO_DUYET', 'DA_DUYET', 'TU_CHOI')),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ngay_xu_ly TIMESTAMPTZ
);

REVOKE ALL ON TABLE public.vi_shipper FROM anon, authenticated;
REVOKE ALL ON TABLE public.giao_dich_vi_shipper FROM anon, authenticated;
REVOKE ALL ON TABLE public.yeu_cau_nap_vi_shipper FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.thong_tin_vi_shipper()
RETURNS TABLE (
    so_du NUMERIC,
    tong_cho_nap NUMERIC
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_nhan_vien_id BIGINT;
BEGIN
    SELECT nv.id INTO v_nhan_vien_id
    FROM public.nhan_vien nv
    WHERE nv.auth_user_id = auth.uid()
      AND nv.vai_tro IN ('SHIPPER', 'VAN_CHUYEN');

    IF v_nhan_vien_id IS NULL THEN
        RAISE EXCEPTION 'Không tìm thấy tài khoản shipper';
    END IF;

    INSERT INTO public.vi_shipper(nhan_vien_id)
    VALUES (v_nhan_vien_id)
    ON CONFLICT (nhan_vien_id) DO NOTHING;

    RETURN QUERY
    SELECT
        v.so_du,
        COALESCE(SUM(yc.so_tien) FILTER (
            WHERE yc.trang_thai = 'CHO_DUYET'
        ), 0)::NUMERIC
    FROM public.vi_shipper v
    LEFT JOIN public.yeu_cau_nap_vi_shipper yc
      ON yc.nhan_vien_id = v.nhan_vien_id
    WHERE v.nhan_vien_id = v_nhan_vien_id
    GROUP BY v.so_du;
END;
$$;

CREATE OR REPLACE FUNCTION public.lich_su_giao_dich_vi_shipper()
RETURNS TABLE (
    id BIGINT,
    loai VARCHAR,
    so_tien NUMERIC,
    so_du_sau NUMERIC,
    noi_dung TEXT,
    ma_van_don VARCHAR,
    ngay_tao TIMESTAMPTZ
)
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
    SELECT gd.id, gd.loai, gd.so_tien, gd.so_du_sau, gd.noi_dung,
           dh.ma_van_don, gd.ngay_tao
    FROM public.giao_dich_vi_shipper gd
    JOIN public.nhan_vien nv ON nv.id = gd.nhan_vien_id
    LEFT JOIN public.don_hang dh ON dh.id = gd.don_hang_id
    WHERE nv.auth_user_id = auth.uid()
    ORDER BY gd.ngay_tao DESC
    LIMIT 100;
$$;

CREATE OR REPLACE FUNCTION public.tao_yeu_cau_nap_vi_shipper(
    p_so_tien NUMERIC,
    p_phuong_thuc TEXT DEFAULT 'CHUYEN_KHOAN'
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_nhan_vien_id BIGINT;
    v_id BIGINT;
BEGIN
    IF p_so_tien < 10000 THEN
        RAISE EXCEPTION 'Số tiền nạp tối thiểu là 10.000đ';
    END IF;

    SELECT nv.id INTO v_nhan_vien_id
    FROM public.nhan_vien nv
    WHERE nv.auth_user_id = auth.uid()
      AND nv.vai_tro IN ('SHIPPER', 'VAN_CHUYEN')
      AND nv.trang_thai = 'HOAT_DONG'
      AND nv.trang_thai_duyet = 'DA_DUYET';

    IF v_nhan_vien_id IS NULL THEN
        RAISE EXCEPTION 'Tài khoản shipper chưa được duyệt';
    END IF;

    INSERT INTO public.yeu_cau_nap_vi_shipper(
        nhan_vien_id, so_tien, phuong_thuc
    ) VALUES (
        v_nhan_vien_id, p_so_tien, UPPER(BTRIM(p_phuong_thuc))
    ) RETURNING id INTO v_id;

    RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.duyet_yeu_cau_nap_vi_shipper(
    p_yeu_cau_id BIGINT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_yeu_cau public.yeu_cau_nap_vi_shipper%ROWTYPE;
    v_so_du_moi NUMERIC;
BEGIN
    SELECT * INTO v_yeu_cau
    FROM public.yeu_cau_nap_vi_shipper
    WHERE id = p_yeu_cau_id
    FOR UPDATE;

    IF NOT FOUND OR v_yeu_cau.trang_thai <> 'CHO_DUYET' THEN
        RAISE EXCEPTION 'Yêu cầu nạp không còn chờ duyệt';
    END IF;

    INSERT INTO public.vi_shipper(nhan_vien_id, so_du)
    VALUES (v_yeu_cau.nhan_vien_id, v_yeu_cau.so_tien)
    ON CONFLICT (nhan_vien_id) DO UPDATE SET
        so_du = public.vi_shipper.so_du + EXCLUDED.so_du,
        ngay_cap_nhat = NOW()
    RETURNING so_du INTO v_so_du_moi;

    UPDATE public.yeu_cau_nap_vi_shipper
    SET trang_thai = 'DA_DUYET', ngay_xu_ly = NOW()
    WHERE id = p_yeu_cau_id;

    INSERT INTO public.giao_dich_vi_shipper(
        nhan_vien_id, loai, so_tien, so_du_sau, noi_dung
    ) VALUES (
        v_yeu_cau.nhan_vien_id, 'NAP_TIEN', v_yeu_cau.so_tien,
        v_so_du_moi, 'Nạp tiền vào ví shipper'
    );
END;
$$;

CREATE OR REPLACE FUNCTION public.tam_giu_cod_vi_shipper(
    p_nhan_vien_id BIGINT,
    p_don_hang_id BIGINT,
    p_so_tien NUMERIC
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_so_du NUMERIC;
BEGIN
    IF COALESCE(p_so_tien, 0) <= 0 THEN RETURN; END IF;

    INSERT INTO public.vi_shipper(nhan_vien_id)
    VALUES (p_nhan_vien_id)
    ON CONFLICT (nhan_vien_id) DO NOTHING;

    SELECT so_du INTO v_so_du
    FROM public.vi_shipper
    WHERE nhan_vien_id = p_nhan_vien_id
    FOR UPDATE;

    IF v_so_du < p_so_tien THEN
        RAISE EXCEPTION 'Số dư ví không đủ. Đơn COD %đ, số dư hiện tại %đ',
            ROUND(p_so_tien), ROUND(v_so_du);
    END IF;

    IF EXISTS (
        SELECT 1 FROM public.giao_dich_vi_shipper
        WHERE don_hang_id = p_don_hang_id AND loai = 'TAM_GIU_COD'
    ) THEN RETURN; END IF;

    v_so_du := v_so_du - p_so_tien;
    UPDATE public.vi_shipper
    SET so_du = v_so_du, ngay_cap_nhat = NOW()
    WHERE nhan_vien_id = p_nhan_vien_id;

    INSERT INTO public.giao_dich_vi_shipper(
        nhan_vien_id, don_hang_id, loai, so_tien, so_du_sau, noi_dung
    ) VALUES (
        p_nhan_vien_id, p_don_hang_id, 'TAM_GIU_COD', p_so_tien,
        v_so_du, 'Tạm giữ tiền thu hộ khi nhận đơn'
    );
END;
$$;

CREATE OR REPLACE FUNCTION public.cong_thu_nhap_vi_shipper(
    p_nhan_vien_id BIGINT,
    p_don_hang_id BIGINT,
    p_so_tien NUMERIC
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_so_du_moi NUMERIC;
BEGIN
    IF COALESCE(p_so_tien, 0) <= 0 THEN RETURN; END IF;

    -- Khóa theo đơn để hai request đồng thời không thể cộng thu nhập hai lần.
    PERFORM pg_advisory_xact_lock(p_don_hang_id);

    IF EXISTS (
        SELECT 1 FROM public.giao_dich_vi_shipper
        WHERE don_hang_id = p_don_hang_id
          AND loai = 'THU_NHAP_GIAO_HANG'
    ) THEN RETURN; END IF;

    INSERT INTO public.vi_shipper(nhan_vien_id, so_du)
    VALUES (p_nhan_vien_id, p_so_tien)
    ON CONFLICT (nhan_vien_id) DO UPDATE SET
        so_du = public.vi_shipper.so_du + EXCLUDED.so_du,
        ngay_cap_nhat = NOW()
    RETURNING so_du INTO v_so_du_moi;

    INSERT INTO public.giao_dich_vi_shipper(
        nhan_vien_id, don_hang_id, loai,
        so_tien, so_du_sau, noi_dung
    ) VALUES (
        p_nhan_vien_id, p_don_hang_id, 'THU_NHAP_GIAO_HANG',
        p_so_tien, v_so_du_moi,
        'Cộng thu nhập khi giao hàng thành công'
    )
    ON CONFLICT DO NOTHING;
END;
$$;

REVOKE ALL ON FUNCTION public.thong_tin_vi_shipper() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.lich_su_giao_dich_vi_shipper() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tao_yeu_cau_nap_vi_shipper(NUMERIC, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.duyet_yeu_cau_nap_vi_shipper(BIGINT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tam_giu_cod_vi_shipper(BIGINT, BIGINT, NUMERIC) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.cong_thu_nhap_vi_shipper(BIGINT, BIGINT, NUMERIC) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.thong_tin_vi_shipper() TO authenticated;
GRANT EXECUTE ON FUNCTION public.lich_su_giao_dich_vi_shipper() TO authenticated;
GRANT EXECUTE ON FUNCTION public.tao_yeu_cau_nap_vi_shipper(NUMERIC, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.duyet_yeu_cau_nap_vi_shipper(BIGINT) TO service_role;
GRANT EXECUTE ON FUNCTION public.tam_giu_cod_vi_shipper(BIGINT, BIGINT, NUMERIC) TO service_role;
GRANT EXECUTE ON FUNCTION public.cong_thu_nhap_vi_shipper(BIGINT, BIGINT, NUMERIC) TO service_role;

-- ============================================================
-- DỮ LIỆU MẪU
-- Gán cho shipper đầu tiên (ID nhỏ nhất) và không tạo trùng khi chạy lại.
-- ============================================================
DO $$
DECLARE
    v_nhan_vien_id BIGINT;
    v_so_du_moi NUMERIC;
BEGIN
    SELECT nv.id INTO v_nhan_vien_id
    FROM public.nhan_vien nv
    WHERE nv.vai_tro = 'SHIPPER'
    ORDER BY nv.id
    LIMIT 1;

    IF v_nhan_vien_id IS NULL THEN
        RAISE NOTICE 'Chưa có shipper, bỏ qua dữ liệu ví mẫu';
        RETURN;
    END IF;

    INSERT INTO public.vi_shipper(nhan_vien_id, so_du)
    VALUES (v_nhan_vien_id, 0)
    ON CONFLICT (nhan_vien_id) DO NOTHING;

    IF NOT EXISTS (
        SELECT 1
        FROM public.giao_dich_vi_shipper gd
        WHERE gd.nhan_vien_id = v_nhan_vien_id
          AND gd.loai = 'NAP_TIEN'
          AND gd.noi_dung = 'Dữ liệu mẫu: số dư khởi tạo ví shipper'
    ) THEN
        UPDATE public.vi_shipper
        SET so_du = so_du + 200000,
            ngay_cap_nhat = NOW()
        WHERE nhan_vien_id = v_nhan_vien_id
        RETURNING so_du INTO v_so_du_moi;

        INSERT INTO public.giao_dich_vi_shipper(
            nhan_vien_id,
            loai,
            so_tien,
            so_du_sau,
            noi_dung
        ) VALUES (
            v_nhan_vien_id,
            'NAP_TIEN',
            200000,
            v_so_du_moi,
            'Dữ liệu mẫu: số dư khởi tạo ví shipper'
        );
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM public.yeu_cau_nap_vi_shipper yc
        WHERE yc.nhan_vien_id = v_nhan_vien_id
          AND yc.phuong_thuc = 'CHUYEN_KHOAN_MAU'
    ) THEN
        INSERT INTO public.yeu_cau_nap_vi_shipper(
            nhan_vien_id,
            so_tien,
            phuong_thuc,
            trang_thai
        ) VALUES (
            v_nhan_vien_id,
            100000,
            'CHUYEN_KHOAN_MAU',
            'CHO_DUYET'
        );
    END IF;
END;
$$;

-- Quản trị viên duyệt yêu cầu nạp trong SQL Editor:
-- SELECT public.duyet_yeu_cau_nap_vi_shipper(ID_YEU_CAU);
