-- ============================================================
-- VÍ DÙNG CHUNG CHO KHÁCH HÀNG VÀ NHÂN VIÊN
-- Chạy sau shipper_wallet_setup.sql và trước shipper_nearby_orders_setup.sql.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.vi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    khach_hang_id BIGINT UNIQUE
        REFERENCES public.khach_hang(id) ON DELETE CASCADE,
    nhan_vien_id BIGINT UNIQUE
        REFERENCES public.nhan_vien(id) ON DELETE CASCADE,
    so_du NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (so_du >= 0),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_vi_chi_mot_chu_so_huu CHECK (
        (khach_hang_id IS NOT NULL AND nhan_vien_id IS NULL)
        OR (khach_hang_id IS NULL AND nhan_vien_id IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS public.giao_dich_vi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vi_id BIGINT NOT NULL REFERENCES public.vi(id) ON DELETE RESTRICT,
    don_hang_id BIGINT REFERENCES public.don_hang(id) ON DELETE RESTRICT,
    loai VARCHAR(40) NOT NULL CHECK (loai IN (
        'NAP_TIEN', 'RUT_TIEN', 'TRU_COD', 'NHAN_COD',
        'HOAN_COD', 'THU_NHAP_GIAO_HANG', 'DIEU_CHINH'
    )),
    so_tien NUMERIC(14,2) NOT NULL CHECK (so_tien > 0),
    so_du_sau NUMERIC(14,2) NOT NULL CHECK (so_du_sau >= 0),
    noi_dung TEXT,
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.giao_dich_vi
    DROP CONSTRAINT IF EXISTS giao_dich_vi_loai_check;
ALTER TABLE public.giao_dich_vi
    DROP CONSTRAINT IF EXISTS chk_giao_dich_vi_loai;
ALTER TABLE public.giao_dich_vi
    ADD CONSTRAINT chk_giao_dich_vi_loai CHECK (loai IN (
        'NAP_TIEN', 'RUT_TIEN', 'YEU_CAU_RUT', 'HOAN_RUT',
        'TRU_COD', 'NHAN_COD', 'HOAN_COD',
        'THU_NHAP_GIAO_HANG', 'DIEU_CHINH'
    ));

CREATE UNIQUE INDEX IF NOT EXISTS uq_giao_dich_vi_don_loai
    ON public.giao_dich_vi(vi_id, don_hang_id, loai)
    WHERE don_hang_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_giao_dich_vi_lich_su
    ON public.giao_dich_vi(vi_id, ngay_tao DESC);

CREATE TABLE IF NOT EXISTS public.yeu_cau_nap_vi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vi_id BIGINT NOT NULL REFERENCES public.vi(id) ON DELETE CASCADE,
    so_tien NUMERIC(14,2) NOT NULL CHECK (so_tien >= 10000),
    phuong_thuc VARCHAR(30) NOT NULL DEFAULT 'CHUYEN_KHOAN',
    trang_thai VARCHAR(30) NOT NULL DEFAULT 'CHO_DUYET'
        CHECK (trang_thai IN ('CHO_DUYET', 'DA_DUYET', 'TU_CHOI')),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ngay_xu_ly TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.yeu_cau_rut_vi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vi_id BIGINT NOT NULL REFERENCES public.vi(id) ON DELETE CASCADE,
    so_tien NUMERIC(14,2) NOT NULL CHECK (so_tien >= 50000),
    ngan_hang VARCHAR(100) NOT NULL,
    so_tai_khoan VARCHAR(50) NOT NULL,
    chu_tai_khoan VARCHAR(150) NOT NULL,
    trang_thai VARCHAR(30) NOT NULL DEFAULT 'CHO_DUYET'
        CHECK (trang_thai IN ('CHO_DUYET', 'DA_DUYET', 'TU_CHOI')),
    ly_do_tu_choi TEXT,
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ngay_xu_ly TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.yeu_cau_nap_rut_vi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vi_id BIGINT NOT NULL REFERENCES public.vi(id) ON DELETE CASCADE,
    loai VARCHAR(20) NOT NULL CHECK (loai IN ('NAP_TIEN', 'RUT_TIEN')),
    so_tien NUMERIC(14,2) NOT NULL CHECK (so_tien > 0),
    phuong_thuc VARCHAR(30),
    ngan_hang VARCHAR(100),
    so_tai_khoan VARCHAR(50),
    chu_tai_khoan VARCHAR(150),
    trang_thai VARCHAR(30) NOT NULL DEFAULT 'CHO_DUYET'
        CHECK (trang_thai IN ('CHO_DUYET', 'DA_DUYET', 'TU_CHOI')),
    ly_do_tu_choi TEXT,
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ngay_xu_ly TIMESTAMPTZ,
    nguon_bang VARCHAR(30),
    nguon_id BIGINT,
    CONSTRAINT chk_yeu_cau_nap_rut_thong_tin CHECK (
        (loai = 'NAP_TIEN' AND phuong_thuc IS NOT NULL)
        OR
        (loai = 'RUT_TIEN' AND ngan_hang IS NOT NULL
         AND so_tai_khoan IS NOT NULL AND chu_tai_khoan IS NOT NULL)
    )
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_yeu_cau_nap_rut_nguon
    ON public.yeu_cau_nap_rut_vi(nguon_bang, nguon_id)
    WHERE nguon_bang IS NOT NULL AND nguon_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.tai_khoan_ngan_hang_vi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vi_id BIGINT NOT NULL UNIQUE REFERENCES public.vi(id) ON DELETE CASCADE,
    ngan_hang VARCHAR(100) NOT NULL,
    so_tai_khoan VARCHAR(50) NOT NULL,
    chu_tai_khoan VARCHAR(150) NOT NULL,
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.giao_dich_vi
    ADD COLUMN IF NOT EXISTS yeu_cau_nap_rut_id BIGINT
        REFERENCES public.yeu_cau_nap_rut_vi(id) ON DELETE RESTRICT;
ALTER TABLE public.giao_dich_vi
    ADD COLUMN IF NOT EXISTS yeu_cau_rut_id BIGINT;
CREATE UNIQUE INDEX IF NOT EXISTS uq_giao_dich_vi_yeu_cau_nap_rut
    ON public.giao_dich_vi(yeu_cau_nap_rut_id, loai)
    WHERE yeu_cau_nap_rut_id IS NOT NULL;

-- Bảng đệm tương thích chỉ tồn tại trong lúc migration nếu hệ thống cũ đã
-- được dọn ở lần chạy trước; cuối file luôn xóa các bảng này.
CREATE TABLE IF NOT EXISTS public.vi_shipper (
    nhan_vien_id BIGINT PRIMARY KEY
        REFERENCES public.nhan_vien(id) ON DELETE CASCADE,
    so_du NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (so_du >= 0),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS public.giao_dich_vi_shipper (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nhan_vien_id BIGINT NOT NULL
        REFERENCES public.nhan_vien(id) ON DELETE CASCADE,
    don_hang_id BIGINT REFERENCES public.don_hang(id) ON DELETE RESTRICT,
    loai VARCHAR(40) NOT NULL,
    so_tien NUMERIC(14,2) NOT NULL,
    so_du_sau NUMERIC(14,2) NOT NULL,
    noi_dung TEXT,
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS public.yeu_cau_nap_vi_shipper (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nhan_vien_id BIGINT NOT NULL
        REFERENCES public.nhan_vien(id) ON DELETE CASCADE,
    so_tien NUMERIC(14,2) NOT NULL,
    phuong_thuc VARCHAR(30) NOT NULL DEFAULT 'CHUYEN_KHOAN',
    trang_thai VARCHAR(30) NOT NULL DEFAULT 'CHO_DUYET',
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ngay_xu_ly TIMESTAMPTZ
);

REVOKE ALL ON TABLE public.vi FROM anon, authenticated;
REVOKE ALL ON TABLE public.giao_dich_vi FROM anon, authenticated;
REVOKE ALL ON TABLE public.yeu_cau_nap_vi FROM anon, authenticated;
REVOKE ALL ON TABLE public.yeu_cau_rut_vi FROM anon, authenticated;
REVOKE ALL ON TABLE public.yeu_cau_nap_rut_vi FROM anon, authenticated;
REVOKE ALL ON TABLE public.tai_khoan_ngan_hang_vi FROM anon, authenticated;

-- Chuyển số dư shipper cũ sang ví chung, không cộng trùng khi chạy lại.
INSERT INTO public.vi(nhan_vien_id, so_du, ngay_cap_nhat)
SELECT vs.nhan_vien_id, vs.so_du, vs.ngay_cap_nhat
FROM public.vi_shipper vs
ON CONFLICT (nhan_vien_id) DO NOTHING;

-- Chuyển các yêu cầu nạp cũ sang bảng yêu cầu nạp dùng chung.
INSERT INTO public.yeu_cau_nap_vi(
    vi_id, so_tien, phuong_thuc, trang_thai, ngay_tao, ngay_xu_ly
)
SELECT v.id, yc.so_tien, yc.phuong_thuc, yc.trang_thai,
       yc.ngay_tao, yc.ngay_xu_ly
FROM public.yeu_cau_nap_vi_shipper yc
JOIN public.vi v ON v.nhan_vien_id = yc.nhan_vien_id
WHERE NOT EXISTS (
    SELECT 1 FROM public.yeu_cau_nap_vi moi
    WHERE moi.vi_id = v.id
      AND moi.so_tien = yc.so_tien
      AND moi.phuong_thuc = yc.phuong_thuc
      AND moi.ngay_tao = yc.ngay_tao
);

-- Gộp dữ liệu từ hai bảng yêu cầu cũ vào bảng nạp/rút dùng chung.
INSERT INTO public.yeu_cau_nap_rut_vi(
    vi_id, loai, so_tien, phuong_thuc, trang_thai,
    ngay_tao, ngay_xu_ly, nguon_bang, nguon_id
)
SELECT n.vi_id, 'NAP_TIEN', n.so_tien, n.phuong_thuc, n.trang_thai,
       n.ngay_tao, n.ngay_xu_ly, 'yeu_cau_nap_vi', n.id
FROM public.yeu_cau_nap_vi n
ON CONFLICT (nguon_bang, nguon_id) WHERE nguon_bang IS NOT NULL AND nguon_id IS NOT NULL
DO NOTHING;

INSERT INTO public.yeu_cau_nap_rut_vi(
    vi_id, loai, so_tien, ngan_hang, so_tai_khoan, chu_tai_khoan,
    trang_thai, ly_do_tu_choi, ngay_tao, ngay_xu_ly, nguon_bang, nguon_id
)
SELECT r.vi_id, 'RUT_TIEN', r.so_tien, r.ngan_hang, r.so_tai_khoan,
       r.chu_tai_khoan, r.trang_thai, r.ly_do_tu_choi,
       r.ngay_tao, r.ngay_xu_ly, 'yeu_cau_rut_vi', r.id
FROM public.yeu_cau_rut_vi r
ON CONFLICT (nguon_bang, nguon_id) WHERE nguon_bang IS NOT NULL AND nguon_id IS NOT NULL
DO NOTHING;

-- Chuyển liên kết giao dịch rút cũ sang ID yêu cầu dùng chung.
UPDATE public.giao_dich_vi gd
SET yeu_cau_nap_rut_id = moi.id
FROM public.yeu_cau_nap_rut_vi moi
WHERE gd.yeu_cau_rut_id IS NOT NULL
  AND moi.nguon_bang = 'yeu_cau_rut_vi'
  AND moi.nguon_id = gd.yeu_cau_rut_id
  AND gd.yeu_cau_nap_rut_id IS NULL;

DROP FUNCTION IF EXISTS public.thong_tin_vi();
CREATE OR REPLACE FUNCTION public.thong_tin_vi()
RETURNS TABLE (
    so_du NUMERIC,
    tong_cho_nap NUMERIC,
    tong_cho_rut NUMERIC
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_khach_hang_id BIGINT;
    v_nhan_vien_id BIGINT;
    v_vi_id BIGINT;
BEGIN
    SELECT kh.id INTO v_khach_hang_id
    FROM public.khach_hang kh WHERE kh.auth_user_id = auth.uid();

    IF v_khach_hang_id IS NULL THEN
        SELECT nv.id INTO v_nhan_vien_id
        FROM public.nhan_vien nv WHERE nv.auth_user_id = auth.uid();
    END IF;

    IF v_khach_hang_id IS NOT NULL THEN
        INSERT INTO public.vi(khach_hang_id) VALUES (v_khach_hang_id)
        ON CONFLICT (khach_hang_id) DO UPDATE SET khach_hang_id = EXCLUDED.khach_hang_id
        RETURNING id INTO v_vi_id;
    ELSIF v_nhan_vien_id IS NOT NULL THEN
        INSERT INTO public.vi(nhan_vien_id) VALUES (v_nhan_vien_id)
        ON CONFLICT (nhan_vien_id) DO UPDATE SET nhan_vien_id = EXCLUDED.nhan_vien_id
        RETURNING id INTO v_vi_id;
    ELSE
        RAISE EXCEPTION 'Không tìm thấy người dùng của ví';
    END IF;

    RETURN QUERY
    SELECT v.so_du,
           COALESCE((SELECT SUM(n.so_tien) FROM public.yeu_cau_nap_rut_vi n
                     WHERE n.vi_id = v.id AND n.loai = 'NAP_TIEN'
                       AND n.trang_thai = 'CHO_DUYET'), 0)::NUMERIC,
           COALESCE((SELECT SUM(r.so_tien) FROM public.yeu_cau_nap_rut_vi r
                     WHERE r.vi_id = v.id AND r.loai = 'RUT_TIEN'
                       AND r.trang_thai = 'CHO_DUYET'), 0)::NUMERIC
    FROM public.vi v
    WHERE v.id = v_vi_id
    GROUP BY v.id, v.so_du;
END;
$$;

CREATE OR REPLACE FUNCTION public.lich_su_giao_dich_vi()
RETURNS TABLE (
    id BIGINT, loai VARCHAR, so_tien NUMERIC, so_du_sau NUMERIC,
    noi_dung TEXT, ma_van_don VARCHAR, ngay_tao TIMESTAMPTZ
)
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
    SELECT gd.id, gd.loai, gd.so_tien, gd.so_du_sau, gd.noi_dung,
           dh.ma_van_don, gd.ngay_tao
    FROM public.giao_dich_vi gd
    JOIN public.vi v ON v.id = gd.vi_id
    LEFT JOIN public.don_hang dh ON dh.id = gd.don_hang_id
    LEFT JOIN public.khach_hang kh ON kh.id = v.khach_hang_id
    LEFT JOIN public.nhan_vien nv ON nv.id = v.nhan_vien_id
    WHERE kh.auth_user_id = auth.uid() OR nv.auth_user_id = auth.uid()
    ORDER BY gd.ngay_tao DESC
    LIMIT 100;
$$;

CREATE OR REPLACE FUNCTION public.tao_yeu_cau_nap_vi(
    p_so_tien NUMERIC,
    p_phuong_thuc TEXT DEFAULT 'CHUYEN_KHOAN'
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_vi_id BIGINT;
    v_id BIGINT;
BEGIN
    IF p_so_tien < 10000 THEN
        RAISE EXCEPTION 'Số tiền nạp tối thiểu là 10.000đ';
    END IF;

    PERFORM public.thong_tin_vi();
    SELECT v.id INTO v_vi_id
    FROM public.vi v
    LEFT JOIN public.khach_hang kh ON kh.id = v.khach_hang_id
    LEFT JOIN public.nhan_vien nv ON nv.id = v.nhan_vien_id
    WHERE kh.auth_user_id = auth.uid() OR nv.auth_user_id = auth.uid();

    INSERT INTO public.yeu_cau_nap_rut_vi(
        vi_id, loai, so_tien, phuong_thuc
    ) VALUES (
        v_vi_id, 'NAP_TIEN', p_so_tien, UPPER(BTRIM(p_phuong_thuc))
    )
    RETURNING id INTO v_id;
    RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.duyet_yeu_cau_nap_vi(p_yeu_cau_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_yeu_cau public.yeu_cau_nap_rut_vi%ROWTYPE;
    v_so_du_moi NUMERIC;
BEGIN
    SELECT * INTO v_yeu_cau FROM public.yeu_cau_nap_rut_vi
    WHERE id = p_yeu_cau_id AND loai = 'NAP_TIEN' FOR UPDATE;
    IF NOT FOUND OR v_yeu_cau.trang_thai <> 'CHO_DUYET' THEN
        RAISE EXCEPTION 'Yêu cầu nạp không còn chờ duyệt';
    END IF;

    UPDATE public.vi SET so_du = so_du + v_yeu_cau.so_tien, ngay_cap_nhat = NOW()
    WHERE id = v_yeu_cau.vi_id RETURNING so_du INTO v_so_du_moi;
    UPDATE public.yeu_cau_nap_rut_vi SET trang_thai = 'DA_DUYET', ngay_xu_ly = NOW()
    WHERE id = p_yeu_cau_id;
    INSERT INTO public.giao_dich_vi(vi_id, loai, so_tien, so_du_sau, noi_dung)
    VALUES (v_yeu_cau.vi_id, 'NAP_TIEN', v_yeu_cau.so_tien, v_so_du_moi, 'Nạp tiền vào ví');
END;
$$;

CREATE OR REPLACE FUNCTION public.lien_ket_tai_khoan_ngan_hang_vi(
    p_ngan_hang TEXT,
    p_so_tai_khoan TEXT,
    p_chu_tai_khoan TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE v_vi_id BIGINT;
BEGIN
    IF NULLIF(BTRIM(p_ngan_hang), '') IS NULL
       OR NULLIF(BTRIM(p_so_tai_khoan), '') IS NULL
       OR NULLIF(BTRIM(p_chu_tai_khoan), '') IS NULL THEN
        RAISE EXCEPTION 'Vui lòng nhập đầy đủ thông tin tài khoản ngân hàng';
    END IF;
    PERFORM public.thong_tin_vi();
    SELECT v.id INTO v_vi_id
    FROM public.vi v
    LEFT JOIN public.khach_hang kh ON kh.id = v.khach_hang_id
    LEFT JOIN public.nhan_vien nv ON nv.id = v.nhan_vien_id
    WHERE kh.auth_user_id = auth.uid() OR nv.auth_user_id = auth.uid();

    INSERT INTO public.tai_khoan_ngan_hang_vi(
        vi_id, ngan_hang, so_tai_khoan, chu_tai_khoan
    ) VALUES (
        v_vi_id, UPPER(BTRIM(p_ngan_hang)), BTRIM(p_so_tai_khoan),
        UPPER(BTRIM(p_chu_tai_khoan))
    ) ON CONFLICT (vi_id) DO UPDATE SET
        ngan_hang = EXCLUDED.ngan_hang,
        so_tai_khoan = EXCLUDED.so_tai_khoan,
        chu_tai_khoan = EXCLUDED.chu_tai_khoan,
        ngay_cap_nhat = NOW();
END;
$$;

CREATE OR REPLACE FUNCTION public.thong_tin_tai_khoan_ngan_hang_vi()
RETURNS TABLE (
    ngan_hang VARCHAR,
    so_tai_khoan VARCHAR,
    chu_tai_khoan VARCHAR
)
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
    SELECT tk.ngan_hang, tk.so_tai_khoan, tk.chu_tai_khoan
    FROM public.tai_khoan_ngan_hang_vi tk
    JOIN public.vi v ON v.id = tk.vi_id
    LEFT JOIN public.khach_hang kh ON kh.id = v.khach_hang_id
    LEFT JOIN public.nhan_vien nv ON nv.id = v.nhan_vien_id
    WHERE kh.auth_user_id = auth.uid() OR nv.auth_user_id = auth.uid();
$$;

DROP FUNCTION IF EXISTS public.tao_yeu_cau_rut_vi(NUMERIC, TEXT, TEXT, TEXT);
DROP FUNCTION IF EXISTS public.tao_yeu_cau_rut_vi(NUMERIC);
CREATE OR REPLACE FUNCTION public.tao_yeu_cau_rut_vi(
    p_so_tien NUMERIC
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_vi_id BIGINT;
    v_so_du NUMERIC;
    v_yeu_cau_id BIGINT;
    v_ngan_hang public.tai_khoan_ngan_hang_vi%ROWTYPE;
BEGIN
    IF p_so_tien < 50000 THEN
        RAISE EXCEPTION 'Số tiền rút tối thiểu là 50.000đ';
    END IF;
    PERFORM public.thong_tin_vi();
    SELECT v.id, v.so_du INTO v_vi_id, v_so_du
    FROM public.vi v
    LEFT JOIN public.khach_hang kh ON kh.id = v.khach_hang_id
    LEFT JOIN public.nhan_vien nv ON nv.id = v.nhan_vien_id
    WHERE kh.auth_user_id = auth.uid() OR nv.auth_user_id = auth.uid()
    FOR UPDATE OF v;

    IF v_vi_id IS NULL OR v_so_du < p_so_tien THEN
        RAISE EXCEPTION 'Số dư ví không đủ để rút %đ', ROUND(p_so_tien);
    END IF;

    SELECT * INTO v_ngan_hang
    FROM public.tai_khoan_ngan_hang_vi
    WHERE vi_id = v_vi_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Vui lòng liên kết tài khoản ngân hàng trước khi rút tiền';
    END IF;

    INSERT INTO public.yeu_cau_nap_rut_vi(
        vi_id, loai, so_tien, ngan_hang, so_tai_khoan, chu_tai_khoan
    ) VALUES (
        v_vi_id, 'RUT_TIEN', p_so_tien, v_ngan_hang.ngan_hang,
        v_ngan_hang.so_tai_khoan, v_ngan_hang.chu_tai_khoan
    ) RETURNING id INTO v_yeu_cau_id;

    UPDATE public.vi
    SET so_du = so_du - p_so_tien, ngay_cap_nhat = NOW()
    WHERE id = v_vi_id RETURNING so_du INTO v_so_du;

    INSERT INTO public.giao_dich_vi(
        vi_id, yeu_cau_nap_rut_id, loai, so_tien, so_du_sau, noi_dung
    ) VALUES (
        v_vi_id, v_yeu_cau_id, 'YEU_CAU_RUT', p_so_tien, v_so_du,
        'Tạm giữ tiền cho yêu cầu rút #' || v_yeu_cau_id
    );
    RETURN v_yeu_cau_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.duyet_yeu_cau_rut_vi(p_yeu_cau_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE v_yeu_cau public.yeu_cau_nap_rut_vi%ROWTYPE;
BEGIN
    SELECT * INTO v_yeu_cau FROM public.yeu_cau_nap_rut_vi
    WHERE id = p_yeu_cau_id AND loai = 'RUT_TIEN' FOR UPDATE;
    IF NOT FOUND OR v_yeu_cau.trang_thai <> 'CHO_DUYET' THEN
        RAISE EXCEPTION 'Yêu cầu rút không còn chờ duyệt';
    END IF;
    UPDATE public.yeu_cau_nap_rut_vi
    SET trang_thai = 'DA_DUYET', ngay_xu_ly = NOW()
    WHERE id = p_yeu_cau_id;
    UPDATE public.giao_dich_vi
    SET loai = 'RUT_TIEN', noi_dung = 'Rút tiền đã được quản trị viên duyệt'
    WHERE yeu_cau_nap_rut_id = p_yeu_cau_id AND loai = 'YEU_CAU_RUT';
END;
$$;

CREATE OR REPLACE FUNCTION public.tu_choi_yeu_cau_rut_vi(
    p_yeu_cau_id BIGINT,
    p_ly_do TEXT DEFAULT NULL
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_yeu_cau public.yeu_cau_nap_rut_vi%ROWTYPE;
    v_so_du_moi NUMERIC;
BEGIN
    SELECT * INTO v_yeu_cau FROM public.yeu_cau_nap_rut_vi
    WHERE id = p_yeu_cau_id AND loai = 'RUT_TIEN' FOR UPDATE;
    IF NOT FOUND OR v_yeu_cau.trang_thai <> 'CHO_DUYET' THEN
        RAISE EXCEPTION 'Yêu cầu rút không còn chờ duyệt';
    END IF;
    UPDATE public.yeu_cau_nap_rut_vi
    SET trang_thai = 'TU_CHOI', ly_do_tu_choi = NULLIF(BTRIM(p_ly_do), ''),
        ngay_xu_ly = NOW()
    WHERE id = p_yeu_cau_id;
    UPDATE public.vi
    SET so_du = so_du + v_yeu_cau.so_tien, ngay_cap_nhat = NOW()
    WHERE id = v_yeu_cau.vi_id RETURNING so_du INTO v_so_du_moi;
    INSERT INTO public.giao_dich_vi(
        vi_id, yeu_cau_nap_rut_id, loai, so_tien, so_du_sau, noi_dung
    ) VALUES (
        v_yeu_cau.vi_id, v_yeu_cau.id, 'HOAN_RUT', v_yeu_cau.so_tien,
        v_so_du_moi, 'Hoàn tiền do yêu cầu rút bị từ chối'
    );
END;
$$;

-- Trừ COD của nhân viên và cộng cho khách hàng trong cùng một transaction.
CREATE OR REPLACE FUNCTION public.tam_giu_cod_vi_shipper(
    p_nhan_vien_id BIGINT,
    p_don_hang_id BIGINT,
    p_so_tien NUMERIC
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_vi_nhan_vien_id BIGINT;
    v_vi_khach_hang_id BIGINT;
    v_khach_hang_id BIGINT;
    v_so_du_nhan_vien NUMERIC;
    v_so_du_khach_hang NUMERIC;
BEGIN
    IF COALESCE(p_so_tien, 0) <= 0 THEN RETURN; END IF;
    PERFORM pg_advisory_xact_lock(p_don_hang_id);

    SELECT dh.khach_hang_id INTO v_khach_hang_id
    FROM public.don_hang dh WHERE dh.id = p_don_hang_id;
    IF v_khach_hang_id IS NULL THEN RAISE EXCEPTION 'Đơn hàng không có khách hàng'; END IF;

    INSERT INTO public.vi(nhan_vien_id) VALUES (p_nhan_vien_id)
    ON CONFLICT (nhan_vien_id) DO UPDATE SET nhan_vien_id = EXCLUDED.nhan_vien_id
    RETURNING id, so_du INTO v_vi_nhan_vien_id, v_so_du_nhan_vien;

    IF EXISTS (SELECT 1 FROM public.giao_dich_vi
               WHERE vi_id = v_vi_nhan_vien_id AND don_hang_id = p_don_hang_id
                 AND loai = 'TRU_COD') THEN RETURN; END IF;
    IF v_so_du_nhan_vien < p_so_tien THEN
        RAISE EXCEPTION 'Số dư ví không đủ. Đơn COD %đ, số dư hiện tại %đ',
            ROUND(p_so_tien), ROUND(v_so_du_nhan_vien);
    END IF;

    UPDATE public.vi SET so_du = so_du - p_so_tien, ngay_cap_nhat = NOW()
    WHERE id = v_vi_nhan_vien_id RETURNING so_du INTO v_so_du_nhan_vien;
    INSERT INTO public.giao_dich_vi(vi_id, don_hang_id, loai, so_tien, so_du_sau, noi_dung)
    VALUES (v_vi_nhan_vien_id, p_don_hang_id, 'TRU_COD', p_so_tien,
            v_so_du_nhan_vien, 'Khấu trừ tiền thu hộ khi giao thành công');

    INSERT INTO public.vi(khach_hang_id) VALUES (v_khach_hang_id)
    ON CONFLICT (khach_hang_id) DO UPDATE SET khach_hang_id = EXCLUDED.khach_hang_id
    RETURNING id INTO v_vi_khach_hang_id;
    UPDATE public.vi SET so_du = so_du + p_so_tien, ngay_cap_nhat = NOW()
    WHERE id = v_vi_khach_hang_id RETURNING so_du INTO v_so_du_khach_hang;
    INSERT INTO public.giao_dich_vi(vi_id, don_hang_id, loai, so_tien, so_du_sau, noi_dung)
    VALUES (v_vi_khach_hang_id, p_don_hang_id, 'NHAN_COD', p_so_tien,
            v_so_du_khach_hang, 'Nhận tiền COD từ đơn giao thành công');
END;
$$;

CREATE OR REPLACE FUNCTION public.cong_thu_nhap_vi_shipper(
    p_nhan_vien_id BIGINT,
    p_don_hang_id BIGINT,
    p_so_tien NUMERIC
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE v_vi_id BIGINT; v_so_du_moi NUMERIC;
BEGIN
    IF COALESCE(p_so_tien, 0) <= 0 THEN RETURN; END IF;
    PERFORM pg_advisory_xact_lock(p_don_hang_id);
    INSERT INTO public.vi(nhan_vien_id) VALUES (p_nhan_vien_id)
    ON CONFLICT (nhan_vien_id) DO UPDATE SET nhan_vien_id = EXCLUDED.nhan_vien_id
    RETURNING id INTO v_vi_id;
    IF EXISTS (SELECT 1 FROM public.giao_dich_vi
               WHERE vi_id = v_vi_id AND don_hang_id = p_don_hang_id
                 AND loai = 'THU_NHAP_GIAO_HANG') THEN RETURN; END IF;
    UPDATE public.vi SET so_du = so_du + p_so_tien, ngay_cap_nhat = NOW()
    WHERE id = v_vi_id RETURNING so_du INTO v_so_du_moi;
    INSERT INTO public.giao_dich_vi(vi_id, don_hang_id, loai, so_tien, so_du_sau, noi_dung)
    VALUES (v_vi_id, p_don_hang_id, 'THU_NHAP_GIAO_HANG', p_so_tien,
            v_so_du_moi, 'Cộng thu nhập khi giao hàng thành công');
END;
$$;

-- Tạo một dòng sao kê chuyển đổi cho số dư cũ của shipper.
INSERT INTO public.giao_dich_vi(
    vi_id, loai, so_tien, so_du_sau, noi_dung
)
SELECT v.id, 'DIEU_CHINH', v.so_du, v.so_du,
       'Chuyển số dư từ ví shipper cũ sang ví dùng chung'
FROM public.vi v
WHERE v.nhan_vien_id IS NOT NULL
  AND v.so_du > 0
  AND NOT EXISTS (
      SELECT 1 FROM public.giao_dich_vi gd
      WHERE gd.vi_id = v.id
        AND gd.noi_dung = 'Chuyển số dư từ ví shipper cũ sang ví dùng chung'
  );

-- Cộng bù COD của các đơn cũ đã khấu trừ khỏi ví shipper.
DO $$
DECLARE
    v_cu RECORD;
    v_vi_khach_hang_id BIGINT;
    v_so_du_moi NUMERIC;
BEGIN
    FOR v_cu IN
        SELECT gd.don_hang_id, gd.so_tien, dh.khach_hang_id
        FROM public.giao_dich_vi_shipper gd
        JOIN public.don_hang dh ON dh.id = gd.don_hang_id
        WHERE gd.loai = 'TAM_GIU_COD'
          AND dh.khach_hang_id IS NOT NULL
    LOOP
        INSERT INTO public.vi(khach_hang_id)
        VALUES (v_cu.khach_hang_id)
        ON CONFLICT (khach_hang_id) DO UPDATE
            SET khach_hang_id = EXCLUDED.khach_hang_id
        RETURNING id INTO v_vi_khach_hang_id;

        IF NOT EXISTS (
            SELECT 1 FROM public.giao_dich_vi gd
            WHERE gd.vi_id = v_vi_khach_hang_id
              AND gd.don_hang_id = v_cu.don_hang_id
              AND gd.loai = 'NHAN_COD'
        ) THEN
            UPDATE public.vi
            SET so_du = so_du + v_cu.so_tien,
                ngay_cap_nhat = NOW()
            WHERE id = v_vi_khach_hang_id
            RETURNING so_du INTO v_so_du_moi;

            INSERT INTO public.giao_dich_vi(
                vi_id, don_hang_id, loai, so_tien, so_du_sau, noi_dung
            ) VALUES (
                v_vi_khach_hang_id, v_cu.don_hang_id, 'NHAN_COD',
                v_cu.so_tien, v_so_du_moi,
                'Cộng bù tiền COD từ dữ liệu giao hàng cũ'
            );
        END IF;
    END LOOP;
END;
$$;

REVOKE ALL ON FUNCTION public.thong_tin_vi() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.lich_su_giao_dich_vi() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tao_yeu_cau_nap_vi(NUMERIC, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.duyet_yeu_cau_nap_vi(BIGINT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.lien_ket_tai_khoan_ngan_hang_vi(TEXT, TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.thong_tin_tai_khoan_ngan_hang_vi() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tao_yeu_cau_rut_vi(NUMERIC) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.duyet_yeu_cau_rut_vi(BIGINT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tu_choi_yeu_cau_rut_vi(BIGINT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tam_giu_cod_vi_shipper(BIGINT, BIGINT, NUMERIC) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.cong_thu_nhap_vi_shipper(BIGINT, BIGINT, NUMERIC) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.thong_tin_vi() TO authenticated;
GRANT EXECUTE ON FUNCTION public.lich_su_giao_dich_vi() TO authenticated;
GRANT EXECUTE ON FUNCTION public.tao_yeu_cau_nap_vi(NUMERIC, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.duyet_yeu_cau_nap_vi(BIGINT) TO service_role;
GRANT EXECUTE ON FUNCTION public.lien_ket_tai_khoan_ngan_hang_vi(TEXT, TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.thong_tin_tai_khoan_ngan_hang_vi() TO authenticated;
GRANT EXECUTE ON FUNCTION public.tao_yeu_cau_rut_vi(NUMERIC) TO authenticated;
GRANT EXECUTE ON FUNCTION public.duyet_yeu_cau_rut_vi(BIGINT) TO service_role;
GRANT EXECUTE ON FUNCTION public.tu_choi_yeu_cau_rut_vi(BIGINT, TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.tam_giu_cod_vi_shipper(BIGINT, BIGINT, NUMERIC) TO service_role;
GRANT EXECUTE ON FUNCTION public.cong_thu_nhap_vi_shipper(BIGINT, BIGINT, NUMERIC) TO service_role;

-- ============================================================
-- DỌN CÁC BẢNG VÍ SHIPPER CŨ SAU KHI MIGRATION HOÀN TẤT
-- ============================================================
DROP INDEX IF EXISTS public.uq_giao_dich_vi_yeu_cau_rut;
ALTER TABLE public.giao_dich_vi
    DROP COLUMN IF EXISTS yeu_cau_rut_id;

DROP TABLE IF EXISTS public.yeu_cau_nap_vi;
DROP TABLE IF EXISTS public.yeu_cau_rut_vi;

DROP FUNCTION IF EXISTS public.thong_tin_vi_shipper();
DROP FUNCTION IF EXISTS public.lich_su_giao_dich_vi_shipper();
DROP FUNCTION IF EXISTS public.tao_yeu_cau_nap_vi_shipper(NUMERIC, TEXT);
DROP FUNCTION IF EXISTS public.duyet_yeu_cau_nap_vi_shipper(BIGINT);

DROP TABLE IF EXISTS public.yeu_cau_nap_vi_shipper;
DROP TABLE IF EXISTS public.giao_dich_vi_shipper;
DROP TABLE IF EXISTS public.vi_shipper;

-- Yêu cầu PostgREST nạp lại danh sách RPC mới ngay sau migration.
NOTIFY pgrst, 'reload schema';
